#./cipherval -alphabet="rune" -wordfile="./rune.txt" -ciphertype="autokey" -text="ᚪ•ᛗᛝᛞᛡᚦᛉᛁᛗ␍ᛡᛞᛈᛝᚢᚹᚪᛗ•ᛏᚪᛝ•ᛝᚦᛡᚹᛋᚻ•ᛁᚳ•ᚫᛈᚫᚷᚩ•ᛗᛁᚪ•ᛖᚩ•ᛏᚹᚩ•ᚠᚣᚢᛏᛄ•ᚦᛄᛠᛖᚳᚾᛠ•ᚳᛠᛖ•ᚱᚩᚢᛉ•ᛞᚹᚻᛒᛝᚠᚪᚳᛄᚢ•ᚩᛄᛡᛠᛁᛚᚷᚻ•ᛒᚢᛄ•ᛉᚪᚳᚹᛡ•ᛗᚩᛈᚣᛞᛡᛚᛈ•ᛇᛁᚦᚱ•ᚣᚷᛗ•ᛉᛟᚷᛋ•ᛗᛈᛄᛟᛞ•ᛟᛏᛡᛟ•ᛏᛝᛁ•ᛗᛝᚣᚪᚫ•ᛝ•ᚱᚣᛄ•ᚾᛚᚢᛉᛒ•ᚻᛈᛄᚩᛠ•ᚷᚫᚹ•ᛉᛋᛞᚳ•ᚢᛏ•ᛟᚻᛇᚾᛈᛏ•ᛠᚣᛒᚢᚷ•ᚷᚪᛇ•ᚾᚷᚩᛖᛚᛗᛒᚦ•ᚣᛡᛟᛇᚣ•ᛗᚳᛟᚦ•ᛖᛚᚱᛇᛈᚱᛞᚣ•ᛉᛞ•ᛝᚣᛈ•ᛋᛖᛉᚹ•ᚳᚷᚠᛞᚱᛖ•ᛞᛖᚹᚩᛇᛟ•ᚻᚩᛟ•ᛒᛋ•ᚻᛠᚪᚳᛁᛗᛉᛄᛗᛖ•ᛗᛚ•ᚷᚩᛏᚦᛉᛖᛠᚱᚷᚣᛝ•ᚫᛗᛁᚹ•ᛋᛒ•ᛉᛗ•ᛋᛇᚷᛞᚦᚫ•ᚠᛡᚪᛒᚳᚢ•ᚹᚱ•ᛒᛠᚠᛉᛁᛗᚢᚳᛈᚻᛝᛚᛇ•ᛗᛋᛞᛡᛈᚠ•ᛒᚻᛇᚳ•ᛇᛖ•ᛠᛖᛁᚷᛉᚷᛋ•ᛖᛋᛇᚦᚦᛖᛋ•ᚦᛟ•ᚳᛠᛁᛗᚳᛉ•ᛞᛄᚢ•ᛒᛖᛁ␍"
#./cipherval -alphabet="runeglish" -wordfile="./runeglish.txt" -ciphertype="autokey" -text="A MINGDIOTHXIM␍IODPINGUWAM TAING INGTHIOWSH IC AEPAEGO MIA EO TWO FYUTJ THJEAECNEA CEAE ROUX DWHBINGFACJU OJIOEAILGH BUJ XACWIO MOPYDIOLP EOITHR YGM XOEGS MPJOED OETIOOE TINGI MINGYAAE ING RYJ NLUXB HPJOEA GAEW XSDC UT OEHEONPT EAYBUG GAEO NGOELMBTH YIOOEEOY MCOETH ELREOPRDY XD INGYP SEXW CGFDRE DEWOEOOE HOOE BS HEAACIMXJME ML GOTTHXEEARGYING AEMIW SB XM SEOGDTHAE FIOABCU WR BEAFXIMUCPHINGLEO MSDIOPF BHEOC EOE EAEIGXGS ESEOTHTHES THOE CEAIMCX DJU BEI␍"

./cipherval -alphabet="rune" -wordfile="./rune.txt" -ciphertype="autokey" -text="ᚱ•ᚾᚹᚳᚢᚣᛉᛖᚾ␍ᚢᚳᛋᚹᛡᛝᚱᚾ•ᛇᚱᚹ•ᚹᚣᚢᛝᛈᛚ•ᛖᛞ•ᚩᛋᚩᛟᚫ•ᚾᛖᚱ•ᛁᚫ•ᛇᛝᚫ•ᛠᚦᛡᛇᛒ•ᚣᛒᚠᛁᛞᛗᚠ•ᛞᚠᛁ•ᚪᚫᛡᛉ•ᚳᛝᛚᛄᚹᛠᚱᛞᛒᛡ•ᚫᛒᚢᚠᛖᚻᛟᛚ•ᛄᛡᛒ•ᛉᚱᛞᛝᚢ•ᚾᚫᛋᚦᚳᚢᚻᛋ•ᛏᛖᚣᚪ•ᚦᛟᚾ•ᛉᚷᛟᛈ•ᚾᛋᛒᚷᚳ•ᚷᛇᚢᚷ•ᛇᚹᛖ•ᚾᚹᚦᚱᚩ•ᚹ•ᚪᚦᛒ•ᛗᚻᛡᛉᛄ•ᛚᛋᛒᚫᚠ•ᛟᚩᛝ•ᛉᛈᚳᛞ•ᛡᛇ•ᚷᛚᛏᛗᛋᛇ•ᚠᚦᛄᛡᛟ•ᛟᚱᛏ•ᛗᛟᚫᛁᚻᚾᛄᚣ•ᚦᚢᚷᛏᚦ•ᚾᛞᚷᚣ•ᛁᚻᚪᛏᛋᚪᚳᚦ•ᛉᚳ•ᚹᚦᛋ•ᛈᛁᛉᛝ•ᛞᛟᛠᚳᚪᛁ•ᚳᛁᛝᚫᛏᚷ•ᛚᚫᚷ•ᛄᛈ•ᛚᚠᚱᛞᛖᚾᛉᛒᚾᛁ•ᚾᚻ•ᛟᚫᛇᚣᛉᛁᚠᚪᛟᚦᚹ•ᚩᚾᛖᛝ•ᛈᛄ•ᛉᚾ•ᛈᛏᛟᚳᚣᚩ•ᛠᚢᚱᛄᛞᛡ•ᛝᚪ•ᛄᚠᛠᛉᛖᚾᛡᛞᛋᛚᚹᚻᛏ•ᚾᛈᚳᚢᛋᛠ•ᛄᛚᛏᛞ•ᛏᛁ•ᚠᛁᛖᛟᛉᛟᛈ•ᛁᛈᛏᚣᚣᛁᛈ•ᚣᚷ•ᛞᚠᛖᚾᛞᛉ•ᚳᛒᛡ•ᛄᛁᛖ␍"
./cipherval -alphabet="runeglish" -wordfile="./runeglish.txt" -ciphertype="autokey" -text="R NWCUYXEN␍UCSWIOINGRN EORW WYUINGPL ED OSOOEAE NER IAE EOINGAE EATHIOEOB YBFIDMF DFI AAEIOX CINGLJWEARDBIO AEBUFEHOEL JIOB XRDINGU NAESTHCUHS TEYA THOEN XGOEP NSBGC GEOUG EOWE NWTHRO W ATHB MHIOXJ LSBAEF OEOING XPCD IOEO GLTMSEO FTHJIOOE OERT MOEAEIHNJY THUGTTH NDGY IHATSACTH XC WTHS PIXING DOEEACAI CIINGAETG LAEG JP LFRDENXBNI NH OEAEEOYXIFAOETHW ONEING PJ XN PTOECYO EAURJDIO INGA JFEAXENIODSLWHT NPCUSEA JLTD TI FIEOEXOEP IPTYYIP YG DFENDX CBIO JIE␍"

./cipherval -alphabet="rune" -wordfile="./rune.txt" -ciphertype="autokey" -text="ᚾ•ᚱᚷᚻᛇᛒᛉᚫᚱ␍ᛇᚻᛠᚷᛏᛟᚾᚱ•ᚢᚾᚷ•ᚷᛒᛇᛟᚠᛞ•ᚫᛚ•ᛁᛠᛁᛝᛖ•ᚱᚫᚾ•ᚩᛖ•ᚢᛟᛖ•ᛋᛄᛏᚢᚣ•ᛒᚣᛈᚩᛚᚪᛈ•ᛚᛈᚩ•ᛗᛖᛏᛉ•ᚻᛟᛞᚦᚷᛋᚾᛚᚣᛏ•ᛖᚣᛇᛈᚫᚳᛝᛞ•ᚦᛏᚣ•ᛉᚾᛚᛟᛇ•ᚱᛖᛠᛄᚻᛇᚳᛠ•ᛡᚫᛒᛗ•ᛄᛝᚱ•ᛉᚹᛝᚠ•ᚱᛠᚣᚹᚻ•ᚹᚢᛇᚹ•ᚢᚷᚫ•ᚱᚷᛄᚾᛁ•ᚷ•ᛗᛄᚣ•ᚪᚳᛏᛉᚦ•ᛞᛠᚣᛖᛈ•ᛝᛁᛟ•ᛉᚠᚻᛚ•ᛏᚢ•ᚹᛞᛡᚪᛠᚢ•ᛈᛄᚦᛏᛝ•ᛝᚾᛡ•ᚪᛝᛖᚩᚳᚱᚦᛒ•ᛄᛇᚹᛡᛄ•ᚱᛚᚹᛒ•ᚩᚳᛗᛡᛠᛗᚻᛄ•ᛉᚻ•ᚷᛄᛠ•ᚠᚩᛉᛟ•ᛚᛝᛋᚻᛗᚩ•ᚻᚩᛟᛖᛡᚹ•ᛞᛖᚹ•ᚦᚠ•ᛞᛈᚾᛚᚫᚱᛉᚣᚱᚩ•ᚱᚳ•ᛝᛖᚢᛒᛉᚩᛈᛗᛝᛄᚷ•ᛁᚱᚫᛟ•ᚠᚦ•ᛉᚱ•ᚠᛡᛝᚻᛒᛁ•ᛋᛇᚾᚦᛚᛏ•ᛟᛗ•ᚦᛈᛋᛉᚫᚱᛏᛚᛠᛞᚷᚳᛡ•ᚱᚠᚻᛇᛠᛋ•ᚦᛞᛡᛚ•ᛡᚩ•ᛈᚩᚫᛝᛉᛝᚠ•ᚩᚠᛡᛒᛒᚩᚠ•ᛒᚹ•ᛚᛈᚫᚱᛚᛉ•ᚻᚣᛏ•ᚦᚩᚫ␍"
./cipherval -alphabet="runeglish" -wordfile="./runeglish.txt" -ciphertype="autokey" -text="N RGHEOBXAER␍EOHEAGTOENR UNG GBEOOEFD AEL IEAIINGE RAEN OE UOEE SJTUY BYPOLAP LPO METX HOEDTHGSNLYT EYEOPAECINGD THTY XNLOEEO REEAJHEOCEA IOAEBM JINGR XWINGF REAYWH WUEOW UGAE RGJNI G MJY ACTXTH DEAYEP INGIOE XFHL TU WDIOAEAU PJTHTING INGNIO AINGEOCRTHB JEOWIOJ RLWB OCMIOEAMHJ XH GJEA FOXOE LINGSHMO HOOEEIOW DEW THF DPNLAERXYRO RC INGEUBXOPMINGJG IRAEOE FTH XR FIOINGHBI SEONTHLT OEM THPSXAERTLEADGCIO RFHEOEAS THDIOL IOO POAEINGXINGF OFIOBBOF BW LPAERLX HYT THOAE␍"

./cipherval -alphabet="rune" -wordfile="./rune.txt" -ciphertype="autokey" -text="ᛁ•ᚳᚹᚾᛈᛏᚠᚪᚳ␍ᛈᚾᛡᚹᛋᛝᛁᚳ•ᚦᛁᚹ•ᚹᛏᛈᛝᚢᛟ•ᚪᛗ•ᛄᛡᛄᛚᛒ•ᚳᚪᛁ•ᚱᛒ•ᚦᛝᛒ•ᛉᛇᛋᚦᚫ•ᛏᚫᛠᚱᛗᛞᛠ•ᛗᛠᚱ•ᛖᛒᛋᚠ•ᚾᛝᛟᚩᚹᛉᛁᛗᚫᛋ•ᛒᚫᛈᛠᚪᚷᛚᛟ•ᚩᛋᚫ•ᚠᛁᛗᛝᛈ•ᚳᛒᛡᛇᚾᛈᚷᛡ•ᚣᚪᛏᛖ•ᛇᛚᚳ•ᚠᚻᛚᚢ•ᚳᛡᚫᚻᚾ•ᚻᚦᛈᚻ•ᚦᚹᚪ•ᚳᚹᛇᛁᛄ•ᚹ•ᛖᛇᚫ•ᛞᚷᛋᚠᚩ•ᛟᛡᚫᛒᛠ•ᛚᛄᛝ•ᚠᚢᚾᛗ•ᛋᚦ•ᚻᛟᚣᛞᛡᚦ•ᛠᛇᚩᛋᛚ•ᛚᛁᚣ•ᛞᛚᛒᚱᚷᚳᚩᛏ•ᛇᛈᚻᚣᛇ•ᚳᛗᚻᛏ•ᚱᚷᛖᚣᛡᛖᚾᛇ•ᚠᚾ•ᚹᛇᛡ•ᚢᚱᚠᛝ•ᛗᛚᛉᚾᛖᚱ•ᚾᚱᛝᛒᚣᚻ•ᛟᛒᚻ•ᚩᚢ•ᛟᛠᛁᛗᚪᚳᚠᚫᚳᚱ•ᚳᚷ•ᛚᛒᚦᛏᚠᚱᛠᛖᛚᛇᚹ•ᛄᚳᚪᛝ•ᚢᚩ•ᚠᚳ•ᚢᚣᛚᚾᛏᛄ•ᛉᛈᛁᚩᛗᛋ•ᛝᛖ•ᚩᛠᛉᚠᚪᚳᛋᛗᛡᛟᚹᚷᚣ•ᚳᚢᚾᛈᛡᛉ•ᚩᛟᚣᛗ•ᚣᚱ•ᛠᚱᚪᛚᚠᛚᚢ•ᚱᚢᚣᛏᛏᚱᚢ•ᛏᚻ•ᛗᛠᚪᚳᛗᚠ•ᚾᚫᛋ•ᚩᚱᚪ␍"
./cipherval -alphabet="runeglish" -wordfile="./runeglish.txt" -ciphertype="autokey" -text="I CWNPTFAC␍PNIOWSINGIC THIW WTPINGUOE AM JIOJLB CAI RB THINGB XEOSTHAE TAEEARMDEA MEAR EBSF NINGOEOWXIMAES BAEPEAAGLOE OSAE FIMINGP CBIOEONPGIO YATE EOLC FHLU CIOAEHN HTHPH THWA CWEOIJ W EEOAE DGSFO OEIOAEBEA LJING FUNM STH HOEYDIOTH EAEOOSL LIY DLBRGCOT EOPHYEO CMHT RGEYIOENEO FN WEOIO URFING MLXNER NRINGBYH OEBH OU OEEAIMACFAECR CG LBTHTFREAELEOW JCAING UO FC UYLNTJ XPIOMS INGE OEAXFACSMIOOEWGY CUNPIOX OOEYM YR EARALFLU RUYTTRU TH MEAACMF NAES ORA␍"

./cipherval -alphabet="rune" -wordfile="./rune.txt" -ciphertype="autokey" -text="ᛗ•ᚪᛟᛚᛏᛇᚠᚱᚪ␍ᛏᛚᚢᛟᛈᚹᛗᚪ•ᛡᛗᛟ•ᛟᛇᛏᚹᛠᚷ•ᚱᚾ•ᛖᚢᛖᚻᛄ•ᚪᚱᛗ•ᚫᛄ•ᛡᚹᛄ•ᛉᛒᛈᛡᚩ•ᛇᚩᛋᚫᚾᚳᛋ•ᚾᛋᚫ•ᛁᛄᛈᚠ•ᛚᚹᚷᚣᛟᛉᛗᚾᚩᛈ•ᛄᚩᛏᛋᚱᛞᚻᚷ•ᚣᛈᚩ•ᚠᛗᚾᚹᛏ•ᚪᛄᚢᛒᛚᛏᛞᚢ•ᚦᚱᛇᛁ•ᛒᚻᚪ•ᚠᛝᚻᛠ•ᚪᚢᚩᛝᛚ•ᛝᛡᛏᛝ•ᛡᛟᚱ•ᚪᛟᛒᛗᛖ•ᛟ•ᛁᛒᚩ•ᚳᛞᛈᚠᚣ•ᚷᚢᚩᛄᛋ•ᚻᛖᚹ•ᚠᛠᛚᚾ•ᛈᛡ•ᛝᚷᚦᚳᚢᛡ•ᛋᛒᚣᛈᚻ•ᚻᛗᚦ•ᚳᚻᛄᚫᛞᚪᚣᛇ•ᛒᛏᛝᚦᛒ•ᚪᚾᛝᛇ•ᚫᛞᛁᚦᚢᛁᛚᛒ•ᚠᛚ•ᛟᛒᚢ•ᛠᚫᚠᚹ•ᚾᚻᛉᛚᛁᚫ•ᛚᚫᚹᛄᚦᛝ•ᚷᛄᛝ•ᚣᛠ•ᚷᛋᛗᚾᚱᚪᚠᚩᚪᚫ•ᚪᛞ•ᚻᛄᛡᛇᚠᚫᛋᛁᚻᛒᛟ•ᛖᚪᚱᚹ•ᛠᚣ•ᚠᚪ•ᛠᚦᚻᛚᛇᛖ•ᛉᛏᛗᚣᚾᛈ•ᚹᛁ•ᚣᛋᛉᚠᚱᚪᛈᚾᚢᚷᛟᛞᚦ•ᚪᛠᛚᛏᚢᛉ•ᚣᚷᚦᚾ•ᚦᚫ•ᛋᚫᚱᚻᚠᚻᛠ•ᚫᛠᚦᛇᛇᚫᛠ•ᛇᛝ•ᚾᛋᚱᚪᚾᚠ•ᛚᚩᛈ•ᚣᚫᚱ␍"
./cipherval -alphabet="runeglish" -wordfile="./runeglish.txt" -ciphertype="autokey" -text="M AOELTEOFRA␍TLUOEPWMA IOMOE OEEOTWEAG RN EUEHJ ARM AEJ IOWJ XBPIOO EOOSAENCS NSAE IJPF LWGYOEXMNOP JOTSRDHG YPO FMNWT AJUBLTDU THREOI BHA FINGHEA AUOINGL INGIOTING IOOER AOEBME OE IBO CDPFY GUOJS HEW FEALN PIO INGGTHCUIO SBYPH HMTH CHJAEDAYEO BTINGTHB ANINGEO AEDITHUILB FL OEBU EAAEFW NHXLIAE LAEWJTHING GJING YEA GSMNRAFOAAE AD HJIOEOFAESIHBOE EARW EAY FA EATHHLEOE XTMYNP WI YSXFRAPNUGOEDTH AEALTUX YGTHN THAE SAERHFHEA AEEATHEOEOAEEA EOING NSRANF LOP YAER␍"

./cipherval -alphabet="rune" -wordfile="./rune.txt" -ciphertype="autokey" -text="ᛖ•ᛞᛝᛗᛋᛄᛠᚩᛞ␍ᛋᛗᚠᛝᛇᚷᛖᛞ•ᚣᛖᛝ•ᛝᛄᛋᚷᛡᚳ•ᚩᚻ•ᛒᚠᛒᚹᛁ•ᛞᚩᛖ•ᚪᛁ•ᚣᚷᛁ•ᛈᛏᛇᚣᚦ•ᛄᚦᛉᚪᚻᚱᛉ•ᚻᛉᚪ•ᚾᛁᛇᛠ•ᛗᚷᚳᚫᛝᛈᛖᚻᚦᛇ•ᛁᚦᛋᛉᚩᛟᚹᚳ•ᚫᛇᚦ•ᛠᛖᚻᚷᛋ•ᛞᛁᚠᛏᛗᛋᛟᚠ•ᚢᚩᛄᚾ•ᛏᚹᛞ•ᛠᛚᚹᛡ•ᛞᚠᚦᛚᛗ•ᛚᚣᛋᛚ•ᚣᛝᚩ•ᛞᛝᛏᛖᛒ•ᛝ•ᚾᛏᚦ•ᚱᛟᛇᛠᚫ•ᚳᚠᚦᛁᛉ•ᚹᛒᚷ•ᛠᛡᛗᚻ•ᛇᚣ•ᛚᚳᚢᚱᚠᚣ•ᛉᛏᚫᛇᚹ•ᚹᛖᚢ•ᚱᚹᛁᚪᛟᛞᚫᛄ•ᛏᛋᛚᚢᛏ•ᛞᚻᛚᛄ•ᚪᛟᚾᚢᚠᚾᛗᛏ•ᛠᛗ•ᛝᛏᚠ•ᛡᚪᛠᚷ•ᚻᚹᛈᛗᚾᚪ•ᛗᚪᚷᛁᚢᛚ•ᚳᛁᛚ•ᚫᛡ•ᚳᛉᛖᚻᚩᛞᛠᚦᛞᚪ•ᛞᛟ•ᚹᛁᚣᛄᛠᚪᛉᚾᚹᛏᛝ•ᛒᛞᚩᚷ•ᛡᚫ•ᛠᛞ•ᛡᚢᚹᛗᛄᛒ•ᛈᛋᛖᚫᚻᛇ•ᚷᚾ•ᚫᛉᛈᛠᚩᛞᛇᚻᚠᚳᛝᛟᚢ•ᛞᛡᛗᛋᚠᛈ•ᚫᚳᚢᚻ•ᚢᚪ•ᛉᚪᚩᚹᛠᚹᛡ•ᚪᛡᚢᛄᛄᚪᛡ•ᛄᛚ•ᚻᛉᚩᛞᚻᛠ•ᛗᚦᛇ•ᚫᚪᚩ␍"
./cipherval -alphabet="runeglish" -wordfile="./runeglish.txt" -ciphertype="autokey" -text="E DINGMSJEAOD␍SMFINGEOGED YEING INGJSGIOC OH BFBWI DOE AI YGI PTEOYTH JTHXAHRX HXA NIEOEA MGCAEINGPEHTHEO ITHSXOOEWC AEEOTH EAEHGS DIFTMSOEF UOJN TWD EALWIO DFTHLM LYSL YINGO DINGTEB ING NTTH ROEEOEAAE CFTHIX WBG EAIOMH EOY LCURFY XTAEEOW WEU RWIAOEDAEJ TSLUT DHLJ AOENUFNMT EAM INGTF IOAEAG HWPMNA MAGIUL CIL AEIO CXEHODEATHDA DOE WIYJEAAXNWTING BDOG IOAE EAD IOUWMJB PSEAEHEO GN AEXPEAODEOHFCINGOEU DIOMSFP AECUH UA XAOWEAWIO AIOUJJAIO JL HXODHEA MTHEO AEAO␍"

./cipherval -alphabet="rune" -wordfile="./rune.txt" -ciphertype="autokey" -text="ᛞ•ᛖᛚᛟᚣᚢᛈᚾᛖ␍ᚣᛟᛇᛚᚠᚷᛞᛖ•ᛋᛞᛚ•ᛚᚢᚣᚷᛉᚹ•ᚾᚱ•ᚪᛇᚪᚳᚦ•ᛖᚾᛞ•ᛒᚦ•ᛋᚷᚦ•ᛠᚫᚠᛋᛁ•ᚢᛁᛡᛒᚱᚻᛡ•ᚱᛡᛒ•ᚩᚦᚠᛈ•ᛟᚷᚹᛏᛚᛠᛞᚱᛁᚠ•ᚦᛁᚣᛡᚾᛗᚳᚹ•ᛏᚠᛁ•ᛈᛞᚱᚷᚣ•ᛖᚦᛇᚫᛟᚣᛗᛇ•ᛄᚾᚢᚩ•ᚫᚳᛖ•ᛈᛝᚳᛉ•ᛖᛇᛁᛝᛟ•ᛝᛋᚣᛝ•ᛋᛚᚾ•ᛖᛚᚫᛞᚪ•ᛚ•ᚩᚫᛁ•ᚻᛗᚠᛈᛏ•ᚹᛇᛁᚦᛡ•ᚳᚪᚷ•ᛈᛉᛟᚱ•ᚠᛋ•ᛝᚹᛄᚻᛇᛋ•ᛡᚫᛏᚠᚳ•ᚳᛞᛄ•ᚻᚳᚦᛒᛗᛖᛏᚢ•ᚫᚣᛝᛄᚫ•ᛖᚱᛝᚢ•ᛒᛗᚩᛄᛇᚩᛟᚫ•ᛈᛟ•ᛚᚫᛇ•ᛉᛒᛈᚷ•ᚱᚳᛠᛟᚩᛒ•ᛟᛒᚷᚦᛄᛝ•ᚹᚦᛝ•ᛏᛉ•ᚹᛡᛞᚱᚾᛖᛈᛁᛖᛒ•ᛖᛗ•ᚳᚦᛋᚢᛈᛒᛡᚩᚳᚫᛚ•ᚪᛖᚾᚷ•ᛉᛏ•ᛈᛖ•ᛉᛄᚳᛟᚢᚪ•ᛠᚣᛞᛏᚱᚠ•ᚷᚩ•ᛏᛡᛠᛈᚾᛖᚠᚱᛇᚹᛚᛗᛄ•ᛖᛉᛟᚣᛇᛠ•ᛏᚹᛄᚱ•ᛄᛒ•ᛡᛒᚾᚳᛈᚳᛉ•ᛒᛉᛄᚢᚢᛒᛉ•ᚢᛝ•ᚱᛡᚾᛖᚱᛈ•ᛟᛁᚠ•ᛏᛒᚾ␍"
./cipherval -alphabet="runeglish" -wordfile="./runeglish.txt" -ciphertype="autokey" -text="D ELOEYUPNE␍YOEEOLFGDE SDL LUYGXW NR AEOACTH END BTH SGTH EAAEFSI UIIOBRHIO RIOB OTHFP OEGWTLEADRIF THIYIONMCW TFI PDRGY ETHEOAEOEYMEO JNUO AECE PINGCX EEOIINGOE INGSYING SLN ELAEDA L OAEI HMFPT WEOITHIO CAG PXOER FS INGWJHEOS IOAETFC CDJ HCTHBMETU AEYINGJAE ERINGU BMOJEOOOEAE POE LAEEO XBPG RCEAOEOB OEBGTHJING WTHING TX WIODRNEPIEB EM CTHSUPBIOOCAEL AENG XT PE XJCOEUA EAYDTRF GO TIOEAPNEFREOWLMJ EXOEYEOEA TWJR JB IOBNCPCX BXJUUBX UING RIONERP OEIF TBN␍"

./cipherval -alphabet="rune" -wordfile="./rune.txt" -ciphertype="autokey" -text="ᛒ•ᛇᛉᛏᛚᛞᚹᚩᛇ␍ᛚᛏᚷᛉᛟᚠᛒᛇ•ᚾᛒᛉ•ᛉᛞᛚᚠᚻᚢ•ᚩᚣ•ᛖᚷᛖᛡᚪ•ᛇᚩᛒ•ᛄᚪ•ᚾᚠᚪ•ᛝᛗᛟᚾᚱ•ᛞᚱᛠᛄᚣᚦᛠ•ᚣᛠᛄ•ᚫᚪᛟᚹ•ᛏᚠᚢᛁᛉᛝᛒᚣᚱᛟ•ᚪᚱᛚᛠᚩᛈᛡᚢ•ᛁᛟᚱ•ᚹᛒᚣᚠᛚ•ᛇᚪᚷᛗᛏᛚᛈᚷ•ᚳᚩᛞᚫ•ᛗᛡᛇ•ᚹᛋᛡᚻ•ᛇᚷᚱᛋᛏ•ᛋᚾᛚᛋ•ᚾᛉᚩ•ᛇᛉᛗᛒᛖ•ᛉ•ᚫᛗᚱ•ᚦᛈᛟᚹᛁ•ᚢᚷᚱᚪᛠ•ᛡᛖᚠ•ᚹᚻᛏᚣ•ᛟᚾ•ᛋᚢᚳᚦᚷᚾ•ᛠᛗᛁᛟᛡ•ᛡᛒᚳ•ᚦᛡᚪᛄᛈᛇᛁᛞ•ᛗᛚᛋᚳᛗ•ᛇᚣᛋᛞ•ᛄᛈᚫᚳᚷᚫᛏᛗ•ᚹᛏ•ᛉᛗᚷ•ᚻᛄᚹᚠ•ᚣᛡᛝᛏᚫᛄ•ᛏᛄᚠᚪᚳᛋ•ᚢᚪᛋ•ᛁᚻ•ᚢᛠᛒᚣᚩᛇᚹᚱᛇᛄ•ᛇᛈ•ᛡᚪᚾᛞᚹᛄᛠᚫᛡᛗᛉ•ᛖᛇᚩᚠ•ᚻᛁ•ᚹᛇ•ᚻᚳᛡᛏᛞᛖ•ᛝᛚᛒᛁᚣᛟ•ᚠᚫ•ᛁᛠᛝᚹᚩᛇᛟᚣᚷᚢᛉᛈᚳ•ᛇᚻᛏᛚᚷᛝ•ᛁᚢᚳᚣ•ᚳᛄ•ᛠᛄᚩᛡᚹᛡᚻ•ᛄᚻᚳᛞᛞᛄᚻ•ᛞᛋ•ᚣᛠᚩᛇᚣᚹ•ᛏᚱᛟ•ᛁᛄᚩ␍"
./cipherval -alphabet="runeglish" -wordfile="./runeglish.txt" -ciphertype="autokey" -text="B EOXTLDWOEO␍LTGXOEFBEO NBX XDLFHU OY EGEIOA EOOB JA NFA INGMOENR DREAJYTHEA YEAJ AEAOEW TFUIXINGBYROE ARLEAOPIOU IOER WBYFL EOAGMTLPG CODAE MIOEO WSIOH EOGRST SNLS NXO EOXMBE X AEMR THPOEWI UGRAEA IOEF WHTY OEN SUCTHGN EAMIOEIO IOBC THIOAJPEOID MLSCM EOYSD JPAECGAETM WT XMG HJWF YIOINGTAEJ TJFACS UAS IH UEABYOEOWREOJ EOP IOANDWJEAAEIOMX EEOOF HI WEO HCIOTDE INGLBIYOE FAE IEAINGWOEOOEYGUXPC EOHTLGING IUCY CJ EAJOIOWIOH JHCDDJH DS YEAOEOYW TROE IJO␍"