#!/bin/bash

declare -a arr=("dwyl.csv" "tfcom.csv" "pgb.csv")

for i in "${arr[@]}"
do
  echo "Section 0-2"

  text="ᛋᚻᛖᚩᚷᛗᛡᚠ•ᛋᚣᛖᛝᚳ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="0-2-1.vigenere.txt"
  text="ᚦᛄᚷᚫ•ᚠᛄᛟ•ᚩᚾᚦ•ᚾᛖᚹᛒᚪᛋᛟᛇᛁᛝᚢ•ᚾᚫᚷᛁᚦ•ᚻᛒᚾᛡ•ᛈᛒᚾ•ᛇᛄᚦ•ᚪᛝᚣᛉ•ᛒᛞᛈ•ᛖᛡᚠᛉᚷᚠ•ᛋᛈᛏᚠᛈᚢᛝᚣᛝᛉᛡ•ᚣᚻ•ᛒᚢ•ᚷᚩᛈ•ᛝᚫᚦ•ᛁᚫᚻᛉᚦᛈᚷ•ᚣᚠᛝᚳᛄ•ᚦᚪᛗᛁᛝᛁᛡᚣ•ᚻᛇ•ᛏᚻᚫᛡ•ᛉᚣ•ᛖᚢᛝ•ᚳᚠᚾ•ᛇᚦᛄᛁᚦ•ᚦᛈ•ᚣᛝᛠ•ᚣᚾᛖᚣ•ᛞᛉᛝᚹ•ᛒᚳᛉᛞᛒᚠ•ᛗᛏᚾᛖ•ᛠᛄᚾᛚᚷᛒ•ᛉᚷᚦ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="0-2-2.vigenere.txt"
  text="ᚣᛁᛞᚪ•ᛝᚷᛗᛄᚱᚩᛚᛇ•ᚣᛏᛈᛁᚦᛞᛄ•ᛟᚻᛚ•ᛠ•ᚠᛉᚫᛈᚷᛉ•ᚠᛚᚹᛇᛏᚫ•ᚠᚷᚾ•ᛗᛇᛚᚾ•ᛝᛗᚠᚱᛡ•ᚪᛋ•ᛠᛗᛝᛉᛉᛇᛞᛒ•ᛟᛞᛗᚩ•ᛠᛇᚻ•ᛞᛝᚷ•ᛟᛝᛚᚢᚱᚾᛏ•ᚫᛋᚣᚢᚻᚱᛏ•ᚻᚳ•ᛋᛟᛏᛟᛝᚢᚱ•ᛋ•ᚠᚩᛖᚹᛠᛟᛚᚠᚫ•ᛗᚱᛝ•ᛞᚪᛗᚱ•ᚹᚪᛁᛗᛋᚾ•ᛋᛟᚱᚢᚹᛋᛚᛡ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="0-2-3.vigenere.txt"
  text="ᛟᚪᚫᛝᛋᛞᛈᛏ•ᚳᚱᚦᛡ•ᚱᛒᚩᛞᚦᚠ•ᚣᛉᛁᛏ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="0-2-4.vigenere.txt"
  text="ᛟᛁ•ᚠᛚᚩ•ᚠᛠ•ᚱᚩᛟᛗᚻᛗᚷᛈᚻ•ᚫᚻᚾᚩᚻᚣ•ᛟᛋᛚ•ᚾᚷ•ᚫᚣ•ᛟᚳᛒᛚᛄ•ᛝᛚᛟ•ᚫᛄᛠᚹ•ᛠᚦᚩ•ᛒᛟᚣ•ᚳᚠᚳᛄ•ᛚᚫ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="0-2-5.vigenere.txt"
  text="ᚾ•ᚦᛈ•ᚢᛉ•ᛟᛉᚷ•ᛈᚠᛋᛇᚫᛟ•ᛝᛈᛇᚩᛖᚪ•ᚷᚫᛡᛝᚦᚩ•ᛈᚪᛟᚦᚱᛝᚫ•ᚳᛋᛒᛇᚣᚻ•ᛏᛉᛖᛚᚱ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="0-2-6.vigenere.txt"
  text="ᚷᚹᚣ•ᛄᚠᛁᚾᛡᚳᚣᛠᛁᛡ•ᚩᚦ•ᛖᚳᚫᚳᛉᛡᛠ•ᚩᛚᚳ•ᚠᚱᛞᛝᛖᚢ•ᛞᚳᛚᛠᛋᛉᚳᚷᛡ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="0-2-7.vigenere.txt"
  text="ᚹᛋᚦ•ᚠᛞᛝ•ᛁᛡᛗᚪᚫᚷ•ᚹᛋ•ᚾᛞ•ᚳᛈᚦᛉᛈᛠᛠ•ᚹᚢ•ᛠᚹ•ᚠᚹᛄᚣ•ᛉᛞᚹᚳᚷᚳᛟ•ᛞᛉᛟ•ᚱᛡᚷ•ᚾᛈᚪᚣᛈ•ᚳᚣᚻ•ᚠᛖᛄᛠᚾ•ᛟᚫ•ᚢᚪ•ᚻᚱ•ᛖᛠᚦᚠᛄᚪ•ᛚᛉᛋᛏ•ᛗᚠᛚᚠᛏ•ᚷᛁᚦ•ᚢᛚᚷ•ᛉᛠᛏᛋᛚᛄᛈ•ᛚᛉᛁᛟᛗ•ᚢ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="0-2-8.vigenere.txt"
  text="ᚻᛏ•ᛒᛇᛚᛞᚻᛒᛗ•ᛠᚱᛒ•ᚾᚻᛒᛖᚷᛇ•ᛞᛚᚹᛇᛡᛈᚩ•ᚻᛖᛠ•ᚹᛁᚱᛁᚻ•ᚢᚦᚻᚣ•ᚾᛉᛒᚷᛄᛈᚢ•ᛝᛠᚠᚾᛁᛖᛞᛡᛝᚱ•ᛞᛒᛄᛡᛟᛗᛁ•ᚠᛏ•ᛄᛞᛁᚦᚱᛚᛋ•ᛖᛇᚩᚷᛒᛏᛞ•ᚦᚪᚾᚳᚣ•ᛡᛋᚦᛞ•ᛝᚠᛚᛖᚷᚻᚳ•ᛖᚩᛁᛏᚾᛉ•ᛈᛏᚠᚻᚱᛞᛖᚠᛏ•ᚫᚹᚻ•ᛒᚳ•ᚠ•ᛈᚪᛚᚢᛠᚾᛚᛄ•ᛄᚳᛚᚹᛠᛞᚢᛞᛇ•ᛠᛉᛞᚹᚻᛠ•ᚦᛡᚫᚳᛚᛏᚹᛖᛁᚳ•ᛈᛟᛞᚳ•ᚾᚻᚪ•ᚱᛁᚷᚦᛠᛖᛏᚷ•ᚦᚻᚩᛡᚹᚫᛄᛖ•ᛝᛠᛞ•ᚩᚫ•ᚪᛚ•ᛒᛄᚳᚢᛉᛏᚪᛒᛄᛈ•ᚠᛠ•ᚻᛞᚾᛡᚢᛈᛋᚢᚹ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="0-2-9.vigenere.txt"

  echo "Section 3-7"

  text="ᛚᛄ•ᛇᚻᛝᚳᚦᛏᚫᛄᛏᛉᚻ•ᛏᚢᛟ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="3-7-1.vigenere.txt"
  text="ᛋᛈᚱᚷ•ᚣᚾᚪᚷᛇᛝᚾ•ᚹᚠᚣᚾᛒᛠᛡ•ᛈᚾᚣᚪᛋᛗᛒ•ᛡᛠᛡᛁ•ᚩᛒᚱᚾᛚᛠ•ᚱᛚᛚᛖᛒᚹᚾᚻᛗᚠᛟᛒ•ᛝ•ᚱᚪᛡᚷᛟᛇᛏᛗᛉ•ᛞᛇ•ᛗᚣᚻᛠ•ᛁᛚᛋ•ᚾᚹᚳᚠᛈᛗᛈᛚ•ᛠᛋᚦᚠᛟᛡ•ᚦᛖᚣ•ᚳᛄᛚᚳᛡᛗ•ᛒᛞᚳᛇ•ᛄᛁᛏᛟ•ᛞᛠᛖᛡᚾᛏ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="3-7-2.vigenere.txt"
  text="ᛈᛞᚦ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="3-7-3.vigenere.txt"
  text="ᛇᛞᛇ•ᚫᛚᚳ•ᛡᛇ•ᛠᚻ•ᚹᛗᚣᚦᚢ•ᚻᛏᚦᚱᚻᛝ•ᛚᛝᛋ•ᚾᚫᛠᚷᛋᛚ•ᛋᛉᚩᚻᚹᛞᛗᛖᛗᚪᚠ•ᚳᚣᚳᚫᚾ•ᛏᚦᚷ•ᛁᛄᛁ•ᚳᛞᛡᛉ•ᚻᚫᚫᛠᚷ•ᛠᛝ•ᚠᛏᚩᚱᛞᚳᛇ•ᚠᚢᛉᛠᛒᚩ•ᛉᛁᚣᚷᛋᛋᛒᛠ•ᚩᛁᛈ•ᛁᛄᛁᚩᛖ•ᚻᛠᚻᛚᛡ•ᚣᛈᛉᛁᚹᛗᚳᛁ•ᛚᚷᚠᚾᛡᚳᛉ•ᛈᚩᚱᛡ•ᚻ•ᛄᛗ•ᛟᛉᛝ•ᚢᛗᛇᛠᚷᛝ•ᛝᚹᚳ•ᛚᛝᚢ•ᛉᛄᚠᛟᚢ•ᚷᛠ•ᛗᛉ•ᚪᚹ•ᛚᚢᛉᚫ•ᛗᛞᛝᚻᚱᚣ•ᚻᚪ•ᚷᛁᚠᚷᚳ•ᚫᛝᛄᛇᛉᛡ•ᚾᚦᛒᚢᛄᚱ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="3-7-4.vigenere.txt"
  text="ᚹ•ᚷᛚᛟᚷ•ᚦᛇᚠ•ᚦᛠᛁ•ᛋᚷ•ᚷᚣ•ᛠᛡᛈ•ᛡᚫᛚ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="3-7-5.vigenere.txt"
  text="ᚦᛠᛉᚫ•ᛖᛗᛖᛏᛟᛏ•ᛠᚳᚠ•ᚳᛠᚷ•ᚦ•ᛈᛁᚳᚾ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="3-7-6.vigenere.txt"
  text="ᛇᚣᛝᛄᛝᛗᚹᚳᚾ•ᛒᚣᛠ•ᚩᛟᚷᚱ•ᛗᚱᛗᛈᛡᚹ•ᚫᛟᚦᛟ•ᛈᛉᛄᛚ•ᚱᛚᚱᛒᚪᛈᛏᛉᛚᛏ•ᛗᛉᛁ'ᚹ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="3-7-7.vigenere.txt"
  text="ᛄᛋᛟᛗᚾᚱᛖᛒᛋ•ᚳᛏᛚᛟ•ᛋᛒᚠᛉᚦᚪᛠᚢ•ᛇᛉ•ᚱᚷᛏᛇᛠᛁᛄᛒᛟ•ᛉᚷᛄᛝ•ᛠᚦ•ᚱᛝᛒ•ᚾᚢᚪᛝᛒᛈᛋᛠ•ᛈᚹᚩᚻᛖ•ᚫᛇᚷᚾᚫᛋᛇ•ᚩᛈᛗ•ᛖᛉᛡᛒᚹ•ᚢᛖᛁᛞ•ᛈᚪᛇᚷᛋᚳᚷᛞᛈᚣ•ᛡᛚᚦᚱ•ᚳᚢᚠᛇᚦ•ᛉᛖᛚ•ᚢᚱᚫ•ᛉᚻᛄᚫᛗᛚᚠ•ᚳᛝᛞ•ᛁᛝᚩ•ᚳᛋᛟᛖᚣᛟᚻᚢ•ᚷᛞᚹᚪ•ᛖᛋᚷᛝᚠᛉ•ᛞᛉᛄ•ᛠᚻᛁ•ᚦᛈᛉᚣ•ᛡ•ᛇᛞᛇᛝᛇᛝ•ᛖᛠᛞᚱ•ᛚᛇᛏ•ᛉᛏᚣ•ᚱᛇ•ᛈᛝᛇᛈᚩᛁᛚᛖᚠ•ᛇᚫᚪ•ᚣᛝᚠᚣ•ᚠᛞᚾᛚ•ᛉᛏᚾᚫᛋ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="3-7-8.vigenere.txt"
  text="ᛁᚩᚳᚢ•ᚣᛠᚾᛏᚷᚳᚪ•ᛉᛡᛇ•ᚦᛄᚣᛄᛚᛟᛖᛚ•ᚣ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="3-7-9.vigenere.txt"
  text="ᛈᛡ•ᛖᚹᛟ•ᛇᚾᚪ•ᚻᛞᛇᛋ•ᚦᚣᛇᚦᛄᚦᚱᚢ•ᚳᛠᚪ•ᚢᛄᛡᛈ•ᚣᚫᛇᛋ•ᚻᛠᛏᚣᛞᚣᚫᚠᚻᚩ•ᛟᛗᛉᛟᛄᚷ•ᚢᛡᚱᛡᚳ•ᛁᚠᛟ•ᛁᛄᛈᛒ•ᛖᛝᚣᚦᚩᚫᚣ•ᛠᛉᛡᛖᛚ•ᛁᚱᚣᛞᛠᛄ•ᚫᚳ•ᛗᚷᛁᚫᚢᚪᚫ•ᛄᚪᚻᛈ•ᚠᛞᛚᛁᛠᛈᛟᚣᚩ•ᚢᛒᚷᛝᛟᚢᛝᛋᚢᚳ•ᛏᛞ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="3-7-10.vigenere.txt"
  text="ᚫᛈᚩᛄ•ᛒᚻᚱᛁᚷᚻᛄ•ᚣᚹᛗᛇᚾᚫ•ᛞᛝᛇ•ᛟᛄᛝᚳᛖᛠ•ᛉᚪᚱᚣ•ᚪᚢᛏ•ᚳᛈᚳ•ᚩᛇᛟ•ᚫᛈ•ᛏᛉᚳᛏᚻᛞᛇ•ᛉᛒᛠ•ᚫᚾᛄ•ᛠᚪᛒ•ᛖᛠᚹ•ᛡᛚ•ᚹᛁᛡᛋᛈᛚᚦᚪᛋᛄ•ᛡᛞᚣᚱᛞᛟ•ᚦᚱᛉᛟᚹ•ᚣᛞᛏ•ᚷᛚᛡᚻᚹᛗᚱ•ᛝᚠᚳ•ᚱᚫᛁᛒᚷᛈᚣ•ᛞᚪᚱᚪᛉᛟ•ᚢᚩᛁᛠ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="3-7-11.vigenere.txt"
  text="ᚪᛏᛉᛒ•ᛗ•ᚷᛡᛋᛒ•ᛉᛇ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="3-7-12.vigenere.txt"
  text="ᚷᚾᛠᚫᚷᛝᛞ•ᛉᛖᛏᚩᚷᛡ•ᛝᚻᛏ•ᚳᛁᚣ•ᛄᛏ•ᛟᚩᚻᚱᛄ•ᚳᛖᛡᚩ•ᛞᚪᛏᚣᚢᚾᚱᛇ•ᚫᚫᛁᛖᚠᛝᚦᚻ•ᛉᛁᛟᛋᛁ•ᛗᚪ•ᚢᛄᚳᛋᚹᚾᚣ•ᚩᛈᛉᚱ•ᛚᚫᛟᛏᛡ•ᛄᛈᛗ•ᛞᛋᚠᛗ•ᛟᚹ•ᛞᛚᛏ•ᚷᚱ•ᚩᚢᛋᚻᚪ•ᚣᛇᛡᛚᚢᚻ•ᛈᚹᛄᛚᚷᛒ•ᛗᚢᛄᛗ•ᛇᚾᛇ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="3-7-13.vigenere.txt"
  text="ᚫᛚᚪᛚᚷᚪ•ᛋᚻᛝ•ᛚᚦᛒ•ᛋᚳᚢᚳᚩᛡ•ᛚᚳᛄ•ᛉᚪᚾᛇᛉ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="3-7-14.vigenere.txt"
  text="ᛠᛗᛈᚢ•ᛗᚠᛚᛠᛝ•ᛒᛉᛁ•ᛚᚦᚱ•ᛠᛡᛁᚳ•ᚩᛉᛖᛞᛡ•ᛏᛋᛗᛠᛄᛈ•ᛠᛟ•ᛡᚫᚦᚹᚻᛈᛇᚪᚷᛈᚻᛠ•ᚳᛚᛠᛈ•ᛡᚣᚾᛁ•ᛚᛡᛁᚳ•ᚫᛇᚾ•ᚫᚳᛡᚱᛡᛚᛞ•ᛒᛟᛝᛡ•ᛉᛗᛝ•ᚳᚻᛟᛠᚾᛈᚳᚦ•ᛁᛇᚦ•ᛇᚢᚩ•ᚦᛈᚪ•ᛡᛚᛟᚹᛡᛈ•ᛄᛗ•ᚷᛒᛈᛋᚾᛇ•ᛏᚩᚷᚢᚾᚫᛖ•ᚾᚣᛁᛖ•ᛞᛝ•ᛞᛝ•ᛚᚢᛚᛉ•ᚪᚾᛝ•ᛇᚪᛄ•ᚻ•ᛞᚹᛈᚫᚹᚫ•ᛇᛁᛚᛝ•ᚦᚾᚳ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="3-7-15.vigenere.txt"
  text="ᛒᛁᛏ•ᛠᚳᚩᛇᛖᛝ•ᚳᚻᛟᚻᚫᛄ•ᛟᛉ•ᛁᚳᛖᛏᛋᚹᛖᚾᛡᚣᛄᛗ•ᛖᚳᚪ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="3-7-16.vigenere.txt"
  text="ᛞᚩ•ᛟᛏᚦᚫ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="3-7-17.vigenere.txt"
  text="ᚳᚹᛄ•ᛉᛠ•ᚷᛠᛗ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="3-7-18.vigenere.txt"

  echo "Section 8-14"

  text="ᛉᛁᛉᛗ•ᚢᛉᛗᚳᚦᛈᚩᛒ•ᛡᚾᛏ•ᛠᛉ•ᛈᚱᚣ•ᚩᚳᛠᛗᛝᚷᛉᛚᚢ•ᛝᛁᛏᚩ•ᛄᚠᛝ•ᛋᛚᚾᛞ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="8-14-1.vigenere.txt"
  text="ᚩᛗ•ᛇᚫ•ᚱᛞᚹᛏᛄᚦ•ᚣᚦᛋ•ᚫᚣᛖᛋᛉᛟᛒ•ᛠᚱᛇ•ᛈᛝᚢᛈ•ᚩᚦᛉ•ᚪᚻᛟᚱᛝᚢᛖᚱ•ᚣᛚᛉᛚ•ᛡᛚᚱ•ᛈᚹᛇᚾ•ᛠᚪᚱᛉᛝ•ᚣᛋᚻᚢᛚ•ᛋᚣ•ᚷᚾᚢ•ᛇᚫᚾᚾ•ᚩᚫᛖᛞ•ᚪᚩᛄᛡᚢᚪᛉ•ᚱᛉᛡᛟᛄ•ᛗᛁᛇᛚᛠᚻᚦᛗᛠᚣ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="8-14-2.vigenere.txt"
  text="ᚷᛒᚳᛈᛉᚳ•ᚾᛟᛟᛋᚷᛗᛈᛖᛏᛚᚾᛄ•ᛄᚳᛝᚩ•ᛁᚹᛚᛠᛒ•ᚠᚪᛖ•ᛏᛝ•ᚾᛈᛠᚩᛏᚦ•ᚻᛝᛉᛈᚻᛈᚳᛈᚱᚢ•ᛚᚠᛖᛟ•ᚷᚪᛒᚠᛁᚫᚠᚢᛟ•ᛗᚠᚣᛝᛄᚳ•ᚻᛏᚠᛚᚫ•ᛖᚦᛋᛚᚩᚢ•ᚫᚩᚪᛗᛟᚢᚹᛇ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="8-14-3.vigenere.txt"
  text="ᛒᚾᛋᛚᛝᛄᛟᚾ•ᛗᛚᛒ•ᛟᛏ•ᚾᛞᛒᚩᚾᚦᛡᚻᛟ•ᚱᛈᚾᚠᛈᛞ•ᛋᚩᛁᛠᚣᚾ•ᛇᚣᚹᚫᚷᛄ•ᛝᛗᚪᚹᛈ•ᚪᚢᚾ•ᛈᛡᛗᛖᛞᛟ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="8-14-4.vigenere.txt"
  text="ᛁ•ᛉᛡᛗ•ᚠᛈᚩ•ᚦᛉᛞ•ᚩᛞ•ᛋᛈᛉᛡᚷ•ᛟᚻᚠᚦᛉᛄᛟᛋᚦᚣᚦ•ᛏᚻᛋᚣ•ᚻᛠᚷᛚᚫᚱᛏ•ᚢᛋᛟ•ᚦᚠᚠᚣᛟᛡ•ᛇᚳᚣᛒᛚᛝ•ᛠᚱᚻᛞ•ᛄᚣᛏᚫ•ᚻᛞᚳᛋ•ᛉᚠᛞ•ᚦᛗ•ᚳᛇᛝ•ᚫᚾᛡᛠᚹᛁᛡ•ᛒᛗᛝ•ᚷᛈᛁᚳ•ᛠᛚᚷᛉᚣᚣᚱᛄ•ᛉᛁᛄᚢ•ᛖᚣ•ᚪᛝᛈ•ᛡᚫᚳ•ᛖᛠᚹᛒᚦᛟᚠᛗ•ᚫᚱᚠᚩᛏ•ᛝᛉᛞ•ᛗᛖᛡ•ᚩᛈᛋ•ᛇᛞ•ᛇᛟᚫᚾ•ᚷᛗᚣᛁᚫᛁᛄ•ᛈᛄᚩᛡᚷ•ᛈᚳᛄ•ᛚᛖᛡᚻᛚᚷᚱᛇ•ᛟᚣ•ᛠᚣᛗᚹᚾᚹ•ᚠᛁᛄᚢᛗᚫᚾᚳᛗᛠᛁ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="8-14-5.vigenere.txt"
  text="ᚩᛇ•ᛒᛚᛞ•ᚾᚹᚠᚾᛒᚱ•ᛋᛟᚦᛡ•ᚪᛡᛏᚷᚷᚹ•ᚪᛋᛡᚦᛋᚦᛋᚠᛗᚷᛞᛠ•ᛝᛈᚩᚪᚣᛝᛈᛋ•ᛟᚾᛇᚪᛖ•ᚻᚢᚷ•ᚩ•ᚢᚦᛏ•ᛒᚷᚣᛝᚠᚣᛁᚻ•ᚹᛡᛠᚱᚫᚹᛡᛞᚪᚦᚳ•ᛉᚢ•ᛈᛏᛋᚢᛖ•ᚷᚦᛡᛚ•ᛖᛋᛠᛝᛉᛈᛉ•ᚾᛟ•ᛞᛟᛒ•ᚾᚹᚢᛁᛇᛚᛞ•ᛁ•ᚦᚣᚷ•ᛟᛈᛡ•ᛖᚪ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="8-14-6.vigenere.txt"
  text="ᚠᛋᛉᛞ•ᛖᚷᚦᛠ•ᚾᛋ•ᛞᛟᛗᛖ•ᛗᚾᛉ•ᚹᛒᛠᛈᛟ•ᛗᛉᚫ•ᛄᚩᛞᚻᛡᚷᚠ•ᚣᛗ•ᛁᚷᛉᚻᚹ•ᚾ•ᛋᛗᚷᛠ•ᚣᛚᚱᛄᛗᛉᚣ•ᛇᚱᚢᛟ•ᚣᚦᚢᛟᚩ•ᚱᚢᚹ•ᛁᛒᚳ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="8-14-7.vigenere.txt"
  text="ᛠᛏᛞ•ᛚᛖᛋᛄ•ᚳᛟ•ᚷᛞᛡ•ᚢᚹᛝᚻᚫᚢᛈ•ᛏᛈᚩᚣ•ᚾᛇᚦᛟᛏᛇᚳᚠ•ᛒᚪᚾ•ᛗᚦᛝ•ᛟᛠᚢᛁᚪ•ᚾᚻᛝᛉᚩ•ᛇᛁᛡᚠᛟᛒᚦᚠ•ᛋᛒ•ᚠᛞᛇ•ᚩᚦᛏ•7•ᚷ•ᛚᛄᛖᚫ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="8-14-8.vigenere.txt"
  text="ᚣᛁᚫᚹᚻ•ᚫᛏ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="8-14-9.vigenere.txt"
  text="ᛁᛉ•ᛉᚻᛞᚩᛠ•ᚫᛋᛝᛚᛝ•ᛖᚩᚻᛗᚩᛟᛒᚦ•ᚱᛚᛋ•ᚳᚻ•ᚪᛡᚾᛇᚱᛉᚦ•ᚣᛉᚻ•ᛡᚾᚢ•ᛗᛉᚹ•ᛖᛈᛖ•ᚩᚳᛈᚳᛞᚪᛉᚢᛗᛝᛟ•ᛋᚾᛟᛉ•ᚠᚱᚳᛒᚢᛄᚱᚫᛝ•ᛒᛋᛟᛠᛡᚪᛚ•ᛏᛟᚾᚫᛟᚪ•ᛁ•ᛡᛋᚳᛖ•ᚹᛒ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="8-14-10.vigenere.txt"
  text="ᚾᛚᛝ•ᚦᚾᛁᛠ•ᛒᛡᚱᚠᛖᛁᚹ•ᚾᚠᛗᚢᚷᚾ•ᛄᛚᚳᚱ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="8-14-12.vigenere.txt"
  text="ᛝᚣᛉᛋᚪᛟᚱᛉᚳ•ᛒᚫ•ᚠᚢᚪᛖᚪᚹ•ᛚᚾ•ᛄᛉ•ᚻᚦᛉ•ᛗᛚᚾᛖ•ᛏᛝᚦᚪᚩᚢᛗᚣ•ᚠᛝᚪ•ᚻᛡᛇᛡ•ᛚᛏᛁ•ᛇᛁ•ᚳᚢᚢᛖ•ᚳᛒ•ᚫᛇᚠᚦᚳᛚᚩᛉᛚᚩᛚ•ᚠᚳᛠ•ᚪᚠᛟᚫᚠ•ᚾᚳ•ᚢᛒᚱ•ᚾᛇᚩᛉ•ᛁᚳᛟ•ᛞᛉᛠᛝᚠᚱᛡᚳᛇ•ᛉᛟᛈᛗᛞᚳᚦᚹᛈ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="8-14-13.vigenere.txt"
  text="ᛡᚻ•ᚾᚦᛇᛏᚹᛖᚢ•ᚫᛇᚦ•ᛝᛟᛏᚳᚷᛒᛠ•ᚪᚳᛒᚪᚩᚹᚫ•ᛉᚢ•ᚫᛖᛒ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="8-14-14.vigenere.txt"
  text="ᛇᛏᚢᚩ•ᛟᛞᚠᚢᛋ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="8-14-15.vigenere.txt"
  text="ᛡᛄᛗᚦᛠᛏᚪ•ᛒᚹᚣ•ᛏᛄᚻᚦᚫ•ᛚᚪᚱᚫᛟᚦᚩᚾᛟᛁᛖ•ᛡᚠᚷ•ᛋᚠᚦᛏ•ᛠᛡᛠᛁᚢᛡᛇᛝᛞ•ᛉᛏᚠᛒᚻᚢᛋᚳᚱᛇᚹ•ᛇᛈᛋᚢᛚᚪᛈᚢᚳᛖᚠᛞᛉ•ᚦᛠᛇᛝᚻ•ᚣᚱᛗ•ᛟᚾᛚ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="8-14-16.vigenere.txt"
  text="ᛈᚹᛞᚱᛄ•ᚪᛝᛞ•ᛁᚦᛏᚷᚢᚹᚳᚻᛖᚩᚪᛖ•ᛉᚪᚢ•ᚳᛁ•ᚱᚳᚹ•ᛠᛇᛏ•ᚦᚳᚻᚢ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="8-14-17.vigenere.txt"
  text="ᛡᚹᛟ•ᚷᛇᛈ•ᚢᛈᚦ•ᚷᚣᚢᚪᛗ•ᚹᚳᛖᛝᚱᛠᛞᛏᚻ•ᛄᛁᛈᚻᚠᛉᛝᛈᚾ•ᛒᚳᚪᚷᛋᛟ•ᛉᛠᛈᚪᚩᚷᚠᚳᛡᛄ•ᛠᚢᚠᛋᛚ•ᚣᛚ•ᚢᛒ•ᛉ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="8-14-18.vigenere.txt"
  text="ᚱᚣᚾ•ᛁᛠ•ᛚᚹᛋ•ᚠᚦᚪᛠ•ᛈᚷ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="8-14-19.vigenere.txt"
  text="ᛏᚷᛡᛟᛠᛡᛒ•ᛉᛄᛒ•ᛖᚾ•ᛞᚠᛠᛗ•ᚦᚪᛗᚠᚪ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="8-14-20.vigenere.txt"
  text="ᚻᛡ•ᛗᛁᛏᛟ•ᚻᚣᚹᛏ•ᚠᛒᛁ•ᚫᛖ•ᛝᛒ•ᛚᛏᛠᛉ•ᛟᛋᚾᛉ•ᚹᛏᛠᛏ•ᛖᚢᛡᛖ•ᛉᚾᛇ•ᛟᚳᚾᚠᚩᚾᚠ•ᚳᚪ•ᚷᚱᚩ•ᛠᚦᚹᚣ•ᛒᛁ•ᛝᛇᛟ•ᚣ•ᚷᛗᚩ•ᛁᚷᛄ•ᚩᛇ•ᚢᛁᛉᛝᚪᚱᛉ•ᛏᛄᛞᛈ•ᚾᛝᚷᛏᚢ•ᛚᚷᚳᛏ•ᚢᛒᛇ•ᛈᚩᚣᚢᛏ•ᛡᚫᛏᚹᛏᛇ•ᛡᚫᚫ•ᚦᛏᛝ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="8-14-21.vigenere.txt"
  text="ᛠᚳᛁᛉᚻᚦᚣ•ᚻᛚᚾᛋᚱᛡᚫᛚᚫ•ᛖᚷᚻ•ᛞᚾᚻᛠ•ᚠᚪᚹᛖᚠᛄ•ᛒᛇᚱᚹᛏᛉᚾᛠᛖᛁ•ᚠᚾᛡᚳ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="8-14-22.vigenere.txt"
  text="ᛋᛟᚹ•ᛈᚷᛝᛟ•ᚷᚦᚠᛄᚷᚳ•ᛒᛁᛗᛚᛇᛠᚹ•ᚾᚫᚹᚷ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="8-14-23.vigenere.txt"
  text="ᚩᚻᚪᛏᚾᛄ•ᚣᛝᛏᛡᛝ•ᚢ•ᚩᚠᚣ•ᛗᚢᛒ•ᛏᚠᛈ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="8-14-24.vigenere.txt"
  text="ᚱᚩ•ᛉᚩᛝᛒ•ᛖᛏᚩᛉ•ᚣᛗᚠᛉ•ᛖᚩᚫᚷᚣᛚ•ᚩᛇ•ᚠᛋᚫᛇᛗᛡᛟᚹᚾᚩᚢᚹᛖᛁ•ᚾᚦᚫᛠᚪ•ᛠᛚ•ᚹ•ᛡᚩ•ᚢᚦᛗ•ᛝᛚᚪᚠᛝ•ᛚᚠᛚᚳᛒᚢᛝᛉ•ᚣᛡᚪᚷ•ᚹᛟᚪᚻᚹᚢ•ᛖᛠᚷ•ᛁᚪᛏᛄᛗ•ᛏᛖᛁ•ᚣᛡ•ᚦᚾᚠᚦ•ᚩᛈᚻᚪ•ᚻᛋᛠ•ᛡᛉᚪᚫ•ᚠᚣᛞᛠᛇᚠᚫ•ᛏᛗ•ᚳᛡᚷ•ᚱᚢᛞ•ᛄ•ᛋᛡᛇᚩ•ᛚᛟ•ᚦᚱᚫᛒᛚᚦ•ᛖᚪᚦᛗᛚ•ᚦᛉᚪᚱ•ᛟᛖᛒᛄᚱᛄᛖᛁᛈ•ᚪᛖᛠᚠᛄᚢ•ᛞᚹᚦᚣ•ᛉᚷᚩᚳᛡ•ᛇᛗᛞᚳᛏ•ᚻᛚᚦᛝᛖᛗᚱ•ᛒᚷᛞᛉᛗᛒᛉᚳᛝᚦᚣᛞᚫᛠ•ᛋᛏᛗᛏᚻᚹ•ᛇᚳᚪᛞ•ᛠᚢᛒᛉ•ᛡᛁᛡᛚ•ᚷᛋᚦᛞ•ᚠᚢᚩᛠ•ᛚᛋᚣᛏ•ᛋᚪᛞᚫᚹᛄᛞ•ᛋᛈᛋᛄ•ᚪᛖᛁᛇᛒᛟ•ᛏᛄ•ᚠᚩᛚᛞ•ᚾᚷᚳ•ᛚᚷᛗ•ᛠᚦᚢ•ᛟᚻᚾᛟᚣᛡ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="8-14-25.vigenere.txt"
  text="ᛇᚻᚣᚪᛈ•ᚾᛋ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="8-14-26.vigenere.txt"
  text="ᛞᚫᛠᚳᛉᛄ•ᚦᚹᛋᚱᚦᚫᚾ•ᛡᛚᚣᚫᛋᛖ•ᛟᚣᛝᛡ•ᚦᚣᚷᛇᚱ•ᛋᛠᛏ•ᛡᚳᛉ•ᛠᚷ•ᚳᛒᛋ•ᚹᚾᚻᛖᛝᛋ•ᚩᛡᛗᛉᛝ•ᛉᚦ•ᛠᛞᚳᛒᚷᛉᚹᛝᚢ•ᛉᛞᛈ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="8-14-27.vigenere.txt"
  text="ᛉᛡᛈᛟ•ᚾᛡᚠᛡᚢᛋ•ᛉᚪᛖᚻᚱᚣᛠᛇ•ᛒᛟ•ᚪᛝᛡ•ᚳᚱᚳᛈᚩᛏ•ᚻᚣᚫᛁᛋᚩᚦᛚ•ᛟᛚ•ᛋᚪᚢᚪᛈᚻ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="8-14-28.vigenere.txt"

  echo "Section 15-22"

  text="ᚠᚢᛚᛗ•ᚪᛠᚣᛟᚪ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="15-22-1.vigenere.txt"
  text="ᛚᚢᛝᚾ•ᚳᚢ•ᛒᚾᛏᚠᛝ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="15-22-2.vigenere.txt"
  text="ᛁᚢᛁᚢ•ᛟᚫᛄᚠᚫ•ᚢᚷᛉᛇᛈᛉ•ᚣᛠᛚᚪᛉ•ᛟᛉᛡᚦᚻᛠ•ᚾᚪᚳ•ᚢᚷᚾ•ᛈᛖᚾᚦᚩᚢᛁᛡᚱ•ᛏᛁᛒᛇᚳᚠᚷ•ᚩᚦᚪ•ᛁᛈᚻᛡᛒ•ᚹᛈᚻᚱᛞᛉᛏᚢ•ᚣᛒ•ᚠᛋᛉᚢ•ᛗᛁ•ᛡᚱ•ᛝᚢᚠᚦᛝ•ᛈᛟᛒ•ᚻᚷᚻᛡᛚ•ᚩᛞᚪᚳ•ᚦᛈᛞᛋᛡᚻᛇᛚ•ᚢᛏᛋᛞ•ᚦᚢᛞᛝ•ᛚᛉᛝ•ᛏᚩᛚ•ᚪᛚ•ᚣ•ᛟᛡᛉᚣ•ᛒᚻᚫᛄᛡᛁ•ᚱᚦᛚᚠ•ᛠᚾᛝ•ᛉᛗᛒᚩᛠᛈ•ᛖᛞᚪᚫᛏᚩᛠᛖᛠᛉᚳᛠᛏ•ᚩᛞᚳᛠᚾᚳᚦᛗ•ᛞ•ᚷᛁᚳᚹᛟ•ᚪᚢᛒᚳᚫ•ᚦᚱ•ᛋᚣᚪ•ᛏᚦᛒ•ᛝᚹᛋᚱᛁᛝ•ᛒᛁᚪᚫᛚ•ᛏᚱᛡᚫᚠᛞ•ᛝᛄᚩ•ᛡᛠᛉ•ᚪᛡᚻ•ᚱᛒᛁ•ᛞᛡᛄᚪᛈᚱᛋ•ᚢᛡ•ᚻᚷ•ᛚᛟᚠ•ᚻᚷᚫᛋ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="15-22-3.vigenere.txt"
  text="ᛈᚹᚷᚷ•ᛗᛟᚪᚾᚱ•ᚩᛟᛞ•ᚷᛟᚠᛠ•ᛡᚷᚳ•ᛉᛠᚠᛚ•ᛒᚫᛈ•ᚩᛄᛈ•ᛄᛗᛠ•ᚾ•ᛉᚪ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="15-22-4.vigenere.txt"
  text="ᛡᛖᛋᚷᚫᚦ•ᛄᚷᛉᚩᚦᛄᚳᚣ•ᚢᛄᚦᛄᚪᚾᛏᛒ•ᚳᛈᛡᛄᛋᚫ•ᛋᛗ•ᚻᛞᛠᛉᚢᛗ•ᛏᛠᛖᚣᚠ•ᛄᛏᛋᛗᛞᛟᛁᛝᚪᛉᛖᛈ•ᛚᛇᛞᚦ•ᚪᛋᛉ•ᚳᛒᚢᛟᚳᛒᛚᚾᛟᛝᛉᚩ•ᛖᚳ•ᛝᛟᚳᛁᛒᛈᚫ•ᚣᛖᛄᛝ•ᛞᚢᚱ•ᛉᛟᚩ•ᚠᚹᚩ•ᚣᛁᚠᚢᛇ•ᛚᛏᛈᛒᛗ•ᛇᛝ•ᚢᚳᚱᛡ•ᛖᚩᛁᚣᛄᛏᛡ•ᛖᚠᛇᚠᛚ•ᛁ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="15-22-5.vigenere.txt"
  text="ᚣᚷᚠᛝᛡᛈᚷᛒ•ᛡᚩᚷᛡ•ᛟᚾᚹᛡᛈᛟ•ᚦᛈ•ᛟᚷᛚᚦ•ᛈᛞ•ᚦᛇᛒ•ᛡᚪᛒᚪ•ᚾᛗ•ᚳᚾᛖᛡᚹᛝᛏᚱ•ᛝᚫᛚᛟᛁᛇᚣ•ᛝᛡᚾᛏ•ᚱᛁ•ᛋᚪᛖ•ᛇᚢ•ᛝᛞᛄ•ᚠᚱᛠᛗᛠᚪ•ᚫᛈ•ᛏᚠ•ᛖᛏᚷᚾᚠᛁᚠ•ᚱᚻᚱᛇᛒ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="15-22-6.vigenere.txt"
  text="ᚻᛈᛏ•ᛇᚱᛝᛡᛒᚹᛚᛏ•ᛗᛉᚦ•ᚾᛄᚳᚫ•ᚷᛈ•ᛋᛖᚩ•ᚢᛝᚩ•ᛏᛈᛁᚣᚾᚪ•ᛏᚹ•ᚠᛗᚾᛟᚾᚳᛒ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="15-22-7.vigenere.txt"
  text="ᛄᛉᛡ•ᛟᚪᛁᚫᛝ•ᛒ•ᛉᛏᛄᛁᛋ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="15-22-8.vigenere.txt"
  text="ᛠ•ᚳᛖᚱᚦᚣᚩᚣ•ᛈᚫᚷ•ᛡᛄᛁᚩ•ᚱᚦᛠ•ᛇᚦᚩᛉ•ᚾᚱᚾᚫᛁᛉ•ᛁ•ᛝᚣᚫᛡᚫᛗ•ᚹᛖ•ᛇᚷᚻᛖᛗ•ᚷᚢᛞᚹ•ᛄᚻ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="15-22-9.vigenere.txt"
  text="ᛉᚱᚢᛄᚢᚾᛈ•ᛋᚣᛄᚫ•ᛈᚳᚣᚳᛒᛡ•ᚫᛟᚪᚠ•ᛏ•ᚷᚩᛇᛟ•ᛁᚱᛗ•ᛖᛉᛟ•ᛗᛇᚫᛟᚦ•ᚱ•ᛞᛁᚢᚦᚻᛗᛡᚾ•ᛁᚦᚻᛚ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="15-22-10.vigenere.txt"
  text="ᛏᚳ•ᚪᚦ•ᚠᚪᚫᚣᚻᛠ•ᚦᚠᛋᚠᛝᚷᚱᛈ•ᛏᛄᛉᛟ•ᚷᛚᚻ•ᚩᚪᚦᛏᚳᛁ•ᚠᚣᚢᛁᚹ•ᛟᚪᚣᛁᛠᛄᚪ•ᛟᛝᚦ•ᛟᚠᚦᚾ•ᛇᚷ•ᛠᛚᛒᚠ•ᛠᚪᛄᛇᛠᛚ•ᚱᚷᛋ•ᚹᚩᛒᛁ•ᛠᚳ•ᛁᛞᛄ•ᛖᛗᚱ•ᚷᚪᚻᛠᛚᚷᚩ•ᛉᚻ•ᛡᛝ•ᛞᚱᚹᚩᛈᛡ•ᚣᚳᚦ•ᛁᛇᚢᛁ•ᛟᚦᚠᚳᚻ•ᚩᛁ•ᛝᚾᛁᛞ•ᛏ•ᚫᚱᛝᚫᛈ•ᛠᛞᛇᛉᚳᛠᚩᛟᛖ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="15-22-11.vigenere.txt"
  text="ᛗᛈᛒᚦᛝᛋᚢᛡ•ᚻᛡᛏ•ᛉᛇᚷᚠᛡᛡᛟᚢ•ᛡᚦᚣᛞᚪᚫᛝᛒ•ᚳᚩᚷ•ᛏᛞᚦᛁ•ᚠᛒᛖ•ᚦᛟᚳ•ᚠᚻ•ᛞᚠᚣᛋᚾᛟ•ᛠᛇᛄ•ᛖᛉ•ᚩᛈᛠᛚᚪ•ᛟᚩᚾ•ᛄᛉᛋ•ᚣᚫᚷᛖᚩᛟᚢᚱᚹᚢ•ᛟᛡᛄᛇᚢᛞᛉ•ᛒᛇᚳ•ᛝᛚᛗᛠᛗ•ᚪᚱᛡᛗᛒᚩᚹ•ᛋᛖᚾᚻᚣ•ᛈ•ᛞᛚᛞ•ᛈᛏ•ᚪᛞᛚᛉ•ᛟᚱᚾᚹ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="15-22-12.vigenere.txt"
  text="ᛠᚠᛁ•ᛟᚾᛒ•ᛇᛟᛖᛝᚳᚠᛏᛞᛏ•ᛇᚫ•ᛝᚢ•ᛠᛡᚫᛖᛟᛞᛝᛠ•ᚠᛗᛒᛚ•ᛏᚢ•ᛈᚱᚹᛟᛇᛉ•ᚳᛟᛈᛏ•ᚢᚠᚳᛞ•ᛄᛋᛞᛈᛚ•ᚠᛝᚱᛄᚣ•ᛞᛗᛖᚣ•ᚢᛖᛝᛠᚳᛞᛈᚩᛠ•ᛏᛒᚳ•ᚷᚾᚩᛟᚾᚠ•ᚩᛁᚠᚢᛋᚾ•ᛞᚹᛠᛇᛈ•ᚱᚩᚩᛄ•ᚪᛟ•ᛇᛠᛄᛁ•ᛟᛄᛞᚢᚳᛝᚩ•ᚱᛝᛋ•ᛄᛁᛈᛉᛖ•ᛞᛁᚾᛗᛗᚳ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="15-22-13.vigenere.txt"
  text="ᛉᚩᛁᛄᛞᚳ•ᚢᚪᛇ•ᚦᛡᛇᚻᛠᚣ•ᛠᚻ•ᚠᚩ•ᛡᛠᛋᛟᚪ•ᚹ•ᚫᚻᚩᛄᚢᚱᚩᚣ•ᛏᚫᚪᛡᚷ•ᛄᛚᛄ•ᛝᛏᛖᛒᛚᛉᚻ•ᚱᚩᚫᛇᛈᛄᛠ•ᚳᛈᛚᚣᛈ•ᚪᛠᚻᚻᛋᚫ•ᚩᛝᚹ•ᛋᛞᚠᚳᛠ•ᚩᛇᚫᚪᚩᚹᛗᚪ•ᚣᚫᚷᚫᛄᚱᚹᛞ•ᚱ•ᚦᚷᚳᚹ•ᚾᚷᛡ•ᛚᛒᚳ•ᛄᚷᚹᚹ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="15-22-14.vigenere.txt"
  text="ᚱᛁᚠᛏ•ᚠᛚ•ᛋᛄᛚᚪᛄᚱᛏ•ᛞᚷᚫᛠᚠᛉᛞ•ᚫᚷᚻᛏ•ᛗᚣᛈ•ᛏᛒᛟᛝ•ᛄᛋᚾ•ᛝᛁᚹ•ᚦ•ᛠᛝᛞᚾᛟᚷᚫ•ᛁᛗ•ᛝᛉᚱᛞᛋᛗ•ᚠᚫᚹ•ᛟᛋ•ᚦᛞᛞᛈᛝᛞᛡᚷᛒ•ᚪᛟ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="15-22-15.vigenere.txt"
  text="ᚦᛡᛒ•ᚪᚹ•ᚾᛉᚫ•ᛚᛈᛁ•ᛒ•ᚠᚾᚠ•ᛡᚩᛏᛞᚾᛋᛖᚳᚻ•ᛖᚻ•ᚢᛟ•ᚪᛖᛗᛝ•ᛠᚫ•ᛈᚩᚪᛞ•ᚠᚫᚻ•ᚠᛏᚦᛄᛚᛄᛒ•ᛗᛇᛈ•ᛄᚢᛒ•ᚷᛁᛇ•ᛈᛉᚣ•ᛈᛟᚦᛞᚱᛠᚪᛡ•ᛝᛡᛒᛚᚻᚦᚫᛉ•ᛟᚫ•ᚪᛇ•ᛉᚳ•ᛠᚠᚫ•ᚢᚣᚦᛋ•ᚠᛝᚠᚱᚹ•ᛟᛒᛗᚷᛞᚾᛡ•ᛞᚪ•ᚻᚣᛇ•ᚱᛚ•ᛖᚣᛇᚻᛠᚩ•ᚢᚳᚱᚻ•ᛡᛟᛗᛠᛝᛄᚦ•ᛄᚢᛁᛇ•ᛄᛁ•ᛖᚷᛁ•ᚪᛇᛏ•ᛝᛡᚳᛚ•ᛇᚠᛗᚪ•ᚷᛚᛒᛋ•ᛉᛞᚫᛟᛋᛚ•ᚹᛏᛠᛗ•ᛚᚦᛗ•ᛝᚦ•ᚣᛈᚠ•ᚪᛞᛚᚪᛖᛚᚩ•ᚱᚷ•ᛚᚳᛇᛏᚷᚣᛟᛗ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="15-22-16.vigenere.txt"
  text="ᚪᛁ•ᚷᛄᛒᛡᛗ•ᛞᛈᚪᚳᛠᚷᛋ•ᛏᛈ•ᚩᛋᛏᛗᚱᚣᛋᛉ•ᛁᛄᛚᛝᛚᛁ•ᛉᚢᛠᛗᛇᚢᛋᚻ•ᚳᛉᛄᚩ•ᚠᛄᚠ•ᛁᚣᛁᛟ•ᛏᚷᚱᚦ•ᛡᛒᛋᚳ•ᛇᚢᚷ•ᛚᚱ•ᛁᛗᚱ•ᛗᛝᚻᛈᚫ•ᛝᛋᚫ•ᛖᛈᛁ•ᛒᛇᚹᚫᚢᛄᚳᛒ•ᚦᛋᚹᚦᚫ•ᛡᛟᚷᛚ•ᛞᛚᚢᛟᛡ•ᚱᛞᚱᛒᛄᚳᚢᛠ•ᚩᛉᛉ•ᛝᛡᛄ•ᛁᚫᛟ•ᛖᛗᚹ•ᛖᛉᚦᛗᚪᛋᛉ•ᛞᚦ•ᛡᚢ•ᛉᛗᚫᛋᚳᛖ•ᚳᚫᛠ•ᛞᚳᚷ•ᚩᛁᛇ•ᚾᛟᚷᚣᚳᚦᚳᚦ•ᛗᚣ•ᛈᚪᛒᛈ•ᚻᚢᚻᚾᛏᚫᛒᛇᚩᛁᛈ•ᚫᚩ\'ᚣ•ᛡᚣᛗᚷ•ᚠᚱᛡᛚᛏ•ᛖᛟᚩᛈᛚᚩᚷᛁᛟᛠ•ᛞᛖᚳᛗᛁᚣ•ᛈᛚ•ᛁᚹᛋᛄᚹ•ᛟᛡᚪ•ᚦᛖᚩᛄᚷᛋᛝᚣᛗᛟᚻ•ᛗᚠᚦᛉᚦᚫᛋᛈᚣᚩᚠ•ᛈᛟᛋᛖᚫᛇᛗᛚᛈᚾ•ᛡᚠᚳᚾᚩᛄᛋᛡ•ᚫᛄᚦᚪᛠ•ᛈᚻᛋᛟ•ᛗᚹ•ᚱᚣᛁᚢ•ᛉᚹᛋᚱ•ᛞᛈᚦᛈᚩ•ᛞᛄᚩ•ᚢᛈᛖᚪᚫᛉᚫ•ᛏᚱᛟᛏᛒ•ᛠ•ᚫᚳᚾ•ᛖᛝᚦᛄᛄᚠᛚᚾᚩᛒ•ᛉᚷ•ᚪᚩᛚ•ᚪᚢ•ᛞᚻᚳᚹᛚᛡᛞᛇ•ᛟᚩᛡᛚᚳ•ᛡᚳᛉ•ᛝᛠᛝᚷᛝᛞᛄᛏ•ᛠᛈ•ᚹᛈᛗ•ᛈᚱ•ᚫᛏᛖᚢᛝᚫᛡ•ᚾᛁᛠᚻᚦᚣᛠ•ᚫ•ᚩᛉᛋᚩ•ᛄᚠᛏᚷ•ᚹᛁᚪᛁᚩᛁ•ᛝᛠ•ᚾ•ᚷᛗᚹᚦᛖ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="15-22-17.vigenere.txt"
  text="ᚷᛟᚪᚹᛞᚻᚢ•ᛡᚹ•ᚣᚷᛉᛒᚪᚾᛝᛡᛄᛡ•ᚠᚷᛈᚦᚠᚦ•ᛁᛈᚪᛝᛋᛞᛟᚩᛝᛗ•ᛁᚷ•ᛄᚷ•ᚳᚩᚦᛖᚦᛄ•ᚣᚠ•ᚦᚳᛄᛡᛖᚢ•ᛉᛄᚳᚻᛄᚱᛄ•ᚪᚻᚾᚦ•ᛚᚷ•ᚱᚦ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="15-22-18.vigenere.txt"
  text="ᛒᚪᚩᛖᚢᛡᛄᚹᛏᚱᚹᛟ•ᚦᚳᛗᚦᚠᚫᚻ•ᛡᚠᛠᚣᚪᚦᛚᛏᛒᚢᛝ•ᛖᛋᛗᚱ•ᚪᚹᛒ•ᚹᛒᛗᚱᚾᛗᚻᛗᛁᚾᚪᛞ•\"ᛡᛖᚩ•ᚾᚹᛡ•ᚢᛄᚦᛠ•ᛚᚳᚷᛚᛇ•ᛟᛠᛠᚪ\""
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="15-22-19.vigenere.txt"
  text="ᛇᛉᚣᚪ•ᚷᛏᚩ•ᛖᚹᛒᛈᚷᛝᛒ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="15-22-20.vigenere.txt"
  text="ᛡᚦᚠᛋᚾ•ᛒᚦᚠ•ᛇᛝᛠ•ᚠᚾᛉ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="15-22-21.vigenere.txt"

  echo "Section 23-26"

  text="ᚢᚪ•ᚹᛝᚷᛉᛞᚷ•ᛁᛒᛁ•ᛇᛏᛒᛁᚣ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="23-26-1.vigenere.txt"
  text="ᛠᚷᛋᚫᛈᚹᛗᛠ•ᛇᛄᛇ•ᚹᚻᛁ•ᚷᛠᛒᚢᚣᚻᚣ•ᛝᚹᚢᚱᛋ•ᚩᛡᚠᛡᛠ•ᛞᛟᚦᛗᚳᚾᛉ•ᛞᚦᛖᚱᛇᚳ•ᚪᛄᛋᛟ•ᚢᚹᚱᛏ•ᛋᛖᛋᛏ•ᚣᚱᛠᚫᚾᛞ•ᛈᛒᛡᛋᚢᛞᛖᚣᚦ•ᛚᚹᛟᛋ•ᚷᛚᛄ•ᚫᛖᚩᚳᚦᚹᛗ•ᚢᚩᚷ•ᚠᚪᚩᛡᛝᛒᛠᚦᚳᚪ•ᚱᛡᛏ•ᛟᚹᚠᚣᛝᚢᚣᛁ•ᛚᛏᚫᚫ•ᚪ•ᚱᛈᚠᛗᚹᚩᛞ•ᛠᛒᛈ•ᛝᛟ•ᚾᚷᛗ•ᛡᛖᚩ•ᚾᛚᛉᛝ•ᛁᛡᚫᛗ•ᚻᛖᚹᛗ•ᛝᛈᛇᛗᛡᛄ•ᚫᚩᛡ•ᚠᚣᛉᛟᚫᚦ•ᚫᛒᚩ•ᚪᚦᛄᚱᛄᚾᚦ•ᛡᚠᚪᛏᚾᚻ•ᚷᚢ•ᛞ•ᚳᚦᚢᚱᚢᛟ•ᛞᚻᚱ•ᚷᚹᛏᛈᛖᚠ•ᚪᚻᛠᚦᛞᚱᚠ•ᛖᛄᚫ•ᚾᚳᚻᚹ•ᛇᛡᛈᛠᚹ•ᛗᛚ•ᚹᛟᚹᛠ•ᚪᚾᚪ•ᚳᚪ•ᚷᛚᚦᛒᚩᚹᚢ•ᚷᛚᚠᛋᚻ•ᚾᛉᛝᛗ•ᛖᚦᚢᛝᛡ•ᛈᚣᚢ•ᛉᚷᚷ•ᚹᛞᛁᛋ•ᚦᛡᛡᛈᚳᚪᚩ•ᚢᛗᚢᛉᚩᚣᚻᛏ•ᚩᚫᛗᚢ•ᚩᚾᛏᛠᛒᛟᛒᚠᛁᛈ•ᛚᛋᛝᚫᚳ•ᚫᛟᛏ•ᚢᚩᛉᚾᛡᛋᚠᛖ•ᛉᚱ•ᛗᚩᚩᚫ•ᚠᚢᚦᛖᛞᚾᚣ•ᛡᛋ•ᛋᚱᛚᛟ•ᚢᚻ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="23-26-2.vigenere.txt"
  text="ᚢᚾᛈ•ᛁᚻ•ᛖᛉ•ᚦᛞᛗ•ᛈᛟᚠ•ᛈᚠᛝᚫᛝᛋ•ᛟᛄᚹ•ᛠᛒᚣ•ᛟᚹᛞ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="23-26-3.vigenere.txt"
  text="ᚠᚣᛄᛁᛏᛉᛚ•ᚩᚦᛝ•ᚠᚪᛋᛡᛁᚻᛒᚱ•ᚪᚢᚣ•ᚫᚢ•ᛟᛠᚪᚣ•ᛖᛟᚫ•ᛖᛈᚠᛒ•ᛈᛄᛁ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="23-26-4.vigenere.txt"
  text="ᛋᛝᛒ•ᚱᚦᚳᛇ•ᛚᛁᚢᛈᛏᚳᛒᛉ•ᛖᚪᚣᚠᛗᚳᚣᚱ•ᚻᚹᛏᚾᛡᛉᚫᚦᛟ•ᚳᚹ•ᛠᚠ•ᛏᛠ•ᛝᚩᚻ•ᛡᛠᛒᛋᚻᛟ•ᚫᛁ•ᛠᛏᛁᛋ•ᛏᚫᚻᚱ•ᚻᛄᛋᛡᚹᚾᚾᛡᚹᛚ•ᚢᛖ•ᛏ•ᚱᛝᚳᚣ•ᚪᛉᛇᛝᛋᛖᛇᛁᚻᚾ•ᚷ•ᚹᛉᚳᛉᚣ•ᛋᛈᚳᛟᚱ•ᛒᚣᛄᛝᛖᛁ•ᚾᚷᚪ•ᚣᚷ•ᛚᛒ•ᚢᛄᚩ•ᛝᛉᛉᚪᛖ•ᛒᚦᛉᛡᚱ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="23-26-5.vigenere.txt"
  text="ᛏᚷᚹᛄᛋᛁᚠ•ᛠᛁᛡᚦᛝᚾᛖᚾᚠᚩᛗᛖᚣᚪ•ᚳᛖᚳᚹᚪᚫᚹ•ᛇᚢᚦᚻᛉᚢᚾ•ᛠᛚᚢᚾᚦᛈᛋᚢᛈᚱ•ᛞᚫᛟᚱᛡᚫᚪᚢ•ᚢᛗᛚᚦᛠ•ᛚᛝᛈᚣ•ᚩᛋᛟᚪᚱᛗᚦᛟᛈ•ᛚᛋ•ᛏᛁᚠᛋᛖᚹᛝ•ᛗᛞᚩ•ᛠᚫᛡᛒᛏᚩᛋ•ᛖᛏᚪᚠ•ᚫᛒ•ᛚᚾ•ᛋᚪᛉᛟ•ᚾᛚᚹᛖ•ᚩᛚᛁᛄᛏ•ᛒᚪᚠᛉᛏ•ᚩᛟᛄ•ᚾᚷᛋ•ᚷᛚᚷᛠ•ᛒᚷᛖᚩᚪᚩᛖᛞ•ᚷᛇᛗ•ᚳᚱᚷ•ᛈᛞᚩᚠᚹᛇ•ᛠᛞᚣᛝ•ᚾᛁᚠᛈᛚ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="23-26-6.vigenere.txt"
  text="ᛖᛟ•ᚢᚳᛗ•ᛚᚫᛏᛉᛄᚱᛉ•ᛁᛠᚷᛚ•ᚷᚳᛋᚩᛝ•ᚫᚦ•ᛗᚻᛟᚠ•ᚱᛋᚳᚦ•ᚣᚩ•ᛒᛁᚫᚻᛖᚢᛏᛚᛚ•ᛇᚷᛟᚣ•ᛒᚾᚦᚻ•ᛠᛖᛄᛒᚾᛁᛚᛠᚱ•ᛄᚠᚳᛋᛝᚳᛈ•ᚷᚻᛋᛗ•ᛇᛞᛇ•ᚣ•ᛡᛖᛏᛠᚢᛡ•ᚩᚾᛠᚩ•ᛄᚣᛇᛉᛠᚪᛡ•ᚾᛞᛝᚻ•ᛈᛠᚻᛡᚢ•ᛝᚻᚦᛈ•ᛉᚢ•ᛠᚣᛈᛟᚦᛋᚣᛈ•ᚠᛏ•ᛒᛁᛟᚪᚷᛚ•ᛠᚻ•ᛝᛁᛡᛚᛝᚾᛞᚪᛈᚷ•ᚾᛏᚦᛋᛒ•ᛋᛋᛠ•ᚷᚳ•ᛠᛗᚢ•ᛖᛉᛒᚷᚫᚠᚩᛁᛉ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="23-26-7.vigenere.txt"
  text="ᚠᚪ•ᛠᚱᛇ•ᚩᛁᛞᛋᛚᚦᛖᛒᛇ•ᛟᚷᚣᚷᚾᚷ•ᚦᚠᚳᛗ•ᚩᛖᛖ•ᚩᚠᛒᚻᛝ•ᚳᛁᛄᚪᚾᚩᚪ•ᛈᚻᚱᛗ•ᚱᛗᛟ•ᚦᚷᛄ•ᛒᚱᚦᚪᛠ•ᛉᛖᛡᛞᚦ•ᚱᛝᛄᛒ•ᚾᛏᚣ•ᛏᛋᛒᚾᚫ•ᚢᛖᛁᚩᛡ•ᛄᛇᚢᚦᛚᚳᛖ•ᛚᛁ•ᛒᚢᚠᚪᚱᛠ•ᛗᛒ•ᛞᛉᛗ•ᚢᛠᛏᚣ•ᚪᛄᛈᚢᛈᛠᚣᚷ•ᛗᛡᛗᚢᚪᛗᛝ•ᚣᛡ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="23-26-8.vigenere.txt"
  text="ᚪᛖᛏ•ᛖᛋᚪᛟ•ᚳᚻᛁᛋᚠᛁᚾ•ᛈᛟᛝ•ᛇᚦᚣᛏᚫᛉ•ᛖᛟᛏ•ᛞᛡᛚᛖᛈᛏᚪ•ᛏᚠᚱᚾ•ᚪᛠᚱ•ᛠᚳ•ᚾᚻᚹᛒᛇᛋ•ᛁᚻᚣᛋᚹᚩᛉᚹ•ᚩᛝᚢ•ᚻᛝᛟ•ᛏᛚᚠ•ᛄᚷᛏᛝᛄᛝ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="23-26-9.vigenere.txt"

  echo "Section 27-32"

  text="ᛗᛈᚣ•ᛚᛋᚩᚪᚫᚻᛚᛖᛇᛁᛗᛚ•ᛚᛋᚳᛈ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="27-32-1.vigenere.txt"
  text="ᚾᚻᚷᚢᛡᚻᚢ•ᛒᚠ•ᛞᛄᚢ•ᛒᛖᛁ•ᚫᚠ•ᛈ•ᚫᛈᚦ•ᚱᛗᛚᚳ•ᛒᚷᚣᛗᛠᛒᚫ•ᚾᚦ•ᛗᚠᛡᛠᚳᛒᚷᚫᚠ•ᛖᛄᚱᚩ•ᛈᛒ•ᚠᛒᚩ•ᛇᚱᛠᚱ•ᛠᚷᛖᛚ•ᛇᚱᚾᛋᚩᚩᚳᚪᛖᚣᛖᛖ•ᛏᚱ•ᚢᚣ•ᛟᛄᛉ•ᛠᚷᛝ•ᚣᛏᛝᚾ•ᚪᛏᛋ•ᛝᚪᛄ•ᚠᛚᛋᚢ•ᚹᛠᛈᛁᛏ•ᛁᚾ•ᚱᚱᛝᛗ•ᚣᛗᚠᛁᚫᛁᚪ•ᚢᛟᛒᚹ•ᛗᛁᚻᚣᚹᛞᛚ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="27-32-2.vigenere.txt"
  text="ᛟᛏᛞ•ᛟᚳᛒ•ᛡᛒ•ᚪᛏ•ᚹᛏᛈ•ᚹᛠᚩᚱᚩᛖ•ᚣᛚᛋ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="27-32-3.vigenere.txt"
  text="ᚢᛡᚱᚠᛄᛇᚱᛡᚦᛖᚢᛏ•ᛝᚫ•ᚾᚪᛠᚩᚪᚾᚪᚦᚷᚩ•ᚫᛉᛒᛏᛖᛠᛗᚷᚱᛗ•ᚣᛝᚠᛒ•ᛞᛟᛞᚪ•ᛠᚱᚳᛁᛈᛞᚠᛗᛝᚻ•ᛋᚩ•ᛞᛈᛉᚾ•ᛟᚱᛡᚾᚳᚳᛏ•ᚾᛈᚠᛈᚳ•ᛄᚦᛒᛁᚹ•ᛞᚹᛝᛠᛡᚹᛚ•ᚹᛄᚾᚪᛟ•ᛏᛞᛉᚣᛖᚱᛞ•ᚱᛏᛇᛁᚳᛈ•ᛝ•ᚦᛟᚷᛄᚦ•ᚣᛋ•ᛠᚻ•ᚠᛒᛚ•ᛁᚫᛚᛞᛉᚪ•ᛁᚹᚷ•ᛒᚩᚹᚾᛠ•ᛋᛖᛗᛒᛋ•ᚳᚹᚦᛟᚠᚻᚫ•ᛞᚢᛁᛒᛞ•ᛇᛝᛈᚠᛁ•ᛟᚢᚣᛏ•ᚻᚱᛖᚾᚳᛈᛡᛈᛞᛄ•ᛁᛏᛗᛋᚫᛉᚩᚣ•ᚪᛄᛗᛡᛖ•ᛇᛄᚠᛗᚱ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="27-32-3.vigenere.txt"
  text="ᛞᛟᚪᛒᛞᚻ•ᚾᛈᚪ•ᛇᚱᚻᚾᛝᛠᚠᚾᚠ•ᚩᛗᛋᚾ•ᛠᚪᛁᚢᛚ•ᚪᚫ•ᛄᛉᛡᚠ•ᛁᛖᛈᛠᚻ•ᚠᛇᚩᚹ•ᛠᛄᛇᛁᛠᚫ•ᛄᛒ•ᛋ•ᚠᛖᚷ•ᛋᛁ•ᛟᛗᛒᛁᛝᛏᚪᚢᛁᚦ•ᚩᛝᛗᚠ•ᚹᛟᛒᛟᛡ•ᚠᚣᛝᚩᛠ•ᚳᛚᛈᚱ•ᛞᛄᚩᛝᛄ•ᚪᛖᛗᛈᚾ•ᚠᛠᚷᛞᛒ•ᚩᛉᚷᚾᚣᚷ•ᛠᛈᛄᛞᚾᛟᚩᚢᚾᚹᛗ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="27-32-4.vigenere.txt"
  text="ᛄ•ᚢᚷᛠ•ᛗ•ᛇᚪ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="27-32-5.vigenere.txt"
  text="ᚻᚦᛡ•ᛝᛈᛞᛒ•ᚳᛉᚳ•ᛠᛉ•ᛟᚣ•ᛒᚦᛁᛄᛚᛡᛝᛡ•ᚹᛄᚫ•ᛋᛗᚪᛡᛠᛇᛝᛏ•ᚦᛞᚷ•ᚢᛏᛚᛏᚣ•ᚢᛝ•ᚷᛟᚪᛏ•ᛄᚦᚣ•ᚫᚻᚪ•ᛒᛝ•ᚦᚢᚱᚪᚾᛞ•ᛁᛝᚫ•ᛚᚫᚷ•ᚹᛁᛒᚣ•ᚾᚫᚠ•ᛚᛋᛒ•ᛈᛟᚪᛟᛞᚷᛟᚣᛉᚷᛚ•ᛋᛠᛁ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="27-32-6.vigenere.txt"
  text="ᚳᛟᛁᚦᛈᚹᛉ•ᛖᚢ•ᛟᛄᛝᛋᚢᛝ•ᚳᛡᛠ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="27-32-7.vigenere.txt"
  text="ᛚᛇ•ᛚᚷᚢᛁᛏᛒᛋ•ᛞᛁ•ᚠᚠᚷᚠ•ᚦᛄᚳ•ᚫᛟ•ᛁᛗᛡᛁᛇᚦ•ᚩ•ᚢᛈᛒ•ᚻᛋ•ᛄᚣᛄᛖ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="27-32-8.vigenere.txt"
  text="ᛒᛇᛇᚱ•ᚹᛄᛏᛡ•ᚳᚪᚫ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="27-32-9.vigenere.txt"
  text="ᚩᛈᚱ•ᛡᚾᛗᛁᛝ•ᚻᚹᚦ•ᛡᚦᚻᚦ•ᛉᚫᚫᛋᚳᛡᚾᛇ•ᛟᛉᚢ•ᚱᛄᛖ•ᛚᚾᛞ•ᛗ•ᛏᚱᛟᚦ•ᛁᛝᛡᛒ•ᚳᚩᚹᛟ•ᛏᛗᛋᚱᚷ•ᚱᛚᛞᛚ•ᚩᚣ•ᛞᚳᚪᛖᛞᚠᚳ•ᛇᛖᛉᛚᚫ•ᛖᚩᛁᛋ•ᛡᛁᛟᛋᚪᛒᛗ•ᛗᚣᚹᛄ•ᛖᚫᛝᛚ•ᛄᚱᛇ•ᛈᛚᚩᚻ•ᚪᛞ•ᛡᛄ•ᛞᚠᚹᛞᛄᚳ•ᚾᚦᛉ•ᛄᚻ•ᚷᛚ•ᚠᛖᚦ•ᛇᚻ•ᛝᛖᛒᛚᛞᛁᛗᚠ•ᚹᛒᛗᛟᛁᛖᛁᛠ•ᛈᚻᛝᛖᛞᛟᚩᚻᛄ•ᚹᚩᚾᛄᛈᛗ•ᛖᚳ•ᛖᛇ•ᚷᚻᛗᛞᚪᛈᛖ•ᛗ•ᛉᚫᛒᛇᚱ•ᛖᚣᛟᚣ•ᚱᛠᛈᚢᛠ•ᚣᛖᚪᚻ•ᚩᛉᛠᚢᚻᛡᛟ•ᚷᚫᚩᛒᛉ•ᚫᚱᛞᛋᚩᚱ•ᚷᛠ•ᛉᚻᛁ•ᚷᚳᛞᛠᛡᚳ•ᛄᛠᛉᛇᚻᛋᚹ•ᛝᛡᚷᛖᛡᚣ•ᛠᚩᚷ•ᚱᚦᚠᛟᚩᚦ•ᚦᛁᛏᚱ•ᛇᛉᛇ•ᚢᚷᛠ•ᛟᛏ•ᚩᚠᛚ•ᛟᛝᛈ•ᚱᛡᚪᚩᛏ•ᚩᛠᚷᚫᛗ•ᛈᛋᚱ•ᛖᚦᚠ•ᛞᚹᚾᛚ•ᛝᚩᛇᛄ•ᚳᛚᚢᚹᛏ•ᚩᛖᛏᚠᚪᛚ•ᛟᛇᛟ•ᛠᚱᛇ•ᚢᚪᚦᛈᛟᛡᛉ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="27-32-10.vigenere.txt"
  text="ᛡᛒᚱᛒᚠᚢᛚᚢᛟ•ᛒᛇᛒ•ᛉᚦᚹ•ᛝᚣᛖ•ᚳᚫᚣᛟ•ᚹᛁᛝᚫᛏ•ᚫᛇᛈᛡᛟᚠ•ᛚ•ᛝᚠᛡ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="27-32-11.vigenere.txt"
  text="ᛞᚪᛚᛈ•ᛋᛁ•ᚢᚣᚪᛚᛠᛝᚹ•ᚪᛏᛈᚳᚣ•ᛝᚫᚻᛗᛞᚷᛚ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="27-32-12.vigenere.txt"
  text="ᛠᛉᛒ•ᛇᛡᛋᛖ•ᚣᛁᛚ•ᚣᛠᚣ•ᚻ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="27-32-13.vigenere.txt"
  text="ᚣᛉᚾᛏᚫᛉᛋᚦᚪᚹᛗ•ᚪᚱ•ᚪᚩᚻ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="27-32-14.vigenere.txt"
  text="ᛗᛖᚫᛞᛠᛁᛗ•ᛒᛟᚾᚳᚩᚱᛉ•ᛋᚹᚫ•ᚻᛖ•ᛋᚠᚾ•ᚢᚦᛟᚷᛖᚪᛟᛇᛇ•ᚦᚳᛒᛝᛏᛉᛡᛞ•ᛋᛡ•ᚩᚠ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="27-32-15.vigenere.txt"
  text="ᛈᛖᛞᛋᛁ•ᛚᛁᚻᚾᛝᚱᚻᛈ•ᛇᚢᚫᛞ•ᛚᚻᛉᚳᛈ•ᛁᛗᛉᚳ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="27-32-16.vigenere.txt"
  text="ᛄᚫᚾᛞᛋ•ᛏᛚᛡᚩᛋᛗ•ᛚᛞᚾ•ᛈᚫᛏᚷᛈ•ᚫᚦᛄᛗ•ᛒᚻᚩᚻᛁᚷᚻᚳ•ᛚᚹᛋᚱᛇᛗᛏ•ᛄᚳᛁ•ᛠᚦᛞ•ᛏᛚ•ᚱᛖᛠᛒᚪ•ᛒᚠᛒ•ᛁᛒᛡᛇᛏᚣ•ᛏᛖᚣᚳᚱᛋᚠ•ᛁᚦᚪᛉ•ᚪᚣᚫᛠ•ᛄ•ᛈᛗ•ᚠᛋ•ᚪᛒᚱ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="27-32-17.vigenere.txt"
  text="ᛉᚣᚻ•ᚦᚩ•ᛇᛞᚢ•ᚠᛁ•ᚻᚩᚫᚠᚣᚷᚱᚪᛄ•ᛏᛉᛇ•ᛖᛠᛞ•ᛏᚠᚢᛝ•ᚫᛄᛖᛈᚳᛒᚦᚢᛝ•ᛡᛒᚹᚱ•ᛖᚾᛈᛇᚣᛇ•ᛉᚱᚹ•ᛒᛡᛞ•ᛖᚱᚩᚻᚣᛠᛈᚦ•ᛗᛁᚷᛚ•ᚹᛉᚫ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="27-32-18.vigenere.txt"
  text="ᚠᛞᚾ•ᛄᛟ•ᚻᛚᛡ•ᛗᛖᚷ•ᛟᛁᛡ•ᚻᛟᚱᛇᚹᚣᚠ•ᛈ•ᛄᚷᚦ•ᚪᛒᛝ•ᛈᛒᚪᛖ•ᚢᚹᚻᚩᛒᛋᛉ•ᚹᛞ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="27-32-19.vigenere.txt"
  text="ᚦᛇᚱᛖ•ᛄᚾᛞᛝᚹᚪ•ᚻᛖᚹ•ᛟᛡᛄᛡᛟᛝᛄᛉᛚᛄ•ᛞᛉᛟᛈ•ᚱᚪᛁᛏᚷᛉᛝᛇ•ᛠᛗᚩᛚ•ᚦᚫᚹ•ᚫᚢᛈᛡᚳ•ᚹᛝᚻᚹᛒᛗᛋᛟᛖᛁᛡ•ᛟᚹᚦᚻᛒ•ᛡᚱᛏᚦᚠ•ᚠᚩᚦ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="27-32-20.vigenere.txt"
  text="ᚻᚩᛗᛖᛉᚹᛞᛋᛚᚠᛞ•ᛝᛒᛇᛡᛚᚪ•ᚹᛞᚾᚫᛉᛏᚣᛗᚷ•ᚦᚹᛉᛡᚦ•ᚹᛒᛋᚱᛉᛡᛉᚪ•ᚢᛒᚻᛠ•ᚹᛝᚢᚻᛇᛝᛡᛠᛄ•ᛋᛈᚦᛏ•ᛟᛝᚩᛗᛒᚢᛞᛋ•ᛒᛄ•ᛠᚱᛟ•ᛖᚾ•ᚾᚹᚷᚢᛚᚪᚩᚣ•ᚢᛏᚠᛄᛏ•ᚪᚷᛒᛇ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="27-32-21.vigenere.txt"

  echo "Section 33-39"

  text="ᛞᛇ•ᛉᚳᚠᛁᚪᚹᚻᚷ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="33-39-1.vigenere.txt"
  text="ᛇᛟ•ᚠᛏᛖᛟᛠᚪᛡᛋᚷ•ᚣᛠᚾᚦᚫᚱ•ᚩᛡᛗ•ᚹᛉᛗ•ᚣᛞᛒᛏᚱ•ᚢᛄᚻ•ᚫᛟ•ᛡᛝᚹᚻᛋᚠᛡ•ᛚᚦᛏ•ᛁᚹᛏ•ᚩᚢᚾᚹᛗᛚ•ᛋᚦᛠᚹᛄ•ᚪᛄᚫᚷᚣᛗᚹᛞ•ᛈᛡ•ᛖᛄᚹ•ᛖᚢ•ᚻᚹ•ᛝᛁ•ᛋᚫᚷ•ᛄᛚ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="33-39-2.vigenere.txt"
  text="ᛝᚦᛇ•ᛁᚠᚳᛟᛇ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="33-39-3.vigenere.txt"
  text="ᛞᛒᚣᛡᚣᚢ•ᚣᚾᚦᚱᛖᛗᛁ•ᛇᛞᚱᚹ•ᛉᛒᚻ•ᚳᛄᛡᚪ•ᚾᚹ•ᚾᛗ•ᚠᛇᛁ•ᛇᚪ•ᚩᛋᛒᛟ•ᛏᛄ•ᛈ•ᛖᛈᛄᚩᚹᚢᛠᛝᚹ•ᛗᚳᚩᛏᛏᚠᚢᛄ•ᛞᛠᛉᚩ•ᛉᚦᚷᛞ•ᛒᚩᛏᛚᛇᛁᛒᛡᚪ•ᛖᚠᛠᚢᛖ•ᛈᛋᚹᛞᛞ•ᛋᛡ•ᚹᚦᛞᛋ•ᛝᛄ•ᛚᚷᚢᛡ•ᚾᛉᚠ•ᚱᚪᚣᛗᚠᚦᚻ•ᚱᚪᚱ•ᚫᚪᚷᛟᛞ•ᛒᛗᛒ•ᚾᚻ•ᛇᛞ•ᚻᛗᛚᛁ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="33-39-4.vigenere.txt"
  text="ᛠᚾᛁ•ᚫᛖᚢ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="33-39-5.vigenere.txt"
  text="ᛏᚦᛇᛋᛈᚻ•ᚻᛇᚳᛠᚫ•ᛞᛚᛋᛝ•ᛁᚹ•ᚪᚳᚩᛏᛇᛝᚷ•ᚳᚦᛋᛠᚠᚢᛝᛚᚻ•ᚹᚩᛇᚪᛈᚷ•ᛇᛗᛚᛄᛋᛏ•ᛚᚳᛈ•ᚾᛋᛝ•ᚳᚪᚳ•ᚾᛉ•ᚾᚢᛉᚫᛗᛏᛞᛏᚫ•ᛟᛗᛋᛉ•ᛏᚣᛉ•ᛇᛠᚷ•ᚻᛒᚾᚷᛇᚢᛟ•ᛄᚦᛉᚩ•ᚾᚪ•ᛞ•ᚩᛈ•ᛠᛚᛋᛏ•ᛒᚷᛁᚢᛟᛖᛁ•ᛄᚦᛖᚻᚹ•ᛄᚫᛄᚾᚻᛉᚹ•ᛒᚪᛋ•ᚠᚱᚱᛁᛉᚢᚦᚻ•ᚢᛗᚪ•ᛞᛝᛠᚪ•ᚫᛉᛖᚾᚹ•ᛟ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="33-39-6.vigenere.txt"
  text="ᛝᛞᚾ•ᛈᚫᚳᛡ•ᛈᚠᛉᚩ•ᛒᚷᛗᚫ•ᛚᚻᛞᚣᛖᛉᛒ•ᛄᚹᛇ•ᛈᚩᛁᚦᚠ•ᚷᚾᛈᛞᛝᛏᛖᚪ•ᛄᛋᛠ•ᛈᛝᚢ•ᛒᚷᚳᛉ•ᚪᚢᛈᛚ•ᛄᚱᚷᚣᚪ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="33-39-7.vigenere.txt"
  text="ᚪᚠ•ᛗᛝᚣᚳᛟ•ᚹᚣᚷᛈ•ᛗᛖᚩᚹᚢ•ᛟᛞᛋᚱ•ᚣᛞᛋᚳᛡᛉ•ᚻᚦᚹᛚᛞᛠᚩᛞᛠᚢᛟᛖ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="33-39-8.vigenere.txt"
  text="ᛠᚹ•ᛉᚻᛡᚹᛞ•ᚪᛗ•ᚠᚦᛈ•ᛝᛏᚳᚪ•ᛠᚣᚷ•ᚳᚦᛖᚾᚢᛁᚫᛁᚢᛡ•ᚹᛚᚳ•ᚻᛈ•ᛞᛄᚳ•ᛗᛒ•ᛗᚪᛄ•ᚩᚪᛞᛁ•ᚩᚱᛟᚠᛖᚣᛟᛁ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="33-39-9.vigenere.txt"
  text="ᛇᛟ•ᛁᛈᚣᛚᚪᛡ•ᚳᛏᛠᛋᛖᛒᛝ•ᚫᛟᚫᛞᛖᛞᚣᛡ•ᛠᚪᛖᚦᛚᚫ•ᚳᛋᚪᚩᚷᚹᛚ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="33-39-10.vigenere.txt"
  text="ᛈᛖ\'ᛏ•ᛄᛉᛝᛚ•ᛏᛉᚩᚣᛝᚠᚩᚣ•ᛁᚻ•ᛟᚫᚷᛄᛝᛡᚾᛗᚣᛟᛡ•ᛝᚷᛖᛉ•ᛟᛉᛈᛚᛋᛉᛠ•ᛚᛡ•ᚱᚪᛞ•ᛠᚷ•ᚱ•ᚳᛇᚻ•ᛗᚪᛟᚷ•ᛞᚪᛋᛡᚻ•ᛈᚷᛖᚳᛟᚱᛟᚢ•ᛁᚫᛟᚦ•ᛄᚱᛡ•ᚱᛖᚦᚣᛏᛝᛡᚩᛒ•ᛏᚦᚳ•ᛉᚳ•ᛋᚪᚫ•ᛗᚠᛄᚱᛖ•ᛡᛇᛁᛇᛟᛉᚳᚹᚪᛖ•ᛋᚢᛉ•ᛋᛟᛚ•ᛄᚾ•ᛈᛇᛒ•ᚦᚦ•ᛁᚫᛚᛋᛝᛄᛄᛡ•ᛟᚻᛇᚢᛚ•ᛁᚱ•ᛡᚻᛚᛏᚹᛉᛇ•ᚱᛏᛠ•ᛁᚫᛚᛗ•ᛁᚱᚷᛏᛠ•ᛇᛟᚻᛟᚳᛋᛏᚾᚩ•ᛁᚱᚷ•ᚹ•ᛞᚢᚣᛚᛁᛗᛒᚢ•ᛚᚱ•ᛏᛁᚢ•ᚷᚳᚠᛇ•ᛚᛇᚣᛏ•ᛏᚫᚢ•ᚫᛠᛇᚣᚾ•ᚢᚹᛝᚻ•ᚷᚣᚱ•ᚩᛁ•ᛚᚾᛉ•ᚾᚩᛈ•ᚠᛠᚫᚫᚩ•ᛉᚾᛋᛟᚫᛚ•ᚾᚫ•ᚦᚢᛠᚣᚫ•ᛈᛁᛇᚢᚱᛄ•ᛈᛟᛄᚪᛝᛈᚦᛈᚪᛝ•ᚣᛗᛟ•ᛉᛒᚢᛏᛇᛗᛈᚫᚣ•ᛉᚫᚣᚱᚫᚣᚠᚠᛗᛡ•ᛉᛖ•ᚱᚢᛏᚷᚢᚣᚱ•ᛡᚢᚩᛇᛁ•ᛄᚠᛈᛄᛞ•ᛁᚦᚩᚻᛡᚷᚻ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="33-39-11.vigenere.txt"
  text="1•ᛚᚦᛇᛟ•ᚪᚫᛠ•ᛗᛉᚻᚳᛉᚪᛏᚦ•ᚫᛉ•ᚩᛋᚳᛞᛏ•ᚣᚹᚾ•ᛟᛏᛉ•ᚹᛁᛟᛄᚠᛁᚩ•ᛁᚱᛋ•ᛉᚾᛗᚪᛡ•ᚱᛈᛋᛞ•ᛁᛟ•ᚻᛖᛏᚢᚹ•ᛠᛟᛞᛟᛄᛁᛝᛡ•ᛄᚱᛞᛗᛒ•ᚩᚳᚩ•ᚦᛟᚱᚢᛚ•ᚢᚦᛋᚢᛞᛚ•ᚷᛁᚣᛝᚩᛟ•ᛁᛖᚣ•ᛖᚠ•ᛇᛝᛒᛚᛁᚢᚣᚠᛟᚾᛟ•ᛒᛟᚷᛄᚪᚾᛗᚫ•ᚣᚦᚠ•ᛁᛒᛝᛈᚾᛁᚱᚷ•ᛄᛇᚫ•ᚻᚪ•ᚱᛉᛉ•ᚩᛚᚾᚫ•ᛞᚣᛒᚾᚪ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="33-39-12.vigenere.txt"
  text="2•ᚾᚣᛖᛉ•ᚾᚢᛉᛁ•ᛝᛏᛈᚹᛋᚣ•ᛏᛠᛈᛉ•ᚪᛁᛄᛋᚱᚪᛏᛋᛝᛏ•ᚳᚷᚳᚻ•ᛖᛟᚱᚪᛡᚻᚳ•ᛝᛒᛖᚱᛠᚪ•ᛚᛟᛖᛚᚪ•ᚦᛋ•ᚳᚹᚱᚹ•ᚩᚻᚣ•ᚢᛝᚩ•ᛈᛚᛁᛏᚪ•ᚠᛋᛝᛞ•ᚳᚪᚱᛒ•ᚹᛈ•ᚾᚩᚦᚳᚦᚾᛗᚩᛖ•ᚣᛇᚾ•ᚠᛒ•3•ᛞᚢᛈ•ᚹᚾᛖᚪ•ᚱᛚᛁᚹ•ᚫᛉ•ᛝᚠᛞᚪᚠ•ᛒᛄᛉ•ᛞᛄᛝᚣᛇᚪ•ᚫᛄ•ᛝᛈᚪ•ᚢᛠ•ᛇᛏᚱ•ᛖ•ᚫᛗ•ᚫᛠᚻ•ᛁᚫᛟ•ᛠᚹᚳᛄᚦᚻ•ᛡᚩᚢ•ᚩᚦᚷᛡ•ᚻᛋᚷᚪᛁᛟᛞᚪᛄ•ᛁᚹᛡᛒ•ᛗᛝᛡᛞᚠᛒᛋᛏ•ᛒᚷᚠ•ᚷᛟᚢᚳᚫᛏᛁᛖ•ᚱᚷᛗᚣ•ᚪᚷᚹ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="33-39-13.vigenere.txt"
  text="4•ᛝᛄᛋᛄᛗᚱᛗ•ᚾᛒᛋᛗᛉᛞᚻᛉᛁ•ᚣᛡᚻᚣᛠᛉᚻ•ᛞᛖ•ᚹᛖᚦ•ᚢᚳ•ᛉᛗᚪᚣᛠ•ᚹᚫᚪᚳ•ᚢᚫᚳᛇᚳᚣ•ᛡᚫᛏᛖᚳᚠ•ᛋᚻ•ᛋᚱᚢᚦ•ᛁᛋᛝᛗᛞᚫᚢᛠᚢᚪ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="33-39-14.vigenere.txt"
  text="ᚾᛝᚳ•ᛖᛈᚹᛉ•ᚢᛉᚫ•ᚾᛈᚳᚻᚱᚣᚹᛚᛉᚱᛒ•ᛗᚫᛟᚣᚩ•ᚳᛇᛗ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="33-39-15.vigenere.txt"
  text="5•ᚻᚫᛉᚦᛒᛟ•ᛏᛟᚹᛄ•ᚫᛠᛗᚠᚫᚳᚷ•ᛇ•ᚻᚹᛗᚻᛝᚣ•ᛁᚩᛁ•ᛏᛁᛖᛡᛄ•ᛗᚣᛚ•ᚻᚱᚩᛞᛒᛡᛈᛠᛗ•ᚳᛠ•ᛖᛒᚢ•ᚷᛁᚦ•ᛟᚫ•ᛡᚻᛝᛖᚾ•ᚱᛠᛡᛋ•ᚻᛏᛝᚻᚪᚷᚩᛝᚫ•ᚹᛚᛏᚱ•ᚷᛁᚾ•ᛖᛠᛄᛡᛞᛋᚻ•ᛝᚾᚳᛋᚾᛞᛇᚾᛋᛁᚳᛡ•ᚱᛝᛚᚫᚣᛇᛚᚩ•ᚳᛞᚾ•ᛝᚷᛡ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="33-39-16.vigenere.txt"
  text="ᛝᛄ•ᚻᛄᛚᛠᛟ•ᛄᛏᚷ•ᛚᛒᛝᚢᛏ•ᚻᚳ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="33-39-17.vigenere.txt"
  text="ᚫᛞᛟᚫᛟᛗ•ᛟᚫᚪᚻᚱᛗᚢ•ᚣᚢᚣ•ᛈᛗ•ᚪᛄᚫᛟᛠᛚᚠᛖᛡᚢ•ᛉᚻ•ᚪᚩᛡᛒᛠᚢᚷ•ᚻᛏᛠᚪᛞ•ᛋᚹ•ᚦ•ᚾᛋᛁᚻᛒ•ᛉᛠᛝ•ᛒᚢᛚᛟᚢᚾ•ᚢᚦᚩᛗᚪ•ᚾᛞᚫᛇ•ᚫᚣᚪᛋ•ᚣᛝᛡᛗᚷᛇᚾᛈ•ᛠᚳᚻᛝᛚ•ᚠᚷᛡ•ᛁᛡᚪᚠᛒᛈ•ᚳᛋᚦᛠᚦᚫᚱ•ᚷᛞᛚᛟ•ᚷᚱᛁᛇ•ᚣᚩᛟᚢᛝᚱᚷ•ᛗᛏᚷᛒᛈᚷ•ᛗᛏ•ᛗᚣᚹᛒᛏᛒ•ᚷᚣᛈᚷ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="33-39-18.vigenere.txt"
  text="ᚾᚦᛇᛒᚳ•ᚷᛖᛇᛟᛚᛈ•ᚹᚾ•ᚻᚷᚱᛇᛏ•ᛈᚷᛒ•ᚹᛗᛋᚹᛟᚻ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="33-39-19.vigenere.txt"
  text="ᛡᚳᛋ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="33-39-20.vigenere.txt"
  text="ᛈᛞᛋᛡ•ᚪᚹᛏᚳᚹᛟ•ᛗᚹᛁᛒᛞ•ᚷᛇᚢᛚ•ᛉᛋᚫ•ᛟᚻᛚᚦᛒ•ᚣᚪᛚᛞᚦᚠ•ᚻ•ᛞᛝᚩᚢᛋᚪᚫ•ᛖᚦᛁ•ᛏᛄᛏ•ᛝᚦᚾᚳᛉᛏᛝ•ᚳᛈᛁ•ᚾᛏ•ᛒᚾᛡᚱᛒ•ᚢᛈᛋᚦᛁᚳᛈᛋᛁᚹ•ᚹᛚᚣᚾᚢ•ᛒᛁᚪᛠ•ᚹᛟᚳ•ᛠᚢᚪ•ᛚᚦᚹ•ᚠᚾᛏᚳᛡᛁ•ᛚᚩ•ᚾᛗᛄᛠ•ᚦᛟᛄ•ᚪᚦᚹ•ᛡᚾᛖᛠᛈ•ᛒᛋᛄ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="33-39-21.vigenere.txt"

  echo "Section 40-55"

  text="ᚠᚾᛗ•ᚣᚷᛞᚫᚻ•ᚪᛈᛉᚣᚻ•ᛇᛠᚩᛖ•ᛏᛝᛠ•ᛚᛁᛏᚦᚠ•ᛗᚪᚳᛖ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-1.vigenere.txt"
  text="ᛞᚳ•ᛏᚱᛟᚷᛠᚾᚫᛒᚢᛖᛒᚢ•ᚦᚠᛟ•ᚷᛋᛟ•ᛁᛈ•ᛟᛉᛋᛒ•ᚹᛄᛒᚣᛗᚢᛠ•ᚱᛁᚢᛟᛄᛁ•ᛗᛖᚫ•ᚱᛋᛉᛝ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-2.vigenere.txt"
  text="\"ᛠᛈᛚ•ᛞᚩᛚᛁᛉᛠᛝᛖᚱ\"•ᚾᛈᛖᚹᛡ•ᚾᛄᛏᚣ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-3.vigenere.txt"
  text="ᛋᚩᛋᛏᛝ•ᚢᚾᛇᚪ•ᛖᛏᚪᛄᚳᚣ•ᛟᛒ•ᛚᛋ•ᛒᛞᛄ•ᛁᛝᚣᛖᚳ•ᛄᚻᛚᚣ•ᚷᚫᛚᛞ•ᛚᚫᛚᚦᛉ•ᛚ•ᛖᛉᚩᛉᛁᚳᚢᛗᚾᚢ•ᚩᚾᛇ•ᚻᛡᛚᛇᚩᚫᚪ•ᚩᛟᚩ•ᚣᚱ•ᛖᚠᚢ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-4.vigenere.txt"
  text="ᛁᚻ•ᛟᛚᚾᛏ•\"ᚠᛞᚱᛠᚷ•ᛈᚩᛇᚩᛗᛠᛒ•ᛄᛡ•ᛋᛗᚠ•ᛏᚠᚫᚩ•ᛟᚳᛚᛞᛡᛚ•ᚩᚳᛝᚢ•ᛈᚹᛏ•ᚷᚳᛋ•ᚢᛟᚷᚦ•ᚠᛉᚠᛏ•ᚳᛋᛉᛟ•ᚷᚠᛉᚾᛞ•ᛒᛏᛠᛡ\""
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-5.vigenere.txt"
  text="ᛈᛡᛠᛁᚪ•ᛋᚣᛗᛞᚣᛋ•ᛒᛞᛄᛞ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-6.vigenere.txt"
  text="ᚩᚾᛏᛚ•ᚳᚪᛝ•ᚱᚷᚻᚷ•ᛄᚹᚠ•ᚪᚢᛇ•ᛞᛏᛗᛄᛁ•ᛝᚫ•ᛉᛈᚳᛈᛠ•ᛟᚪᛒᛁᛁᛋ•ᛇᚷᚻᛋ•ᛇᛡᛒ•ᚠᚹᛝ•ᚫᚪᚠᚩᚣᛡᚪᚾᚻ•ᛒᚦᛟᛇᚣᛟᛁᛒ•ᛟ•ᚩᛋᚹ•ᛞᚳᚠᚪᛁ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-7.vigenere.txt"
  text="ᛉᛏᛟᚢᚩᛟᚦᛈᛋᚩ•ᚻᛇᚦᛝ•ᛏᛠᚠᛝᛠ•ᚩᛗ•ᛏᚠᚣᛚᚣ•ᚹᛚᛞ•ᚪᛉᛠ•ᚪᛄ•ᚩᛋᛒᛚ•ᚳᛖᚾᚪᚩᚱᛏᚦ•ᚱᛒᚳᚣ•ᛠᛗᚹᛚ•ᚻᛈ•ᛇᛈᛖ•ᛚᛄᚩᛡᚪ•ᛖᛋᚫᚩ•ᛠᛉᛝᚣ•ᛖᚫᛒᛗ•ᛖᚻᚱ•ᛈᚾᛗ•ᚹᛏᛟᚣᚢ•ᚠᛉᛈᛗᚩᚷᚾ•ᛡᛇᚳᚠᛒᛈᛗ•ᛋᛇᛁ•ᛖᛈᚢᚱᛏᚳᚣ•ᛄᛚᚠ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-8.vigenere.txt"
  text="ᚱᛚᚱᚫᛖᚻᛟ•ᛇᚣᛡ•ᚩᛉ•ᚪᛋᚣᛁᛝ•ᛉᛚᛄ\'ᚳ•ᛖᚣᚢᛝᚦᛇᚱ•ᛠᛁᚫ•ᚦᚠᛟᚷᛠᛁ•ᛈᛋᛒ•ᛗᛒᛄᚠᚾᚳᛖ•ᚻᚫᚩᛄ•ᛉᛄᛚᛈᚪᛁ•ᛟᚹᚱᛁᚱᚦᛖᛉ•ᚪᚾ•ᛞᛄᚷ•ᛟᛟᚳᛏᛄᛞ•ᛉᚾᛗᚦ•ᛁᛄᚱ•ᛈᛉᚢᚫᚦᛒᚠᛄᚦ•ᚠᚪᛝᛖ•ᚹᚹᚣᛚᛇ•ᚢᚣ•ᚾᚱᚪ•ᛈᚾᚹ•ᛚᚾᛏᛚᚢᛒᚱᛝᚪᛋ•ᚫᛈ•ᛄᛚᚢᚳᚷ•ᛚᛏᛄᚹᛈ•ᚫᛗᛚ•ᛉᛚᛗᛏᛞᚠᛈᛁ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-9.vigenere.txt"
  text="\"ᚠᚳᚦᛗᛄᚹᚱᚪᛚ•ᚩᛝᚱᚢᛈᚱᛟᛡ•ᚳᛉᚱ•ᛇᛏᚦᚾ•ᚱᛇᚫᛞᛟᚻ•ᛒᚾᚣ•ᚠᛡᚪᛡᛖᚫᛞᛄᚢᛖ•ᚦᚱ•ᚩᛇᚱᛡ•ᚣᛁᛉᛇᚻᚩᛠ•ᚫᚻᛡᛝᛠᚦ•ᚾᚣ•ᚾᚠᛁᛝ\""
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-10.vigenere.txt"
  text="\"ᛏᚻᚹᚫ•ᛒᛇ•ᛡᚻᛉᛒ•ᛞᛝᚱᛄᚦᚻ•ᚪᚷᚣᛁᚠᚷ•ᛁᛏᛞᛠᛒᚠᚩᛈ•ᛇᛡᛟᚹᚱᚾᚩᛏ•ᛋᚹᚢ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-11.vigenere.txt"
  text="ᛖᛡᛖᛡᚦ•ᛉᚪᚷᛈᚾ•ᛋᚱᚠᛞᛝᚻᛖᛄᛞ•ᛄᛡ•ᚱᚹ•ᚷᛝᚪᛒ•ᛄᛈᛄ•ᛏᚠᛉ•ᚪᛄ•ᛁᚠᛉᚢᚩᚣᚻᚦ•ᚻᚾᛁᛒ•ᛡᛟᛡᛋᛈᚣᛉ•ᛠᚢᛠᛚ•ᚠᛝᛗᚻ•ᚦᛒᚩ•ᛗᛚ•ᚩᛠᛋᚦᛠ•ᛇᛋᛉ•ᚠᛗᛒ•ᚫᛋᛇᚾᛡᚾ•ᚢᚫᚹ•ᛞᛠᚢᚾᛝᚠᚾᛖᚫᚻᛄ•ᛁᛖᛏᛡ•ᚷᛁᚩᚾ•ᚳᚢᚫᛗᛈᛋᚪᛡ•ᚷᛚᚣᚹᛟ\"•ᚠᚢ•ᛉᚠᚫᛞᚠᛡᛄᚾ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-12.vigenere.txt"
  text="ᚻᛋᚦᚠ•ᛏᚠᛄᚱᚹᚠᛋᚾᚹᛄᛖᛒᚢᚦ•ᚩᛇᚫᛈ•ᛡᛟ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-13.vigenere.txt"
  text="ᚢᛁᚩᛄᚩᛇᛟᛄᛞᚩ•ᛈᚹᛞᚷᚱ•ᚠᛟ•ᛇᚷ•ᛄᛟᛇᚫᛋᚫᚣ•ᛒᛏᛞᛟ•ᛠᚻᛡᚱᛠᛠᛉᛋ•ᚠᚾᚣᚱᚠ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-14.vigenere.txt"
  text="ᚪᚾᛡᚪᛖᚫ•ᚳᛇᛁᛝ•ᛒᛡᛞᛠᚫᛒᛠᚳᛉᚠ•ᚫᛏᛁᚱᚪᛗᚩ•ᛚᛉᛋᚪ•ᛒᚩᛈᚫᚩᛝᚻᛇᛖᛇᚫ•ᚻᛖᛇᛠ•ᚱᛗᛞ•ᚫᛇᛗ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-15.vigenere.txt"
  text="ᚾᚾᚣᛡ•ᚱᚾᛗᛠ•ᛄᛉᛋᛄ•ᛟᛖᛒ•ᛏᚻᚾ•ᚠᚪᚠ•ᛒᚾ•ᚩᚾ•ᛖᛋᛏᛒᚹᛡ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-16.vigenere.txt"
  text="ᚻᛏ•ᚩᛟᚩ•ᛒᚾᛖᚳᛁᚹᚣᛟ•ᛟᚩᛒ•ᛋᛖᚩ•ᚫᚻᛟᚠᚫᚷᚩᛄ•ᛟᛒᚻ•ᚳᛖᛁᛚᚫᚣᛚ•ᚢᛚᛁ•ᚾᛟᛏ•ᚫᛈᛟᛈᛝᛗ•ᚳᚢᛁ•ᚣᛋᚳᚢᛡᛇᚩ•ᚠᛖ•ᚷᛟ•ᚻᚫ•ᛝᚠ•ᛗᚠᛝᛉᛞᛁ•ᛗᛝᚣᚪᛝᚠᛉᛁᛟᚷᛚ•ᛇᚩ•ᚫᛡᛏ•ᛄᛏᛠᚢ•ᚷᚦᚣ•ᚦᚾᛟᚣᚩᛖᚻ•ᛁᛋᛖᚣᚦᚪᛡᛝᛟᛇᛚ•ᛡᛏᛝ•ᛁᛚ•ᚠᛉᛡᛠᛏ•ᚠᚾᛄᚠᚻᚳ•ᚻᛞᛠᚣᛟᛝ•ᛉᛇᚻᚩᛋᚻ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-17.vigenere.txt"
  text="ᛇᛏᚠ•ᛚᚱᛇᚦᚪᛁᛁ•ᛒᚠᛁᛚ•ᛄᛡᛒᚣᛗᚫᚫ•ᛞᚻᛟ•ᚪᚹᛉᛚᛏᛁᚪ•ᛟᛞᛖᚾᛈᚻᚣ•ᚦᛚᛖᛋᛖᛟᚫᛖ•ᛏᚱᚪ•ᛁᚫᚹᚫ•ᛋᛈᚱ•ᛄᛡᚪᛏ•ᚫᚦ•ᚠᛠᚢᛈᚣᚫᛝ•ᚣᚾᚻᛡ•ᚳᛗᚠᚾ•ᛞᛄ•ᛖᚩ•ᛒᚷᚻᚪ•ᛖᛞᛟᚠᛇᛞᛟ•ᛈᚳᛁᚪᛒᚷᛒᛈᛟ•ᛟᛄᚠᚪᛖ•ᛄᚣᚩᛄ•ᚣ•ᚫᛋ•ᚦᛁᚫᛄᚫᛏ•ᛖᛇᚻᛟ•ᚣᚠᚹᛞᚷ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-18.vigenere.txt"
  text="ᛡᚱᛒᚢ•ᛒᛚᚢ•ᚷᛈᛄᚪ•ᛏᛡ•ᚳᛄᚠᛡᛝᛚᚣᛒ•ᛗᚻ•ᚱᛚᛟᛠᛋᚦᛝ•ᛏᚳᛟᛉᛁ•ᛄᚱᚳᛖᛏᛄᚷ•ᛡᛈᛏᛉᚩᛁᛄᛟ•ᚷᚩᚪᚢ•ᚣᛖᚪᛋᛟᛇᚢᚪᛡ•ᛗᚱᛚᚳᚠ•ᛒᛗᛝ•ᚻᛉ•ᛠᛄᚫ•ᛉᚪᚷᚻᚣᛏᛖᛝ•ᛉᛉᛗᚾᚫᛋ•ᚱᛗᛞᛋᚳ•ᚦᛚᛟ•ᛝᛇᚢ•ᚻᚩ•ᛏ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-19.vigenere.txt"
  text="ᚢᛁᚦᛄᚾᚠᚱᚦ•ᛋᛟᚷᛠᛗᚪ•ᛝᛚᚪᛁᛒᛠᚢᛋ•ᚩ•ᛖᛋᛝ•ᚠᛡᚢᛟᛞᛇᚪ•ᛞᛡᛒᚹᚩ•ᛄᛋ•ᛟᛝᛏᚳ•ᚻᚾᛇᛋ•ᛗᛚᚻᛞᛖᛈ•ᚫᛄᚱᚪᚢᚻᚱᚦᚱ•ᛟᛄ•ᛟᛗᚩᛟᛏ•ᚫᛇ•ᛉᛒᚳ•ᛄᛁ•ᚪᚩᛉ•ᚹᚪᚾᛈᛏᚢᚣ•ᛁᛒᚢ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-20.vigenere.txt"
  text="ᚦᚩᛡ•ᛗᚳᚠᛉᚱᛁ•ᚪᛗᛏᛒ•ᛗᛚᛁᚦᛏᛠᛋᚾᚷᛚ•ᛏ•ᛇᛈ•ᚩᛚᛞ•ᛚᚹᚳᛄᚹᛉ•ᚪᛡᚹᛇ•ᛖᛖᚹ•ᛏᚪ•ᚣᚠᛉᚳ•ᛗᚩᚷᛞᚷ•ᛚᚳ•ᛒᚣᛋᚣᚠᛞᚣᛝ•ᛠᛇᛏᚩᚢᚫ•ᛟᛁᛒ•ᛏᚾᚫᚠ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-21.vigenere.txt"
  text="ᛄᛟᛗᚾᛈ•ᛠᛡᚩᛏᛡᚪᚱᛞ•ᚪᛝᛈᚹᛗᛄᛟᛠᚩ•ᛚᚹᛉ•ᚱᛗ•ᚩᛏᚹᛄᚹᚾ•ᚷᚳᛠ•ᛄᚳᚢᚱ•ᛟᛇᛟᚾᚻᚫᛉ•ᚣᛚᚩ•ᚩᛡᚳᚻᛄ•ᛋᚣᚹᛁ•ᚣᚠᛋᚾᚪ•ᚷᛖᚾᛄᚪᚹᛠ•ᛞᚠᛟ•ᚢᛁ•ᛖᛇᚦ•ᚫᛞ•ᚳᛄ•ᚷᚢᚻᚣᚻᛁᛒᛉᚾ•ᚹᛝᚻᛏᛉᚫᛁᛄᚢ•ᛞᚠᛡᚫ•ᛋᛁᚹᛝᛈ•ᛗᛉᛄᛈ•ᛞᛗᛝ•ᛇᛚᛞᚣ•ᚠᚩᛞ•ᛝᚷᚾᛇ•ᚷᛖ•ᛚᛉᚣ•ᚫᛚᛖᛉ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-22.vigenere.txt"
  text="ᛡᛝᛋ•ᚳᛁᚦ•ᚷᛏᚣ•ᚹᚩ•ᛝᛖ•ᛒᚪᛗᛏᚪᚷᛒ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-23.vigenere.txt"
  text="ᛈᛡᛟ•ᚪᛉᛝᛒᛞᛉᛄᚦᚢ•ᛏᛇᛖ•ᚣᚪᚳ•ᛠᚦᚹ•ᛏᛉᚩᚳᛞᛒ•ᛟᚩᛠᚾᚠᚪ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-24.vigenere.txt"
  text="ᛚᛗᛖᛁᚦᚫᚪᛡᛄᛁᚪᚱ•ᚦᚱᛖᛖᚣᛋᚾ•ᛖᛏᚢᚻᛈᚳᚦᛋ•ᚳᛇᛉᛖᛇᚠ•ᛞᛠᛏᛈ•ᚣᛇᛠᚢᛏ•ᛉᚦᚷᚻ•ᚫᚾᛠᚱ•ᛡᛒᛏᛁᛉ•ᚩᚢᛝ•ᛚᛒᛇᚩ•ᛟᛉ•ᚦᛞᚷᚠ•ᚩᚱᛈᚪᛏ•ᚫᛋᚪᚦ•ᛖᛟᚪᛝᚫ•ᚣᛒᛚ•ᛡᚦᚾᚠᛈᛟᛡᚾ•ᛖᚹ•ᛖᛗᚩ•ᛉᚹᚦᛠ•ᛁᚦᛒᛖᚱ•ᛟᚳᛉ•ᛈᛖ•ᛁᚢᚦ•ᛈᚠᛞᛈᛄ•ᛁᛟᚻ•ᛒᚦᛏᚩᚳᚢᛚ•ᛞᛄᛝ•ᚦᛄᛁᚪ•ᚹᚣ•ᚢᛝᚾ•ᛋᚾᛈᚠᚫᛒᛄᚫ•ᛡᛗᚹ•ᛇᚪᚩᚾᛄᚳᛚᛒᛉ•ᚣᛠᚦᚹ•ᛝᛚᛗᚳᛡᛇᚠᚫᛠᛁᚦ•ᛒᛠᛚᚦᚳᛞᛁᛇ•ᚠᚢᛉᛋᛉᛁᚦᚫᛋᛗ•ᚦᚹ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-25.vigenere.txt"
  text="ᛈ•ᛒᛋᛏᚫᚾᚱᛁ•ᚦᛇᛡᚱᛚᛡᚹ•ᚢᚩᛋᚱ•ᚹᚫ•ᛒᚹᛡᛖᛟᛄ•ᛡᚣᛖᚩᛖᛡᚷᚫᚠᚾᚹ•ᛟᛏᚫᚠᛄᚹᛠ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-26.vigenere.txt"
  text="ᚦᛞ•ᛁᚫᚩᚾ•ᛋᚷᛈᚪᛖᚩ•ᚣᚦᚹ•ᚾᚷ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-27.vigenere.txt"
  text="ᛠᛋᚩᛇᛏ•ᛝᛚᚷᛞ•ᛒᛈᛈ•ᛗᛁᚪᛖ•ᛚᛏᛁ•ᚫᛄᛖ•ᛒᚾᚠᚪᛋᚷᛒᚠ•ᚫᚹᚣᚷᚢᛡᚠᛠ•ᛖᛋᛞ•ᛚᚳᛒᛞᛏᛈ•ᛖᚾᛈᚣ•ᚱᚠᚻ•ᚫᛝ•ᛟᚪᛗ•ᛒ•ᛡᛚ•ᛝᛋᚱᚢᚹᚱᚣᚻᚹ•ᚹᛡᛈ•ᛁᚻᚾᚻᚱ•ᚳᛖᛏᚫᚩᛋ•ᚣᛋ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-28.vigenere.txt"
  text="ᛝᚫᛡᛝᚫ•ᚻᚦ•ᛇᚪᛞᛋ•ᛒᛁᚳᛈ•ᛇᛒᛟᚫ•ᛠᛝᛖ•ᛝᛠᚣ•ᛒᚣᛉᚻᚢᚠᚦᛞᚹ•ᛗᚢᛁᛡᛄᚩ•ᛋᛇᚫᛇᛝᚱ•ᛚᛇᛠ•ᛏᚩᛄ•ᚩᛝᛈ•ᚱᚻᛠᚢᛉᚦ•ᚣᚢᛋ•ᛡᛚᛖᚷᛗᛝᚹᚻᚱᛋ•ᚢᛟᚣᛠᚷᚩᚷ•ᛇᛁᛖ•ᛠᛄᛇᛁᚾᛄᚩᛗᚱᛡᛉ•ᚠᚻᚳ•ᚪᚩᚪᚫᚻᚳᛁᚦ•ᛄᚷ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-29.vigenere.txt"
  text="ᛝᛖᚢ•ᛡᛏᛁ•ᛚᚩᚱᛈ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-30.vigenere.txt"
  text="ᚠᚪ•ᛈᛞᚱᛒ•ᛝᛁᛋ•ᚷ•ᚠᚾᛈᚠᛒ•ᛟᚦᛁᛠᚪ•ᛡᛏᚾᚳ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-31.vigenere.txt"
  text="ᚦᛟᚻᛈᛖᛚᚫ•ᛟᚠᛗ•ᛡᛝ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-32.vigenere.txt"
  text="ᛒᛝᚦᛝᛠᚠ•ᛇᛗᛟ•ᚩᛠᛈ•ᛁᛡᚱ•ᚹᚹᛟᚩᛒᚩ•ᚾᚩᛄᛟᚾ•ᚦᛡᚠ•ᚩᛄᛞᚦᛏᛁ•ᛈᚾᚪᚱᛄ•ᛉᚱᚣ•ᛝᛡ•ᛏᛗ•ᛈᛞᚣᚻ•ᛗᛝᚫᚳᛇ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-33.vigenere.txt"
  text="ᛡᚣᛄᛟ•ᛝᚩᚢᛇᛁᚱ•ᛏᚪ•ᚩᚻᚪᛚᚫᛚᚪ•ᛋᛈ•ᛏᚪᛄᚳᚦᚢᛏᚹᚦ•ᛗᚷᛖᛗᚣᛡᛁᛞ•ᚢᛋᚠᛒ•ᛟᛚᛟ•ᚪᛒ•ᚦᛚᚣ•ᚳᛠᚣ•ᛞᛇᛁ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-34.vigenere.txt"
  text="ᚹᛉ•ᛟᛝᛒᚢᛋᛞᚻᛞ•ᚢ•ᛠᚱ•ᚫᚩᚻᛝᛒᚪᚹ•ᛈᛡᚾᛚᛇ•ᛖᛟᛝ•ᛡᚠᛇᛡ•ᚳᚦᚹ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-35.vigenere.txt"
  text="ᛚᚦᚪᛁᛈ•ᛞᛟᛄ•ᚢᛉᚢᚾᛠᚠ•ᚩᚾᚪ•ᚱᛠᚷ•ᛗᚢ•ᛗᛁᛄᛒᛗᚱᚾᛗ•ᚩᚾᚠᚣ•ᛗᚠᛇᚠᛄ•ᛒᛡᛈᛄᛖᛡᛏ•ᛈᛟᚫᛏᛟ•ᚻᛖᚾ•ᚳᛇᚩ•ᛋᚻᚫᛇ•ᛝᛁᛟ•ᛇᚠᚢᛞᚣᚪᛚᚠᛡ•ᛖᛄ•ᚠᛚᛟ•ᛁᚳ•ᛁᛝᚷᚦ•ᛗᛋᚫᚷᚪᛠ•ᛗᛁ•ᛒᛡᛏᚾ•ᛝᛗᚦ•ᛏᚣᚫᛄ•ᛖᚻᚠᚪᛡᚷ•ᚪᛗᛁ•ᛞᛉᛏ•ᚢᛖᚦᚾ•ᛖᚪᛈᚹᛠᛚ•ᛒᚢᚱᛡᛟ•ᚪᚣ•ᛟᛇᚹᛄᛈᛞ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-36.vigenere.txt"
  text="ᚹᚹᛈ•ᚠᛡᛚᛉᛒᚾ•ᚳᛗᚾᚱᛗ•ᚻᚦᚫᛞᛄ•ᛒᛡᚫ•ᛇᚹᛗᚢ•ᚪᛈᛡ•ᛈᛁᛄ•ᚪᚢᚾᛠᛖᛞᛗᚪ•ᛏᛟᛗ•ᛋᛞᛝᚷᛚᛋᛞᛝ•ᛟ•ᛋᛄᛞ•ᛚᛟᚠᛄᚫᚠᚪ•ᛝᛟᚣᛈ•ᚣᚩᛒᚷᚳᛖᛏᚹ•ᚪᛋᛒ•ᛗᛠᚣᛇᛗᚫᛚᚱ•ᚹᛇᛄᛒ•ᛈᛚᚠᛈ•ᚠᛗ•ᛝᚪᛇᚾᛟᚹᛇᛉ•ᚣᚫᛉᛞᛟᚱᛒ•ᛡᚱᛟ•ᚹᛏᚷᚱᛄᛖ•ᛠ•ᛈᛚᛞ•ᚻᚦᚱ•ᚦᚣᛚᛉ•ᛠᛈᚫᚠᚪ•ᚫᚪᛒ•ᛈᛋ•ᛗ•ᛏᚫᚳᛈᛝᚹᚦ•ᚻᛠ•ᛞᚩᛄᚷ•ᛋᚩᛠᚳᛖᛋ•ᚣᛖᚫ•ᛈᚦ•ᛁᛇᛈᚳᛝ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-37.vigenere.txt"
  text="ᛈᚳᛇᚢᛏᚳᛡᛇᛝᚾᚢᚻᚦ•ᚣᚠᛗᚾ•ᛝᚠᛄᛉᛟᚱᛗ•ᛝᛠᛄᛏᚳ•ᚢᚷᚦ•ᚠᚦᛋ•ᚪᛈᚩᚪᚫᛞᛋᛝ•ᛒᛗᚩᚷ•ᚹᚠᛗᛖ•ᛠᛇᚻᚠᚻᚳᚱᚫ•ᛝᛗᛉᚳ•ᛋᚪᚹᛋᛠ•ᚩᚣᛚᛉᛝ•ᛠᛟᛉᛟᛠᛡᛝᛒ•ᛝᚳᚫᛁᚱ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-38.vigenere.txt"
  text="ᛒᚠ•ᛏᚣᚣ•ᛠᛒ•ᚣᛚᚩ•ᛇᛉ•ᚩᚷᛗᚩ•ᚠᛚᛟᛝᚦᛠ•ᚦᚣᛖᚣ•ᚾᚷᚾ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-39.vigenere.txt"
  text="ᛡᛏ•ᛄᛟᚾᛁ•ᛋᛟ•ᛠᚦᚣ•ᛋᛒ•ᚫᛚᚪᛄᛡᛖᚷᛉᛡᚾᛉᛏ•ᛡᛒᚻᛚᚷ•ᚢᚦᛠ•ᚢᚾᛁᚩᛗᛠᛁᚷ•ᛟᚦᚱᚣ•ᛒᛖᛠᚩᛈ•ᛗᛏᚱᚫᚢᚻᛁᛝ•ᛇᚳᚠ•ᛄᚾᚱᚷ•ᛟᚷᚻᚣᚻᛇᚫᛠᚫᚣ•ᚢᛗᛈ•ᛉᛁᚢᚾᚩᛟᚾ•ᚷᛞᚦ•ᛡᚫᚹ•ᛞᛟᛖᚱ•ᛗᚾᛖᚻᚷᛒᚢᛄ•ᚢᚦᛗᛖᛞᛝ•ᛒᚷᚣᚱ•ᛖᛁᚢᛄ•ᚣᛡᛚᚢ•ᛄᛟ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-40.vigenere.txt"
  text="\"ᛠᛉᚣᛇᚱ•ᚩᛈᛋᚳᚫᛗᛇ•ᚾᛄ•ᛖᚠᛋ•ᛖᚠᚪᛝ•ᚢᛝᛄᛇᚷᚠᛝᚱᛁᚦ•ᛄᚢᚫ•ᚣᛋᚠᛖᚢᛋᚫᚣᛠ•ᛁᛏᛟᚱᛏᛟᚩ•ᚷᚾᚻ•ᛞᛗᚩᚳᛞᛖᛏ•ᚹᛉᛞᛚ•ᚩᚫᛄ•ᛇᚢᛒ\"•ᛗᛏ•ᛞᛗᛖ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-41.vigenere.txt"
  text="ᛏᛈᚹᛇᛋ•ᚹᛒᛇᚦ•ᚾᚻᚷᛄ•ᚱᛡᛞᛡᚦᚪᛁᛇᚫᛉᛚ•ᛇᛠ•ᛡᚪᛄ•ᚻᚱ•ᚦᛈᛞᛄᛝᚩ•ᚷᚠᛇᛗᚳ•ᚻᛞᚩᛏᚳ•ᚢᚱ•ᛈᚾ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-42.vigenere.txt"
  text="ᚪ•ᛗᛝᛞᛡᚦᛉᛁᛗ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-43.vigenere.txt"
  text="ᛡᛞᛈᛝᚢᚹᚪᛗ•ᛏᚪᛝ•ᛝᚦᛡᚹᛋᚻ•ᛁᚳ•ᚫᛈᚫᚷᚩ•ᛗᛁᚪ•ᛖᚩ•ᛏᚹᚩ•ᚠᚣᚢᛏᛄ•ᚦᛄᛠᛖᚳᚾᛠ•ᚳᛠᛖ•ᚱᚩᚢᛉ•ᛞᚹᚻᛒᛝᚠᚪᚳᛄᚢ•ᚩᛄᛡᛠᛁᛚᚷᚻ•ᛒᚢᛄ•ᛉᚪᚳᚹᛡ•ᛗᚩᛈᚣᛞᛡᛚᛈ•ᛇᛁᚦᚱ•ᚣᚷᛗ•ᛉᛟᚷᛋ•ᛗᛈᛄᛟᛞ•ᛟᛏᛡᛟ•ᛏᛝᛁ•ᛗᛝᚣᚪᚫ•ᛝ•ᚱᚣᛄ•ᚾᛚᚢᛉᛒ•ᚻᛈᛄᚩᛠ•ᚷᚫᚹ•ᛉᛋᛞᚳ•ᚢᛏ•ᛟᚻᛇᚾᛈᛏ•ᛠᚣᛒᚢᚷ•ᚷᚪᛇ•ᚾᚷᚩᛖᛚᛗᛒᚦ•ᚣᛡᛟᛇᚣ•ᛗᚳᛟᚦ•ᛖᛚᚱᛇᛈᚱᛞᚣ•ᛉᛞ•ᛝᚣᛈ•ᛋᛖᛉᚹ•ᚳᚷᚠᛞᚱᛖ•ᛞᛖᚹᚩᛇᛟ•ᚻᚩᛟ•ᛒᛋ•ᚻᛠᚪᚳᛁᛗᛉᛄᛗᛖ•ᛗᛚ•ᚷᚩᛏᚦᛉᛖᛠᚱᚷᚣᛝ•ᚫᛗᛁᚹ•ᛋᛒ•ᛉᛗ•ᛋᛇᚷᛞᚦᚫ•ᚠᛡᚪᛒᚳᚢ•ᚹᚱ•ᛒᛠᚠᛉᛁᛗᚢᚳᛈᚻᛝᛚᛇ•ᛗᛋᛞᛡᛈᚠ•ᛒᚻᛇᚳ•ᛇᛖ•ᛠᛖᛁᚷᛉᚷᛋ•ᛖᛋᛇᚦᚦᛖᛋ•ᚦᛟ•ᚳᛠᛁᛗᚳᛉ•ᛞᛄᚢ•ᛒᛖᛁ"
  ./cipherval -ciphertype="vigenere" -wordfile="$i" -alphabet="rune" -text "$text" -output="40-55-44.vigenere.txt"
done
