rm gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛋᚻᛖᚩᚷᛗᛡᚠ•ᛋᚣᛖᛝᚳ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚦᛄᚷᚫ•ᚠᛄᛟ•ᚩᚾᚦ•ᚾᛖᚹᛒᚪᛋᛟᛇᛁᛝᚢ•ᚾᚫᚷᛁᚦ•ᚻᛒᚾᛡ•ᛈᛒᚾ•ᛇᛄᚦ•ᚪᛝᚣᛉ•ᛒᛞᛈ•ᛖᛡᚠᛉᚷᚠ•ᛋᛈᛏᚠᛈᚢᛝᚣᛝᛉᛡ•ᚣᚻ•ᛒᚢ•ᚷᚩᛈ•ᛝᚫᚦ•ᛁᚫᚻᛉᚦᛈᚷ•ᚣᚠᛝᚳᛄ•ᚦᚪᛗᛁᛝᛁᛡᚣ•ᚻᛇ•ᛏᚻᚫᛡ•ᛉᚣ•ᛖᚢᛝ•ᚳᚠᚾ•ᛇᚦᛄᛁᚦ•ᚦᛈ•ᚣᛝᛠ•ᚣᚾᛖᚣ•ᛞᛉᛝᚹ•ᛒᚳᛉᛞᛒᚠ•ᛗᛏᚾᛖ•ᛠᛄᚾᛚᚷᛒ•ᛉᚷᚦ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚣᛁᛞᚪ•ᛝᚷᛗᛄᚱᚩᛚᛇ•ᚣᛏᛈᛁᚦᛞᛄ•ᛟᚻᛚ•ᛠ•ᚠᛉᚫᛈᚷᛉ•ᚠᛚᚹᛇᛏᚫ•ᚠᚷᚾ•ᛗᛇᛚᚾ•ᛝᛗᚠᚱᛡ•ᚪᛋ•ᛠᛗᛝᛉᛉᛇᛞᛒ•ᛟᛞᛗᚩ•ᛠᛇᚻ•ᛞᛝᚷ•ᛟᛝᛚᚢᚱᚾᛏ•ᚫᛋᚣᚢᚻᚱᛏ•ᚻᚳ•ᛋᛟᛏᛟᛝᚢᚱ•ᛋ•ᚠᚩᛖᚹᛠᛟᛚᚠᚫ•ᛗᚱᛝ•ᛞᚪᛗᚱ•ᚹᚪᛁᛗᛋᚾ•ᛋᛟᚱᚢᚹᛋᛚᛡ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛟᚪᚫᛝᛋᛞᛈᛏ•ᚳᚱᚦᛡ•ᚱᛒᚩᛞᚦᚠ•ᚣᛉᛁᛏ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛟᛁ•ᚠᛚᚩ•ᚠᛠ•ᚱᚩᛟᛗᚻᛗᚷᛈᚻ•ᚫᚻᚾᚩᚻᚣ•ᛟᛋᛚ•ᚾᚷ•ᚫᚣ•ᛟᚳᛒᛚᛄ•ᛝᛚᛟ•ᚫᛄᛠᚹ•ᛠᚦᚩ•ᛒᛟᚣ•ᚳᚠᚳᛄ•ᛚᚫ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚾ•ᚦᛈ•ᚢᛉ•ᛟᛉᚷ•ᛈᚠᛋᛇᚫᛟ•ᛝᛈᛇᚩᛖᚪ•ᚷᚫᛡᛝᚦᚩ•ᛈᚪᛟᚦᚱᛝᚫ•ᚳᛋᛒᛇᚣᚻ•ᛏᛉᛖᛚᚱ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚷᚹᚣ•ᛄᚠᛁᚾᛡᚳᚣᛠᛁᛡ•ᚩᚦ•ᛖᚳᚫᚳᛉᛡᛠ•ᚩᛚᚳ•ᚠᚱᛞᛝᛖᚢ•ᛞᚳᛚᛠᛋᛉᚳᚷᛡ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚹᛋᚦ•ᚠᛞᛝ•ᛁᛡᛗᚪᚫᚷ•ᚹᛋ•ᚾᛞ•ᚳᛈᚦᛉᛈᛠᛠ•ᚹᚢ•ᛠᚹ•ᚠᚹᛄᚣ•ᛉᛞᚹᚳᚷᚳᛟ•ᛞᛉᛟ•ᚱᛡᚷ•ᚾᛈᚪᚣᛈ•ᚳᚣᚻ•ᚠᛖᛄᛠᚾ•ᛟᚫ•ᚢᚪ•ᚻᚱ•ᛖᛠᚦᚠᛄᚪ•ᛚᛉᛋᛏ•ᛗᚠᛚᚠᛏ•ᚷᛁᚦ•ᚢᛚᚷ•ᛉᛠᛏᛋᛚᛄᛈ•ᛚᛉᛁᛟᛗ•ᚢ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚻᛏ•ᛒᛇᛚᛞᚻᛒᛗ•ᛠᚱᛒ•ᚾᚻᛒᛖᚷᛇ•ᛞᛚᚹᛇᛡᛈᚩ•ᚻᛖᛠ•ᚹᛁᚱᛁᚻ•ᚢᚦᚻᚣ•ᚾᛉᛒᚷᛄᛈᚢ•ᛝᛠᚠᚾᛁᛖᛞᛡᛝᚱ•ᛞᛒᛄᛡᛟᛗᛁ•ᚠᛏ•ᛄᛞᛁᚦᚱᛚᛋ•ᛖᛇᚩᚷᛒᛏᛞ•ᚦᚪᚾᚳᚣ•ᛡᛋᚦᛞ•ᛝᚠᛚᛖᚷᚻᚳ•ᛖᚩᛁᛏᚾᛉ•ᛈᛏᚠᚻᚱᛞᛖᚠᛏ•ᚫᚹᚻ•ᛒᚳ•ᚠ•ᛈᚪᛚᚢᛠᚾᛚᛄ•ᛄᚳᛚᚹᛠᛞᚢᛞᛇ•ᛠᛉᛞᚹᚻᛠ•ᚦᛡᚫᚳᛚᛏᚹᛖᛁᚳ•ᛈᛟᛞᚳ•ᚾᚻᚪ•ᚱᛁᚷᚦᛠᛖᛏᚷ•ᚦᚻᚩᛡᚹᚫᛄᛖ•ᛝᛠᛞ•ᚩᚫ•ᚪᛚ•ᛒᛄᚳᚢᛉᛏᚪᛒᛄᛈ•ᚠᛠ•ᚻᛞᚾᛡᚢᛈᛋᚢᚹ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛚᛄ•ᛇᚻᛝᚳᚦᛏᚫᛄᛏᛉᚻ•ᛏᚢᛟ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛋᛈᚱᚷ•ᚣᚾᚪᚷᛇᛝᚾ•ᚹᚠᚣᚾᛒᛠᛡ•ᛈᚾᚣᚪᛋᛗᛒ•ᛡᛠᛡᛁ•ᚩᛒᚱᚾᛚᛠ•ᚱᛚᛚᛖᛒᚹᚾᚻᛗᚠᛟᛒ•ᛝ•ᚱᚪᛡᚷᛟᛇᛏᛗᛉ•ᛞᛇ•ᛗᚣᚻᛠ•ᛁᛚᛋ•ᚾᚹᚳᚠᛈᛗᛈᛚ•ᛠᛋᚦᚠᛟᛡ•ᚦᛖᚣ•ᚳᛄᛚᚳᛡᛗ•ᛒᛞᚳᛇ•ᛄᛁᛏᛟ•ᛞᛠᛖᛡᚾᛏ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛈᛞᚦ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛇᛞᛇ•ᚫᛚᚳ•ᛡᛇ•ᛠᚻ•ᚹᛗᚣᚦᚢ•ᚻᛏᚦᚱᚻᛝ•ᛚᛝᛋ•ᚾᚫᛠᚷᛋᛚ•ᛋᛉᚩᚻᚹᛞᛗᛖᛗᚪᚠ•ᚳᚣᚳᚫᚾ•ᛏᚦᚷ•ᛁᛄᛁ•ᚳᛞᛡᛉ•ᚻᚫᚫᛠᚷ•ᛠᛝ•ᚠᛏᚩᚱᛞᚳᛇ•ᚠᚢᛉᛠᛒᚩ•ᛉᛁᚣᚷᛋᛋᛒᛠ•ᚩᛁᛈ•ᛁᛄᛁᚩᛖ•ᚻᛠᚻᛚᛡ•ᚣᛈᛉᛁᚹᛗᚳᛁ•ᛚᚷᚠᚾᛡᚳᛉ•ᛈᚩᚱᛡ•ᚻ•ᛄᛗ•ᛟᛉᛝ•ᚢᛗᛇᛠᚷᛝ•ᛝᚹᚳ•ᛚᛝᚢ•ᛉᛄᚠᛟᚢ•ᚷᛠ•ᛗᛉ•ᚪᚹ•ᛚᚢᛉᚫ•ᛗᛞᛝᚻᚱᚣ•ᚻᚪ•ᚷᛁᚠᚷᚳ•ᚫᛝᛄᛇᛉᛡ•ᚾᚦᛒᚢᛄᚱ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚹ•ᚷᛚᛟᚷ•ᚦᛇᚠ•ᚦᛠᛁ•ᛋᚷ•ᚷᚣ•ᛠᛡᛈ•ᛡᚫᛚ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚦᛠᛉᚫ•ᛖᛗᛖᛏᛟᛏ•ᛠᚳᚠ•ᚳᛠᚷ•ᚦ•ᛈᛁᚳᚾ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛇᚣᛝᛄᛝᛗᚹᚳᚾ•ᛒᚣᛠ•ᚩᛟᚷᚱ•ᛗᚱᛗᛈᛡᚹ•ᚫᛟᚦᛟ•ᛈᛉᛄᛚ•ᚱᛚᚱᛒᚪᛈᛏᛉᛚᛏ•ᛗᛉᛁ'ᚹ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛄᛋᛟᛗᚾᚱᛖᛒᛋ•ᚳᛏᛚᛟ•ᛋᛒᚠᛉᚦᚪᛠᚢ•ᛇᛉ•ᚱᚷᛏᛇᛠᛁᛄᛒᛟ•ᛉᚷᛄᛝ•ᛠᚦ•ᚱᛝᛒ•ᚾᚢᚪᛝᛒᛈᛋᛠ•ᛈᚹᚩᚻᛖ•ᚫᛇᚷᚾᚫᛋᛇ•ᚩᛈᛗ•ᛖᛉᛡᛒᚹ•ᚢᛖᛁᛞ•ᛈᚪᛇᚷᛋᚳᚷᛞᛈᚣ•ᛡᛚᚦᚱ•ᚳᚢᚠᛇᚦ•ᛉᛖᛚ•ᚢᚱᚫ•ᛉᚻᛄᚫᛗᛚᚠ•ᚳᛝᛞ•ᛁᛝᚩ•ᚳᛋᛟᛖᚣᛟᚻᚢ•ᚷᛞᚹᚪ•ᛖᛋᚷᛝᚠᛉ•ᛞᛉᛄ•ᛠᚻᛁ•ᚦᛈᛉᚣ•ᛡ•ᛇᛞᛇᛝᛇᛝ•ᛖᛠᛞᚱ•ᛚᛇᛏ•ᛉᛏᚣ•ᚱᛇ•ᛈᛝᛇᛈᚩᛁᛚᛖᚠ•ᛇᚫᚪ•ᚣᛝᚠᚣ•ᚠᛞᚾᛚ•ᛉᛏᚾᚫᛋ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛁᚩᚳᚢ•ᚣᛠᚾᛏᚷᚳᚪ•ᛉᛡᛇ•ᚦᛄᚣᛄᛚᛟᛖᛚ•ᚣ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛈᛡ•ᛖᚹᛟ•ᛇᚾᚪ•ᚻᛞᛇᛋ•ᚦᚣᛇᚦᛄᚦᚱᚢ•ᚳᛠᚪ•ᚢᛄᛡᛈ•ᚣᚫᛇᛋ•ᚻᛠᛏᚣᛞᚣᚫᚠᚻᚩ•ᛟᛗᛉᛟᛄᚷ•ᚢᛡᚱᛡᚳ•ᛁᚠᛟ•ᛁᛄᛈᛒ•ᛖᛝᚣᚦᚩᚫᚣ•ᛠᛉᛡᛖᛚ•ᛁᚱᚣᛞᛠᛄ•ᚫᚳ•ᛗᚷᛁᚫᚢᚪᚫ•ᛄᚪᚻᛈ•ᚠᛞᛚᛁᛠᛈᛟᚣᚩ•ᚢᛒᚷᛝᛟᚢᛝᛋᚢᚳ•ᛏᛞ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚫᛈᚩᛄ•ᛒᚻᚱᛁᚷᚻᛄ•ᚣᚹᛗᛇᚾᚫ•ᛞᛝᛇ•ᛟᛄᛝᚳᛖᛠ•ᛉᚪᚱᚣ•ᚪᚢᛏ•ᚳᛈᚳ•ᚩᛇᛟ•ᚫᛈ•ᛏᛉᚳᛏᚻᛞᛇ•ᛉᛒᛠ•ᚫᚾᛄ•ᛠᚪᛒ•ᛖᛠᚹ•ᛡᛚ•ᚹᛁᛡᛋᛈᛚᚦᚪᛋᛄ•ᛡᛞᚣᚱᛞᛟ•ᚦᚱᛉᛟᚹ•ᚣᛞᛏ•ᚷᛚᛡᚻᚹᛗᚱ•ᛝᚠᚳ•ᚱᚫᛁᛒᚷᛈᚣ•ᛞᚪᚱᚪᛉᛟ•ᚢᚩᛁᛠ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚪᛏᛉᛒ•ᛗ•ᚷᛡᛋᛒ•ᛉᛇ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚷᚾᛠᚫᚷᛝᛞ•ᛉᛖᛏᚩᚷᛡ•ᛝᚻᛏ•ᚳᛁᚣ•ᛄᛏ•ᛟᚩᚻᚱᛄ•ᚳᛖᛡᚩ•ᛞᚪᛏᚣᚢᚾᚱᛇ•ᚫᚫᛁᛖᚠᛝᚦᚻ•ᛉᛁᛟᛋᛁ•ᛗᚪ•ᚢᛄᚳᛋᚹᚾᚣ•ᚩᛈᛉᚱ•ᛚᚫᛟᛏᛡ•ᛄᛈᛗ•ᛞᛋᚠᛗ•ᛟᚹ•ᛞᛚᛏ•ᚷᚱ•ᚩᚢᛋᚻᚪ•ᚣᛇᛡᛚᚢᚻ•ᛈᚹᛄᛚᚷᛒ•ᛗᚢᛄᛗ•ᛇᚾᛇ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚫᛚᚪᛚᚷᚪ•ᛋᚻᛝ•ᛚᚦᛒ•ᛋᚳᚢᚳᚩᛡ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛚᚳᛄ•ᛉᚪᚾᛇᛉ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛠᛗᛈᚢ•ᛗᚠᛚᛠᛝ•ᛒᛉᛁ•ᛚᚦᚱ•ᛠᛡᛁᚳ•ᚩᛉᛖᛞᛡ•ᛏᛋᛗᛠᛄᛈ•ᛠᛟ•ᛡᚫᚦᚹᚻᛈᛇᚪᚷᛈᚻᛠ•ᚳᛚᛠᛈ•ᛡᚣᚾᛁ•ᛚᛡᛁᚳ•ᚫᛇᚾ•ᚫᚳᛡᚱᛡᛚᛞ•ᛒᛟᛝᛡ•ᛉᛗᛝ•ᚳᚻᛟᛠᚾᛈᚳᚦ•ᛁᛇᚦ•ᛇᚢᚩ•ᚦᛈᚪ•ᛡᛚᛟᚹᛡᛈ•ᛄᛗ•ᚷᛒᛈᛋᚾᛇ•ᛏᚩᚷᚢᚾᚫᛖ•ᚾᚣᛁᛖ•ᛞᛝ•ᛞᛝ•ᛚᚢᛚᛉ•ᚪᚾᛝ•ᛇᚪᛄ•ᚻ•ᛞᚹᛈᚫᚹᚫ•ᛇᛁᛚᛝ•ᚦᚾᚳ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛒᛁᛏ•ᛠᚳᚩᛇᛖᛝ•ᚳᚻᛟᚻᚫᛄ•ᛟᛉ•ᛁᚳᛖᛏᛋᚹᛖᚾᛡᚣᛄᛗ•ᛖᚳᚪ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛞᚩ•ᛟᛏᚦᚫ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚳᚹᛄ•ᛉᛠ•ᚷᛠᛗ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛉᛁᛉᛗ•ᚢᛉᛗᚳᚦᛈᚩᛒ•ᛡᚾᛏ•ᛠᛉ•ᛈᚱᚣ•ᚩᚳᛠᛗᛝᚷᛉᛚᚢ•ᛝᛁᛏᚩ•ᛄᚠᛝ•ᛋᛚᚾᛞ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚩᛗ•ᛇᚫ•ᚱᛞᚹᛏᛄᚦ•ᚣᚦᛋ•ᚫᚣᛖᛋᛉᛟᛒ•ᛠᚱᛇ•ᛈᛝᚢᛈ•ᚩᚦᛉ•ᚪᚻᛟᚱᛝᚢᛖᚱ•ᚣᛚᛉᛚ•ᛡᛚᚱ•ᛈᚹᛇᚾ•ᛠᚪᚱᛉᛝ•ᚣᛋᚻᚢᛚ•ᛋᚣ•ᚷᚾᚢ•ᛇᚫᚾᚾ•ᚩᚫᛖᛞ•ᚪᚩᛄᛡᚢᚪᛉ•ᚱᛉᛡᛟᛄ•ᛗᛁᛇᛚᛠᚻᚦᛗᛠᚣ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚷᛒᚳᛈᛉᚳ•ᚾᛟᛟᛋᚷᛗᛈᛖᛏᛚᚾᛄ•ᛄᚳᛝᚩ•ᛁᚹᛚᛠᛒ•ᚠᚪᛖ•ᛏᛝ•ᚾᛈᛠᚩᛏᚦ•ᚻᛝᛉᛈᚻᛈᚳᛈᚱᚢ•ᛚᚠᛖᛟ•ᚷᚪᛒᚠᛁᚫᚠᚢᛟ•ᛗᚠᚣᛝᛄᚳ•ᚻᛏᚠᛚᚫ•ᛖᚦᛋᛚᚩᚢ•ᚫᚩᚪᛗᛟᚢᚹᛇ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛒᚾᛋᛚᛝᛄᛟᚾ•ᛗᛚᛒ•ᛟᛏ•ᚾᛞᛒᚩᚾᚦᛡᚻᛟ•ᚱᛈᚾᚠᛈᛞ•ᛋᚩᛁᛠᚣᚾ•ᛇᚣᚹᚫᚷᛄ•ᛝᛗᚪᚹᛈ•ᚪᚢᚾ•ᛈᛡᛗᛖᛞᛟ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛁ•ᛉᛡᛗ•ᚠᛈᚩ•ᚦᛉᛞ•ᚩᛞ•ᛋᛈᛉᛡᚷ•ᛟᚻᚠᚦᛉᛄᛟᛋᚦᚣᚦ•ᛏᚻᛋᚣ•ᚻᛠᚷᛚᚫᚱᛏ•ᚢᛋᛟ•ᚦᚠᚠᚣᛟᛡ•ᛇᚳᚣᛒᛚᛝ•ᛠᚱᚻᛞ•ᛄᚣᛏᚫ•ᚻᛞᚳᛋ•ᛉᚠᛞ•ᚦᛗ•ᚳᛇᛝ•ᚫᚾᛡᛠᚹᛁᛡ•ᛒᛗᛝ•ᚷᛈᛁᚳ•ᛠᛚᚷᛉᚣᚣᚱᛄ•ᛉᛁᛄᚢ•ᛖᚣ•ᚪᛝᛈ•ᛡᚫᚳ•ᛖᛠᚹᛒᚦᛟᚠᛗ•ᚫᚱᚠᚩᛏ•ᛝᛉᛞ•ᛗᛖᛡ•ᚩᛈᛋ•ᛇᛞ•ᛇᛟᚫᚾ•ᚷᛗᚣᛁᚫᛁᛄ•ᛈᛄᚩᛡᚷ•ᛈᚳᛄ•ᛚᛖᛡᚻᛚᚷᚱᛇ•ᛟᚣ•ᛠᚣᛗᚹᚾᚹ•ᚠᛁᛄᚢᛗᚫᚾᚳᛗᛠᛁ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚩᛇ•ᛒᛚᛞ•ᚾᚹᚠᚾᛒᚱ•ᛋᛟᚦᛡ•ᚪᛡᛏᚷᚷᚹ•ᚪᛋᛡᚦᛋᚦᛋᚠᛗᚷᛞᛠ•ᛝᛈᚩᚪᚣᛝᛈᛋ•ᛟᚾᛇᚪᛖ•ᚻᚢᚷ•ᚩ•ᚢᚦᛏ•ᛒᚷᚣᛝᚠᚣᛁᚻ•ᚹᛡᛠᚱᚫᚹᛡᛞᚪᚦᚳ•ᛉᚢ•ᛈᛏᛋᚢᛖ•ᚷᚦᛡᛚ•ᛖᛋᛠᛝᛉᛈᛉ•ᚾᛟ•ᛞᛟᛒ•ᚾᚹᚢᛁᛇᛚᛞ•ᛁ•ᚦᚣᚷ•ᛟᛈᛡ•ᛖᚪ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚠᛋᛉᛞ•ᛖᚷᚦᛠ•ᚾᛋ•ᛞᛟᛗᛖ•ᛗᚾᛉ•ᚹᛒᛠᛈᛟ•ᛗᛉᚫ•ᛄᚩᛞᚻᛡᚷᚠ•ᚣᛗ•ᛁᚷᛉᚻᚹ•ᚾ•ᛋᛗᚷᛠ•ᚣᛚᚱᛄᛗᛉᚣ•ᛇᚱᚢᛟ•ᚣᚦᚢᛟᚩ•ᚱᚢᚹ•ᛁᛒᚳ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛠᛏᛞ•ᛚᛖᛋᛄ•ᚳᛟ•ᚷᛞᛡ•ᚢᚹᛝᚻᚫᚢᛈ•ᛏᛈᚩᚣ•ᚾᛇᚦᛟᛏᛇᚳᚠ•ᛒᚪᚾ•ᛗᚦᛝ•ᛟᛠᚢᛁᚪ•ᚾᚻᛝᛉᚩ•ᛇᛁᛡᚠᛟᛒᚦᚠ•ᛋᛒ•ᚠᛞᛇ•ᚩᚦᛏ•7•ᚷ•ᛚᛄᛖᚫ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚣᛁᚫᚹᚻ•ᚫᛏ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛁᛉ•ᛉᚻᛞᚩᛠ•ᚫᛋᛝᛚᛝ•ᛖᚩᚻᛗᚩᛟᛒᚦ•ᚱᛚᛋ•ᚳᚻ•ᚪᛡᚾᛇᚱᛉᚦ•ᚣᛉᚻ•ᛡᚾᚢ•ᛗᛉᚹ•ᛖᛈᛖ•ᚩᚳᛈᚳᛞᚪᛉᚢᛗᛝᛟ•ᛋᚾᛟᛉ•ᚠᚱᚳᛒᚢᛄᚱᚫᛝ•ᛒᛋᛟᛠᛡᚪᛚ•ᛏᛟᚾᚫᛟᚪ•ᛁ•ᛡᛋᚳᛖ•ᚹᛒ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚾᛚᛝ•ᚦᚾᛁᛠ•ᛒᛡᚱᚠᛖᛁᚹ•ᚾᚠᛗᚢᚷᚾ•ᛄᛚᚳᚱ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛝᚣᛉᛋᚪᛟᚱᛉᚳ•ᛒᚫ•ᚠᚢᚪᛖᚪᚹ•ᛚᚾ•ᛄᛉ•ᚻᚦᛉ•ᛗᛚᚾᛖ•ᛏᛝᚦᚪᚩᚢᛗᚣ•ᚠᛝᚪ•ᚻᛡᛇᛡ•ᛚᛏᛁ•ᛇᛁ•ᚳᚢᚢᛖ•ᚳᛒ•ᚫᛇᚠᚦᚳᛚᚩᛉᛚᚩᛚ•ᚠᚳᛠ•ᚪᚠᛟᚫᚠ•ᚾᚳ•ᚢᛒᚱ•ᚾᛇᚩᛉ•ᛁᚳᛟ•ᛞᛉᛠᛝᚠᚱᛡᚳᛇ•ᛉᛟᛈᛗᛞᚳᚦᚹᛈ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛡᚻ•ᚾᚦᛇᛏᚹᛖᚢ•ᚫᛇᚦ•ᛝᛟᛏᚳᚷᛒᛠ•ᚪᚳᛒᚪᚩᚹᚫ•ᛉᚢ•ᚫᛖᛒ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛇᛏᚢᚩ•ᛟᛞᚠᚢᛋ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛡᛄᛗᚦᛠᛏᚪ•ᛒᚹᚣ•ᛏᛄᚻᚦᚫ•ᛚᚪᚱᚫᛟᚦᚩᚾᛟᛁᛖ•ᛡᚠᚷ•ᛋᚠᚦᛏ•ᛠᛡᛠᛁᚢᛡᛇᛝᛞ•ᛉᛏᚠᛒᚻᚢᛋᚳᚱᛇᚹ•ᛇᛈᛋᚢᛚᚪᛈᚢᚳᛖᚠᛞᛉ•ᚦᛠᛇᛝᚻ•ᚣᚱᛗ•ᛟᚾᛚ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛈᚹᛞᚱᛄ•ᚪᛝᛞ•ᛁᚦᛏᚷᚢᚹᚳᚻᛖᚩᚪᛖ•ᛉᚪᚢ•ᚳᛁ•ᚱᚳᚹ•ᛠᛇᛏ•ᚦᚳᚻᚢ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛡᚹᛟ•ᚷᛇᛈ•ᚢᛈᚦ•ᚷᚣᚢᚪᛗ•ᚹᚳᛖᛝᚱᛠᛞᛏᚻ•ᛄᛁᛈᚻᚠᛉᛝᛈᚾ•ᛒᚳᚪᚷᛋᛟ•ᛉᛠᛈᚪᚩᚷᚠᚳᛡᛄ•ᛠᚢᚠᛋᛚ•ᚣᛚ•ᚢᛒ•ᛉ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚱᚣᚾ•ᛁᛠ•ᛚᚹᛋ•ᚠᚦᚪᛠ•ᛈᚷ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛏᚷᛡᛟᛠᛡᛒ•ᛉᛄᛒ•ᛖᚾ•ᛞᚠᛠᛗ•ᚦᚪᛗᚠᚪ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚻᛡ•ᛗᛁᛏᛟ•ᚻᚣᚹᛏ•ᚠᛒᛁ•ᚫᛖ•ᛝᛒ•ᛚᛏᛠᛉ•ᛟᛋᚾᛉ•ᚹᛏᛠᛏ•ᛖᚢᛡᛖ•ᛉᚾᛇ•ᛟᚳᚾᚠᚩᚾᚠ•ᚳᚪ•ᚷᚱᚩ•ᛠᚦᚹᚣ•ᛒᛁ•ᛝᛇᛟ•ᚣ•ᚷᛗᚩ•ᛁᚷᛄ•ᚩᛇ•ᚢᛁᛉᛝᚪᚱᛉ•ᛏᛄᛞᛈ•ᚾᛝᚷᛏᚢ•ᛚᚷᚳᛏ•ᚢᛒᛇ•ᛈᚩᚣᚢᛏ•ᛡᚫᛏᚹᛏᛇ•ᛡᚫᚫ•ᚦᛏᛝ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛠᚳᛁᛉᚻᚦᚣ•ᚻᛚᚾᛋᚱᛡᚫᛚᚫ•ᛖᚷᚻ•ᛞᚾᚻᛠ•ᚠᚪᚹᛖᚠᛄ•ᛒᛇᚱᚹᛏᛉᚾᛠᛖᛁ•ᚠᚾᛡᚳ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛋᛟᚹ•ᛈᚷᛝᛟ•ᚷᚦᚠᛄᚷᚳ•ᛒᛁᛗᛚᛇᛠᚹ•ᚾᚫᚹᚷ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚩᚻᚪᛏᚾᛄ•ᚣᛝᛏᛡᛝ•ᚢ•ᚩᚠᚣ•ᛗᚢᛒ•ᛏᚠᛈ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚱᚩ•ᛉᚩᛝᛒ•ᛖᛏᚩᛉ•ᚣᛗᚠᛉ•ᛖᚩᚫᚷᚣᛚ•ᚩᛇ•ᚠᛋᚫᛇᛗᛡᛟᚹᚾᚩᚢᚹᛖᛁ•ᚾᚦᚫᛠᚪ•ᛠᛚ•ᚹ•ᛡᚩ•ᚢᚦᛗ•ᛝᛚᚪᚠᛝ•ᛚᚠᛚᚳᛒᚢᛝᛉ•ᚣᛡᚪᚷ•ᚹᛟᚪᚻᚹᚢ•ᛖᛠᚷ•ᛁᚪᛏᛄᛗ•ᛏᛖᛁ•ᚣᛡ•ᚦᚾᚠᚦ•ᚩᛈᚻᚪ•ᚻᛋᛠ•ᛡᛉᚪᚫ•ᚠᚣᛞᛠᛇᚠᚫ•ᛏᛗ•ᚳᛡᚷ•ᚱᚢᛞ•ᛄ•ᛋᛡᛇᚩ•ᛚᛟ•ᚦᚱᚫᛒᛚᚦ•ᛖᚪᚦᛗᛚ•ᚦᛉᚪᚱ•ᛟᛖᛒᛄᚱᛄᛖᛁᛈ•ᚪᛖᛠᚠᛄᚢ•ᛞᚹᚦᚣ•ᛉᚷᚩᚳᛡ•ᛇᛗᛞᚳᛏ•ᚻᛚᚦᛝᛖᛗᚱ•ᛒᚷᛞᛉᛗᛒᛉᚳᛝᚦᚣᛞᚫᛠ•ᛋᛏᛗᛏᚻᚹ•ᛇᚳᚪᛞ•ᛠᚢᛒᛉ•ᛡᛁᛡᛚ•ᚷᛋᚦᛞ•ᚠᚢᚩᛠ•ᛚᛋᚣᛏ•ᛋᚪᛞᚫᚹᛄᛞ•ᛋᛈᛋᛄ•ᚪᛖᛁᛇᛒᛟ•ᛏᛄ•ᚠᚩᛚᛞ•ᚾᚷᚳ•ᛚᚷᛗ•ᛠᚦᚢ•ᛟᚻᚾᛟᚣᛡ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛇᚻᚣᚪᛈ•ᚾᛋ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛞᚫᛠᚳᛉᛄ•ᚦᚹᛋᚱᚦᚫᚾ•ᛡᛚᚣᚫᛋᛖ•ᛟᚣᛝᛡ•ᚦᚣᚷᛇᚱ•ᛋᛠᛏ•ᛡᚳᛉ•ᛠᚷ•ᚳᛒᛋ•ᚹᚾᚻᛖᛝᛋ•ᚩᛡᛗᛉᛝ•ᛉᚦ•ᛠᛞᚳᛒᚷᛉᚹᛝᚢ•ᛉᛞᛈ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛉᛡᛈᛟ•ᚾᛡᚠᛡᚢᛋ•ᛉᚪᛖᚻᚱᚣᛠᛇ•ᛒᛟ•ᚪᛝᛡ•ᚳᚱᚳᛈᚩᛏ•ᚻᚣᚫᛁᛋᚩᚦᛚ•ᛟᛚ•ᛋᚪᚢᚪᛈᚻ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚠᚢᛚᛗ•ᚪᛠᚣᛟᚪ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛚᚢᛝᚾ•ᚳᚢ•ᛒᚾᛏᚠᛝ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛁᚢᛁᚢ•ᛟᚫᛄᚠᚫ•ᚢᚷᛉᛇᛈᛉ•ᚣᛠᛚᚪᛉ•ᛟᛉᛡᚦᚻᛠ•ᚾᚪᚳ•ᚢᚷᚾ•ᛈᛖᚾᚦᚩᚢᛁᛡᚱ•ᛏᛁᛒᛇᚳᚠᚷ•ᚩᚦᚪ•ᛁᛈᚻᛡᛒ•ᚹᛈᚻᚱᛞᛉᛏᚢ•ᚣᛒ•ᚠᛋᛉᚢ•ᛗᛁ•ᛡᚱ•ᛝᚢᚠᚦᛝ•ᛈᛟᛒ•ᚻᚷᚻᛡᛚ•ᚩᛞᚪᚳ•ᚦᛈᛞᛋᛡᚻᛇᛚ•ᚢᛏᛋᛞ•ᚦᚢᛞᛝ•ᛚᛉᛝ•ᛏᚩᛚ•ᚪᛚ•ᚣ•ᛟᛡᛉᚣ•ᛒᚻᚫᛄᛡᛁ•ᚱᚦᛚᚠ•ᛠᚾᛝ•ᛉᛗᛒᚩᛠᛈ•ᛖᛞᚪᚫᛏᚩᛠᛖᛠᛉᚳᛠᛏ•ᚩᛞᚳᛠᚾᚳᚦᛗ•ᛞ•ᚷᛁᚳᚹᛟ•ᚪᚢᛒᚳᚫ•ᚦᚱ•ᛋᚣᚪ•ᛏᚦᛒ•ᛝᚹᛋᚱᛁᛝ•ᛒᛁᚪᚫᛚ•ᛏᚱᛡᚫᚠᛞ•ᛝᛄᚩ•ᛡᛠᛉ•ᚪᛡᚻ•ᚱᛒᛁ•ᛞᛡᛄᚪᛈᚱᛋ•ᚢᛡ•ᚻᚷ•ᛚᛟᚠ•ᚻᚷᚫᛋ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛈᚹᚷᚷ•ᛗᛟᚪᚾᚱ•ᚩᛟᛞ•ᚷᛟᚠᛠ•ᛡᚷᚳ•ᛉᛠᚠᛚ•ᛒᚫᛈ•ᚩᛄᛈ•ᛄᛗᛠ•ᚾ•ᛉᚪ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛡᛖᛋᚷᚫᚦ•ᛄᚷᛉᚩᚦᛄᚳᚣ•ᚢᛄᚦᛄᚪᚾᛏᛒ•ᚳᛈᛡᛄᛋᚫ•ᛋᛗ•ᚻᛞᛠᛉᚢᛗ•ᛏᛠᛖᚣᚠ•ᛄᛏᛋᛗᛞᛟᛁᛝᚪᛉᛖᛈ•ᛚᛇᛞᚦ•ᚪᛋᛉ•ᚳᛒᚢᛟᚳᛒᛚᚾᛟᛝᛉᚩ•ᛖᚳ•ᛝᛟᚳᛁᛒᛈᚫ•ᚣᛖᛄᛝ•ᛞᚢᚱ•ᛉᛟᚩ•ᚠᚹᚩ•ᚣᛁᚠᚢᛇ•ᛚᛏᛈᛒᛗ•ᛇᛝ•ᚢᚳᚱᛡ•ᛖᚩᛁᚣᛄᛏᛡ•ᛖᚠᛇᚠᛚ•ᛁ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚣᚷᚠᛝᛡᛈᚷᛒ•ᛡᚩᚷᛡ•ᛟᚾᚹᛡᛈᛟ•ᚦᛈ•ᛟᚷᛚᚦ•ᛈᛞ•ᚦᛇᛒ•ᛡᚪᛒᚪ•ᚾᛗ•ᚳᚾᛖᛡᚹᛝᛏᚱ•ᛝᚫᛚᛟᛁᛇᚣ•ᛝᛡᚾᛏ•ᚱᛁ•ᛋᚪᛖ•ᛇᚢ•ᛝᛞᛄ•ᚠᚱᛠᛗᛠᚪ•ᚫᛈ•ᛏᚠ•ᛖᛏᚷᚾᚠᛁᚠ•ᚱᚻᚱᛇᛒ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚻᛈᛏ•ᛇᚱᛝᛡᛒᚹᛚᛏ•ᛗᛉᚦ•ᚾᛄᚳᚫ•ᚷᛈ•ᛋᛖᚩ•ᚢᛝᚩ•ᛏᛈᛁᚣᚾᚪ•ᛏᚹ•ᚠᛗᚾᛟᚾᚳᛒ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛄᛉᛡ•ᛟᚪᛁᚫᛝ•ᛒ•ᛉᛏᛄᛁᛋ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛠ•ᚳᛖᚱᚦᚣᚩᚣ•ᛈᚫᚷ•ᛡᛄᛁᚩ•ᚱᚦᛠ•ᛇᚦᚩᛉ•ᚾᚱᚾᚫᛁᛉ•ᛁ•ᛝᚣᚫᛡᚫᛗ•ᚹᛖ•ᛇᚷᚻᛖᛗ•ᚷᚢᛞᚹ•ᛄᚻ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛉᚱᚢᛄᚢᚾᛈ•ᛋᚣᛄᚫ•ᛈᚳᚣᚳᛒᛡ•ᚫᛟᚪᚠ•ᛏ•ᚷᚩᛇᛟ•ᛁᚱᛗ•ᛖᛉᛟ•ᛗᛇᚫᛟᚦ•ᚱ•ᛞᛁᚢᚦᚻᛗᛡᚾ•ᛁᚦᚻᛚ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛏᚳ•ᚪᚦ•ᚠᚪᚫᚣᚻᛠ•ᚦᚠᛋᚠᛝᚷᚱᛈ•ᛏᛄᛉᛟ•ᚷᛚᚻ•ᚩᚪᚦᛏᚳᛁ•ᚠᚣᚢᛁᚹ•ᛟᚪᚣᛁᛠᛄᚪ•ᛟᛝᚦ•ᛟᚠᚦᚾ•ᛇᚷ•ᛠᛚᛒᚠ•ᛠᚪᛄᛇᛠᛚ•ᚱᚷᛋ•ᚹᚩᛒᛁ•ᛠᚳ•ᛁᛞᛄ•ᛖᛗᚱ•ᚷᚪᚻᛠᛚᚷᚩ•ᛉᚻ•ᛡᛝ•ᛞᚱᚹᚩᛈᛡ•ᚣᚳᚦ•ᛁᛇᚢᛁ•ᛟᚦᚠᚳᚻ•ᚩᛁ•ᛝᚾᛁᛞ•ᛏ•ᚫᚱᛝᚫᛈ•ᛠᛞᛇᛉᚳᛠᚩᛟᛖ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛗᛈᛒᚦᛝᛋᚢᛡ•ᚻᛡᛏ•ᛉᛇᚷᚠᛡᛡᛟᚢ•ᛡᚦᚣᛞᚪᚫᛝᛒ•ᚳᚩᚷ•ᛏᛞᚦᛁ•ᚠᛒᛖ•ᚦᛟᚳ•ᚠᚻ•ᛞᚠᚣᛋᚾᛟ•ᛠᛇᛄ•ᛖᛉ•ᚩᛈᛠᛚᚪ•ᛟᚩᚾ•ᛄᛉᛋ•ᚣᚫᚷᛖᚩᛟᚢᚱᚹᚢ•ᛟᛡᛄᛇᚢᛞᛉ•ᛒᛇᚳ•ᛝᛚᛗᛠᛗ•ᚪᚱᛡᛗᛒᚩᚹ•ᛋᛖᚾᚻᚣ•ᛈ•ᛞᛚᛞ•ᛈᛏ•ᚪᛞᛚᛉ•ᛟᚱᚾᚹ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛠᚠᛁ•ᛟᚾᛒ•ᛇᛟᛖᛝᚳᚠᛏᛞᛏ•ᛇᚫ•ᛝᚢ•ᛠᛡᚫᛖᛟᛞᛝᛠ•ᚠᛗᛒᛚ•ᛏᚢ•ᛈᚱᚹᛟᛇᛉ•ᚳᛟᛈᛏ•ᚢᚠᚳᛞ•ᛄᛋᛞᛈᛚ•ᚠᛝᚱᛄᚣ•ᛞᛗᛖᚣ•ᚢᛖᛝᛠᚳᛞᛈᚩᛠ•ᛏᛒᚳ•ᚷᚾᚩᛟᚾᚠ•ᚩᛁᚠᚢᛋᚾ•ᛞᚹᛠᛇᛈ•ᚱᚩᚩᛄ•ᚪᛟ•ᛇᛠᛄᛁ•ᛟᛄᛞᚢᚳᛝᚩ•ᚱᛝᛋ•ᛄᛁᛈᛉᛖ•ᛞᛁᚾᛗᛗᚳ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛉᚩᛁᛄᛞᚳ•ᚢᚪᛇ•ᚦᛡᛇᚻᛠᚣ•ᛠᚻ•ᚠᚩ•ᛡᛠᛋᛟᚪ•ᚹ•ᚫᚻᚩᛄᚢᚱᚩᚣ•ᛏᚫᚪᛡᚷ•ᛄᛚᛄ•ᛝᛏᛖᛒᛚᛉᚻ•ᚱᚩᚫᛇᛈᛄᛠ•ᚳᛈᛚᚣᛈ•ᚪᛠᚻᚻᛋᚫ•ᚩᛝᚹ•ᛋᛞᚠᚳᛠ•ᚩᛇᚫᚪᚩᚹᛗᚪ•ᚣᚫᚷᚫᛄᚱᚹᛞ•ᚱ•ᚦᚷᚳᚹ•ᚾᚷᛡ•ᛚᛒᚳ•ᛄᚷᚹᚹ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚱᛁᚠᛏ•ᚠᛚ•ᛋᛄᛚᚪᛄᚱᛏ•ᛞᚷᚫᛠᚠᛉᛞ•ᚫᚷᚻᛏ•ᛗᚣᛈ•ᛏᛒᛟᛝ•ᛄᛋᚾ•ᛝᛁᚹ•ᚦ•ᛠᛝᛞᚾᛟᚷᚫ•ᛁᛗ•ᛝᛉᚱᛞᛋᛗ•ᚠᚫᚹ•ᛟᛋ•ᚦᛞᛞᛈᛝᛞᛡᚷᛒ•ᚪᛟ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚦᛡᛒ•ᚪᚹ•ᚾᛉᚫ•ᛚᛈᛁ•ᛒ•ᚠᚾᚠ•ᛡᚩᛏᛞᚾᛋᛖᚳᚻ•ᛖᚻ•ᚢᛟ•ᚪᛖᛗᛝ•ᛠᚫ•ᛈᚩᚪᛞ•ᚠᚫᚻ•ᚠᛏᚦᛄᛚᛄᛒ•ᛗᛇᛈ•ᛄᚢᛒ•ᚷᛁᛇ•ᛈᛉᚣ•ᛈᛟᚦᛞᚱᛠᚪᛡ•ᛝᛡᛒᛚᚻᚦᚫᛉ•ᛟᚫ•ᚪᛇ•ᛉᚳ•ᛠᚠᚫ•ᚢᚣᚦᛋ•ᚠᛝᚠᚱᚹ•ᛟᛒᛗᚷᛞᚾᛡ•ᛞᚪ•ᚻᚣᛇ•ᚱᛚ•ᛖᚣᛇᚻᛠᚩ•ᚢᚳᚱᚻ•ᛡᛟᛗᛠᛝᛄᚦ•ᛄᚢᛁᛇ•ᛄᛁ•ᛖᚷᛁ•ᚪᛇᛏ•ᛝᛡᚳᛚ•ᛇᚠᛗᚪ•ᚷᛚᛒᛋ•ᛉᛞᚫᛟᛋᛚ•ᚹᛏᛠᛗ•ᛚᚦᛗ•ᛝᚦ•ᚣᛈᚠ•ᚪᛞᛚᚪᛖᛚᚩ•ᚱᚷ•ᛚᚳᛇᛏᚷᚣᛟᛗ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚪᛁ•ᚷᛄᛒᛡᛗ•ᛞᛈᚪᚳᛠᚷᛋ•ᛏᛈ•ᚩᛋᛏᛗᚱᚣᛋᛉ•ᛁᛄᛚᛝᛚᛁ•ᛉᚢᛠᛗᛇᚢᛋᚻ•ᚳᛉᛄᚩ•ᚠᛄᚠ•ᛁᚣᛁᛟ•ᛏᚷᚱᚦ•ᛡᛒᛋᚳ•ᛇᚢᚷ•ᛚᚱ•ᛁᛗᚱ•ᛗᛝᚻᛈᚫ•ᛝᛋᚫ•ᛖᛈᛁ•ᛒᛇᚹᚫᚢᛄᚳᛒ•ᚦᛋᚹᚦᚫ•ᛡᛟᚷᛚ•ᛞᛚᚢᛟᛡ•ᚱᛞᚱᛒᛄᚳᚢᛠ•ᚩᛉᛉ•ᛝᛡᛄ•ᛁᚫᛟ•ᛖᛗᚹ•ᛖᛉᚦᛗᚪᛋᛉ•ᛞᚦ•ᛡᚢ•ᛉᛗᚫᛋᚳᛖ•ᚳᚫᛠ•ᛞᚳᚷ•ᚩᛁᛇ•ᚾᛟᚷᚣᚳᚦᚳᚦ•ᛗᚣ•ᛈᚪᛒᛈ•ᚻᚢᚻᚾᛏᚫᛒᛇᚩᛁᛈ•ᚫᚩ'ᚣ•ᛡᚣᛗᚷ•ᚠᚱᛡᛚᛏ•ᛖᛟᚩᛈᛚᚩᚷᛁᛟᛠ•ᛞᛖᚳᛗᛁᚣ•ᛈᛚ•ᛁᚹᛋᛄᚹ•ᛟᛡᚪ•ᚦᛖᚩᛄᚷᛋᛝᚣᛗᛟᚻ•ᛗᚠᚦᛉᚦᚫᛋᛈᚣᚩᚠ•ᛈᛟᛋᛖᚫᛇᛗᛚᛈᚾ•ᛡᚠᚳᚾᚩᛄᛋᛡ•ᚫᛄᚦᚪᛠ•ᛈᚻᛋᛟ•ᛗᚹ•ᚱᚣᛁᚢ•ᛉᚹᛋᚱ•ᛞᛈᚦᛈᚩ•ᛞᛄᚩ•ᚢᛈᛖᚪᚫᛉᚫ•ᛏᚱᛟᛏᛒ•ᛠ•ᚫᚳᚾ•ᛖᛝᚦᛄᛄᚠᛚᚾᚩᛒ•ᛉᚷ•ᚪᚩᛚ•ᚪᚢ•ᛞᚻᚳᚹᛚᛡᛞᛇ•ᛟᚩᛡᛚᚳ•ᛡᚳᛉ•ᛝᛠᛝᚷᛝᛞᛄᛏ•ᛠᛈ•ᚹᛈᛗ•ᛈᚱ•ᚫᛏᛖᚢᛝᚫᛡ•ᚾᛁᛠᚻᚦᚣᛠ•ᚫ•ᚩᛉᛋᚩ•ᛄᚠᛏᚷ•ᚹᛁᚪᛁᚩᛁ•ᛝᛠ•ᚾ•ᚷᛗᚹᚦᛖ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚷᛟᚪᚹᛞᚻᚢ•ᛡᚹ•ᚣᚷᛉᛒᚪᚾᛝᛡᛄᛡ•ᚠᚷᛈᚦᚠᚦ•ᛁᛈᚪᛝᛋᛞᛟᚩᛝᛗ•ᛁᚷ•ᛄᚷ•ᚳᚩᚦᛖᚦᛄ•ᚣᚠ•ᚦᚳᛄᛡᛖᚢ•ᛉᛄᚳᚻᛄᚱᛄ•ᚪᚻᚾᚦ•ᛚᚷ•ᚱᚦ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛒᚪᚩᛖᚢᛡᛄᚹᛏᚱᚹᛟ•ᚦᚳᛗᚦᚠᚫᚻ•ᛡᚠᛠᚣᚪᚦᛚᛏᛒᚢᛝ•ᛖᛋᛗᚱ•ᚪᚹᛒ•ᚹᛒᛗᚱᚾᛗᚻᛗᛁᚾᚪᛞ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛡᛖᚩ•ᚾᚹᛡ•ᚢᛄᚦᛠ•ᛚᚳᚷᛚᛇ•ᛟᛠᛠᚪ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛇᛉᚣᚪ•ᚷᛏᚩ•ᛖᚹᛒᛈᚷᛝᛒ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛡᚦᚠᛋᚾ•ᛒᚦᚠ•ᛇᛝᛠ•ᚠᚾᛉ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚢᚪ•ᚹᛝᚷᛉᛞᚷ•ᛁᛒᛁ•ᛇᛏᛒᛁᚣ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛠᚷᛋᚫᛈᚹᛗᛠ•ᛇᛄᛇ•ᚹᚻᛁ•ᚷᛠᛒᚢᚣᚻᚣ•ᛝᚹᚢᚱᛋ•ᚩᛡᚠᛡᛠ•ᛞᛟᚦᛗᚳᚾᛉ•ᛞᚦᛖᚱᛇᚳ•ᚪᛄᛋᛟ•ᚢᚹᚱᛏ•ᛋᛖᛋᛏ•ᚣᚱᛠᚫᚾᛞ•ᛈᛒᛡᛋᚢᛞᛖᚣᚦ•ᛚᚹᛟᛋ•ᚷᛚᛄ•ᚫᛖᚩᚳᚦᚹᛗ•ᚢᚩᚷ•ᚠᚪᚩᛡᛝᛒᛠᚦᚳᚪ•ᚱᛡᛏ•ᛟᚹᚠᚣᛝᚢᚣᛁ•ᛚᛏᚫᚫ•ᚪ•ᚱᛈᚠᛗᚹᚩᛞ•ᛠᛒᛈ•ᛝᛟ•ᚾᚷᛗ•ᛡᛖᚩ•ᚾᛚᛉᛝ•ᛁᛡᚫᛗ•ᚻᛖᚹᛗ•ᛝᛈᛇᛗᛡᛄ•ᚫᚩᛡ•ᚠᚣᛉᛟᚫᚦ•ᚫᛒᚩ•ᚪᚦᛄᚱᛄᚾᚦ•ᛡᚠᚪᛏᚾᚻ•ᚷᚢ•ᛞ•ᚳᚦᚢᚱᚢᛟ•ᛞᚻᚱ•ᚷᚹᛏᛈᛖᚠ•ᚪᚻᛠᚦᛞᚱᚠ•ᛖᛄᚫ•ᚾᚳᚻᚹ•ᛇᛡᛈᛠᚹ•ᛗᛚ•ᚹᛟᚹᛠ•ᚪᚾᚪ•ᚳᚪ•ᚷᛚᚦᛒᚩᚹᚢ•ᚷᛚᚠᛋᚻ•ᚾᛉᛝᛗ•ᛖᚦᚢᛝᛡ•ᛈᚣᚢ•ᛉᚷᚷ•ᚹᛞᛁᛋ•ᚦᛡᛡᛈᚳᚪᚩ•ᚢᛗᚢᛉᚩᚣᚻᛏ•ᚩᚫᛗᚢ•ᚩᚾᛏᛠᛒᛟᛒᚠᛁᛈ•ᛚᛋᛝᚫᚳ•ᚫᛟᛏ•ᚢᚩᛉᚾᛡᛋᚠᛖ•ᛉᚱ•ᛗᚩᚩᚫ•ᚠᚢᚦᛖᛞᚾᚣ•ᛡᛋ•ᛋᚱᛚᛟ•ᚢᚻ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚢᚾᛈ•ᛁᚻ•ᛖᛉ•ᚦᛞᛗ•ᛈᛟᚠ•ᛈᚠᛝᚫᛝᛋ•ᛟᛄᚹ•ᛠᛒᚣ•ᛟᚹᛞ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚠᚣᛄᛁᛏᛉᛚ•ᚩᚦᛝ•ᚠᚪᛋᛡᛁᚻᛒᚱ•ᚪᚢᚣ•ᚫᚢ•ᛟᛠᚪᚣ•ᛖᛟᚫ•ᛖᛈᚠᛒ•ᛈᛄᛁ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛋᛝᛒ•ᚱᚦᚳᛇ•ᛚᛁᚢᛈᛏᚳᛒᛉ•ᛖᚪᚣᚠᛗᚳᚣᚱ•ᚻᚹᛏᚾᛡᛉᚫᚦᛟ•ᚳᚹ•ᛠᚠ•ᛏᛠ•ᛝᚩᚻ•ᛡᛠᛒᛋᚻᛟ•ᚫᛁ•ᛠᛏᛁᛋ•ᛏᚫᚻᚱ•ᚻᛄᛋᛡᚹᚾᚾᛡᚹᛚ•ᚢᛖ•ᛏ•ᚱᛝᚳᚣ•ᚪᛉᛇᛝᛋᛖᛇᛁᚻᚾ•ᚷ•ᚹᛉᚳᛉᚣ•ᛋᛈᚳᛟᚱ•ᛒᚣᛄᛝᛖᛁ•ᚾᚷᚪ•ᚣᚷ•ᛚᛒ•ᚢᛄᚩ•ᛝᛉᛉᚪᛖ•ᛒᚦᛉᛡᚱ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛏᚷᚹᛄᛋᛁᚠ•ᛠᛁᛡᚦᛝᚾᛖᚾᚠᚩᛗᛖᚣᚪ•ᚳᛖᚳᚹᚪᚫᚹ•ᛇᚢᚦᚻᛉᚢᚾ•ᛠᛚᚢᚾᚦᛈᛋᚢᛈᚱ•ᛞᚫᛟᚱᛡᚫᚪᚢ•ᚢᛗᛚᚦᛠ•ᛚᛝᛈᚣ•ᚩᛋᛟᚪᚱᛗᚦᛟᛈ•ᛚᛋ•ᛏᛁᚠᛋᛖᚹᛝ•ᛗᛞᚩ•ᛠᚫᛡᛒᛏᚩᛋ•ᛖᛏᚪᚠ•ᚫᛒ•ᛚᚾ•ᛋᚪᛉᛟ•ᚾᛚᚹᛖ•ᚩᛚᛁᛄᛏ•ᛒᚪᚠᛉᛏ•ᚩᛟᛄ•ᚾᚷᛋ•ᚷᛚᚷᛠ•ᛒᚷᛖᚩᚪᚩᛖᛞ•ᚷᛇᛗ•ᚳᚱᚷ•ᛈᛞᚩᚠᚹᛇ•ᛠᛞᚣᛝ•ᚾᛁᚠᛈᛚ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛖᛟ•ᚢᚳᛗ•ᛚᚫᛏᛉᛄᚱᛉ•ᛁᛠᚷᛚ•ᚷᚳᛋᚩᛝ•ᚫᚦ•ᛗᚻᛟᚠ•ᚱᛋᚳᚦ•ᚣᚩ•ᛒᛁᚫᚻᛖᚢᛏᛚᛚ•ᛇᚷᛟᚣ•ᛒᚾᚦᚻ•ᛠᛖᛄᛒᚾᛁᛚᛠᚱ•ᛄᚠᚳᛋᛝᚳᛈ•ᚷᚻᛋᛗ•ᛇᛞᛇ•ᚣ•ᛡᛖᛏᛠᚢᛡ•ᚩᚾᛠᚩ•ᛄᚣᛇᛉᛠᚪᛡ•ᚾᛞᛝᚻ•ᛈᛠᚻᛡᚢ•ᛝᚻᚦᛈ•ᛉᚢ•ᛠᚣᛈᛟᚦᛋᚣᛈ•ᚠᛏ•ᛒᛁᛟᚪᚷᛚ•ᛠᚻ•ᛝᛁᛡᛚᛝᚾᛞᚪᛈᚷ•ᚾᛏᚦᛋᛒ•ᛋᛋᛠ•ᚷᚳ•ᛠᛗᚢ•ᛖᛉᛒᚷᚫᚠᚩᛁᛉ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚠᚪ•ᛠᚱᛇ•ᚩᛁᛞᛋᛚᚦᛖᛒᛇ•ᛟᚷᚣᚷᚾᚷ•ᚦᚠᚳᛗ•ᚩᛖᛖ•ᚩᚠᛒᚻᛝ•ᚳᛁᛄᚪᚾᚩᚪ•ᛈᚻᚱᛗ•ᚱᛗᛟ•ᚦᚷᛄ•ᛒᚱᚦᚪᛠ•ᛉᛖᛡᛞᚦ•ᚱᛝᛄᛒ•ᚾᛏᚣ•ᛏᛋᛒᚾᚫ•ᚢᛖᛁᚩᛡ•ᛄᛇᚢᚦᛚᚳᛖ•ᛚᛁ•ᛒᚢᚠᚪᚱᛠ•ᛗᛒ•ᛞᛉᛗ•ᚢᛠᛏᚣ•ᚪᛄᛈᚢᛈᛠᚣᚷ•ᛗᛡᛗᚢᚪᛗᛝ•ᚣᛡ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚪᛖᛏ•ᛖᛋᚪᛟ•ᚳᚻᛁᛋᚠᛁᚾ•ᛈᛟᛝ•ᛇᚦᚣᛏᚫᛉ•ᛖᛟᛏ•ᛞᛡᛚᛖᛈᛏᚪ•ᛏᚠᚱᚾ•ᚪᛠᚱ•ᛠᚳ•ᚾᚻᚹᛒᛇᛋ•ᛁᚻᚣᛋᚹᚩᛉᚹ•ᚩᛝᚢ•ᚻᛝᛟ•ᛏᛚᚠ•ᛄᚷᛏᛝᛄᛝ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛗᛈᚣ•ᛚᛋᚩᚪᚫᚻᛚᛖᛇᛁᛗᛚ•ᛚᛋᚳᛈ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚾᚻᚷᚢᛡᚻᚢ•ᛒᚠ•ᛞᛄᚢ•ᛒᛖᛁ•ᚫᚠ•ᛈ•ᚫᛈᚦ•ᚱᛗᛚᚳ•ᛒᚷᚣᛗᛠᛒᚫ•ᚾᚦ•ᛗᚠᛡᛠᚳᛒᚷᚫᚠ•ᛖᛄᚱᚩ•ᛈᛒ•ᚠᛒᚩ•ᛇᚱᛠᚱ•ᛠᚷᛖᛚ•ᛇᚱᚾᛋᚩᚩᚳᚪᛖᚣᛖᛖ•ᛏᚱ•ᚢᚣ•ᛟᛄᛉ•ᛠᚷᛝ•ᚣᛏᛝᚾ•ᚪᛏᛋ•ᛝᚪᛄ•ᚠᛚᛋᚢ•ᚹᛠᛈᛁᛏ•ᛁᚾ•ᚱᚱᛝᛗ•ᚣᛗᚠᛁᚫᛁᚪ•ᚢᛟᛒᚹ•ᛗᛁᚻᚣᚹᛞᛚ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛟᛏᛞ•ᛟᚳᛒ•ᛡᛒ•ᚪᛏ•ᚹᛏᛈ•ᚹᛠᚩᚱᚩᛖ•ᚣᛚᛋ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚢᛡᚱᚠᛄᛇᚱᛡᚦᛖᚢᛏ•ᛝᚫ•ᚾᚪᛠᚩᚪᚾᚪᚦᚷᚩ•ᚫᛉᛒᛏᛖᛠᛗᚷᚱᛗ•ᚣᛝᚠᛒ•ᛞᛟᛞᚪ•ᛠᚱᚳᛁᛈᛞᚠᛗᛝᚻ•ᛋᚩ•ᛞᛈᛉᚾ•ᛟᚱᛡᚾᚳᚳᛏ•ᚾᛈᚠᛈᚳ•ᛄᚦᛒᛁᚹ•ᛞᚹᛝᛠᛡᚹᛚ•ᚹᛄᚾᚪᛟ•ᛏᛞᛉᚣᛖᚱᛞ•ᚱᛏᛇᛁᚳᛈ•ᛝ•ᚦᛟᚷᛄᚦ•ᚣᛋ•ᛠᚻ•ᚠᛒᛚ•ᛁᚫᛚᛞᛉᚪ•ᛁᚹᚷ•ᛒᚩᚹᚾᛠ•ᛋᛖᛗᛒᛋ•ᚳᚹᚦᛟᚠᚻᚫ•ᛞᚢᛁᛒᛞ•ᛇᛝᛈᚠᛁ•ᛟᚢᚣᛏ•ᚻᚱᛖᚾᚳᛈᛡᛈᛞᛄ•ᛁᛏᛗᛋᚫᛉᚩᚣ•ᚪᛄᛗᛡᛖ•ᛇᛄᚠᛗᚱ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛞᛟᚪᛒᛞᚻ•ᚾᛈᚪ•ᛇᚱᚻᚾᛝᛠᚠᚾᚠ•ᚩᛗᛋᚾ•ᛠᚪᛁᚢᛚ•ᚪᚫ•ᛄᛉᛡᚠ•ᛁᛖᛈᛠᚻ•ᚠᛇᚩᚹ•ᛠᛄᛇᛁᛠᚫ•ᛄᛒ•ᛋ•ᚠᛖᚷ•ᛋᛁ•ᛟᛗᛒᛁᛝᛏᚪᚢᛁᚦ•ᚩᛝᛗᚠ•ᚹᛟᛒᛟᛡ•ᚠᚣᛝᚩᛠ•ᚳᛚᛈᚱ•ᛞᛄᚩᛝᛄ•ᚪᛖᛗᛈᚾ•ᚠᛠᚷᛞᛒ•ᚩᛉᚷᚾᚣᚷ•ᛠᛈᛄᛞᚾᛟᚩᚢᚾᚹᛗ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛄ•ᚢᚷᛠ•ᛗ•ᛇᚪ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚻᚦᛡ•ᛝᛈᛞᛒ•ᚳᛉᚳ•ᛠᛉ•ᛟᚣ•ᛒᚦᛁᛄᛚᛡᛝᛡ•ᚹᛄᚫ•ᛋᛗᚪᛡᛠᛇᛝᛏ•ᚦᛞᚷ•ᚢᛏᛚᛏᚣ•ᚢᛝ•ᚷᛟᚪᛏ•ᛄᚦᚣ•ᚫᚻᚪ•ᛒᛝ•ᚦᚢᚱᚪᚾᛞ•ᛁᛝᚫ•ᛚᚫᚷ•ᚹᛁᛒᚣ•ᚾᚫᚠ•ᛚᛋᛒ•ᛈᛟᚪᛟᛞᚷᛟᚣᛉᚷᛚ•ᛋᛠᛁ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚳᛟᛁᚦᛈᚹᛉ•ᛖᚢ•ᛟᛄᛝᛋᚢᛝ•ᚳᛡᛠ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛚᛇ•ᛚᚷᚢᛁᛏᛒᛋ•ᛞᛁ•ᚠᚠᚷᚠ•ᚦᛄᚳ•ᚫᛟ•ᛁᛗᛡᛁᛇᚦ•ᚩ•ᚢᛈᛒ•ᚻᛋ•ᛄᚣᛄᛖ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛒᛇᛇᚱ•ᚹᛄᛏᛡ•ᚳᚪᚫ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚩᛈᚱ•ᛡᚾᛗᛁᛝ•ᚻᚹᚦ•ᛡᚦᚻᚦ•ᛉᚫᚫᛋᚳᛡᚾᛇ•ᛟᛉᚢ•ᚱᛄᛖ•ᛚᚾᛞ•ᛗ•ᛏᚱᛟᚦ•ᛁᛝᛡᛒ•ᚳᚩᚹᛟ•ᛏᛗᛋᚱᚷ•ᚱᛚᛞᛚ•ᚩᚣ•ᛞᚳᚪᛖᛞᚠᚳ•ᛇᛖᛉᛚᚫ•ᛖᚩᛁᛋ•ᛡᛁᛟᛋᚪᛒᛗ•ᛗᚣᚹᛄ•ᛖᚫᛝᛚ•ᛄᚱᛇ•ᛈᛚᚩᚻ•ᚪᛞ•ᛡᛄ•ᛞᚠᚹᛞᛄᚳ•ᚾᚦᛉ•ᛄᚻ•ᚷᛚ•ᚠᛖᚦ•ᛇᚻ•ᛝᛖᛒᛚᛞᛁᛗᚠ•ᚹᛒᛗᛟᛁᛖᛁᛠ•ᛈᚻᛝᛖᛞᛟᚩᚻᛄ•ᚹᚩᚾᛄᛈᛗ•ᛖᚳ•ᛖᛇ•ᚷᚻᛗᛞᚪᛈᛖ•ᛗ•ᛉᚫᛒᛇᚱ•ᛖᚣᛟᚣ•ᚱᛠᛈᚢᛠ•ᚣᛖᚪᚻ•ᚩᛉᛠᚢᚻᛡᛟ•ᚷᚫᚩᛒᛉ•ᚫᚱᛞᛋᚩᚱ•ᚷᛠ•ᛉᚻᛁ•ᚷᚳᛞᛠᛡᚳ•ᛄᛠᛉᛇᚻᛋᚹ•ᛝᛡᚷᛖᛡᚣ•ᛠᚩᚷ•ᚱᚦᚠᛟᚩᚦ•ᚦᛁᛏᚱ•ᛇᛉᛇ•ᚢᚷᛠ•ᛟᛏ•ᚩᚠᛚ•ᛟᛝᛈ•ᚱᛡᚪᚩᛏ•ᚩᛠᚷᚫᛗ•ᛈᛋᚱ•ᛖᚦᚠ•ᛞᚹᚾᛚ•ᛝᚩᛇᛄ•ᚳᛚᚢᚹᛏ•ᚩᛖᛏᚠᚪᛚ•ᛟᛇᛟ•ᛠᚱᛇ•ᚢᚪᚦᛈᛟᛡᛉ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛡᛒᚱᛒᚠᚢᛚᚢᛟ•ᛒᛇᛒ•ᛉᚦᚹ•ᛝᚣᛖ•ᚳᚫᚣᛟ•ᚹᛁᛝᚫᛏ•ᚫᛇᛈᛡᛟᚠ•ᛚ•ᛝᚠᛡ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛞᚪᛚᛈ•ᛋᛁ•ᚢᚣᚪᛚᛠᛝᚹ•ᚪᛏᛈᚳᚣ•ᛝᚫᚻᛗᛞᚷᛚ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛠᛉᛒ•ᛇᛡᛋᛖ•ᚣᛁᛚ•ᚣᛠᚣ•ᚻ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚣᛉᚾᛏᚫᛉᛋᚦᚪᚹᛗ•ᚪᚱ•ᚪᚩᚻ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛗᛖᚫᛞᛠᛁᛗ•ᛒᛟᚾᚳᚩᚱᛉ•ᛋᚹᚫ•ᚻᛖ•ᛋᚠᚾ•ᚢᚦᛟᚷᛖᚪᛟᛇᛇ•ᚦᚳᛒᛝᛏᛉᛡᛞ•ᛋᛡ•ᚩᚠ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛈᛖᛞᛋᛁ•ᛚᛁᚻᚾᛝᚱᚻᛈ•ᛇᚢᚫᛞ•ᛚᚻᛉᚳᛈ•ᛁᛗᛉᚳ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛄᚫᚾᛞᛋ•ᛏᛚᛡᚩᛋᛗ•ᛚᛞᚾ•ᛈᚫᛏᚷᛈ•ᚫᚦᛄᛗ•ᛒᚻᚩᚻᛁᚷᚻᚳ•ᛚᚹᛋᚱᛇᛗᛏ•ᛄᚳᛁ•ᛠᚦᛞ•ᛏᛚ•ᚱᛖᛠᛒᚪ•ᛒᚠᛒ•ᛁᛒᛡᛇᛏᚣ•ᛏᛖᚣᚳᚱᛋᚠ•ᛁᚦᚪᛉ•ᚪᚣᚫᛠ•ᛄ•ᛈᛗ•ᚠᛋ•ᚪᛒᚱ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛉᚣᚻ•ᚦᚩ•ᛇᛞᚢ•ᚠᛁ•ᚻᚩᚫᚠᚣᚷᚱᚪᛄ•ᛏᛉᛇ•ᛖᛠᛞ•ᛏᚠᚢᛝ•ᚫᛄᛖᛈᚳᛒᚦᚢᛝ•ᛡᛒᚹᚱ•ᛖᚾᛈᛇᚣᛇ•ᛉᚱᚹ•ᛒᛡᛞ•ᛖᚱᚩᚻᚣᛠᛈᚦ•ᛗᛁᚷᛚ•ᚹᛉᚫ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚠᛞᚾ•ᛄᛟ•ᚻᛚᛡ•ᛗᛖᚷ•ᛟᛁᛡ•ᚻᛟᚱᛇᚹᚣᚠ•ᛈ•ᛄᚷᚦ•ᚪᛒᛝ•ᛈᛒᚪᛖ•ᚢᚹᚻᚩᛒᛋᛉ•ᚹᛞ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚦᛇᚱᛖ•ᛄᚾᛞᛝᚹᚪ•ᚻᛖᚹ•ᛟᛡᛄᛡᛟᛝᛄᛉᛚᛄ•ᛞᛉᛟᛈ•ᚱᚪᛁᛏᚷᛉᛝᛇ•ᛠᛗᚩᛚ•ᚦᚫᚹ•ᚫᚢᛈᛡᚳ•ᚹᛝᚻᚹᛒᛗᛋᛟᛖᛁᛡ•ᛟᚹᚦᚻᛒ•ᛡᚱᛏᚦᚠ•ᚠᚩᚦ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚻᚩᛗᛖᛉᚹᛞᛋᛚᚠᛞ•ᛝᛒᛇᛡᛚᚪ•ᚹᛞᚾᚫᛉᛏᚣᛗᚷ•ᚦᚹᛉᛡᚦ•ᚹᛒᛋᚱᛉᛡᛉᚪ•ᚢᛒᚻᛠ•ᚹᛝᚢᚻᛇᛝᛡᛠᛄ•ᛋᛈᚦᛏ•ᛟᛝᚩᛗᛒᚢᛞᛋ•ᛒᛄ•ᛠᚱᛟ•ᛖᚾ•ᚾᚹᚷᚢᛚᚪᚩᚣ•ᚢᛏᚠᛄᛏ•ᚪᚷᛒᛇ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛞᛇ•ᛉᚳᚠᛁᚪᚹᚻᚷ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛇᛟ•ᚠᛏᛖᛟᛠᚪᛡᛋᚷ•ᚣᛠᚾᚦᚫᚱ•ᚩᛡᛗ•ᚹᛉᛗ•ᚣᛞᛒᛏᚱ•ᚢᛄᚻ•ᚫᛟ•ᛡᛝᚹᚻᛋᚠᛡ•ᛚᚦᛏ•ᛁᚹᛏ•ᚩᚢᚾᚹᛗᛚ•ᛋᚦᛠᚹᛄ•ᚪᛄᚫᚷᚣᛗᚹᛞ•ᛈᛡ•ᛖᛄᚹ•ᛖᚢ•ᚻᚹ•ᛝᛁ•ᛋᚫᚷ•ᛄᛚ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛝᚦᛇ•ᛁᚠᚳᛟᛇ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛞᛒᚣᛡᚣᚢ•ᚣᚾᚦᚱᛖᛗᛁ•ᛇᛞᚱᚹ•ᛉᛒᚻ•ᚳᛄᛡᚪ•ᚾᚹ•ᚾᛗ•ᚠᛇᛁ•ᛇᚪ•ᚩᛋᛒᛟ•ᛏᛄ•ᛈ•ᛖᛈᛄᚩᚹᚢᛠᛝᚹ•ᛗᚳᚩᛏᛏᚠᚢᛄ•ᛞᛠᛉᚩ•ᛉᚦᚷᛞ•ᛒᚩᛏᛚᛇᛁᛒᛡᚪ•ᛖᚠᛠᚢᛖ•ᛈᛋᚹᛞᛞ•ᛋᛡ•ᚹᚦᛞᛋ•ᛝᛄ•ᛚᚷᚢᛡ•ᚾᛉᚠ•ᚱᚪᚣᛗᚠᚦᚻ•ᚱᚪᚱ•ᚫᚪᚷᛟᛞ•ᛒᛗᛒ•ᚾᚻ•ᛇᛞ•ᚻᛗᛚᛁ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛠᚾᛁ•ᚫᛖᚢ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛏᚦᛇᛋᛈᚻ•ᚻᛇᚳᛠᚫ•ᛞᛚᛋᛝ•ᛁᚹ•ᚪᚳᚩᛏᛇᛝᚷ•ᚳᚦᛋᛠᚠᚢᛝᛚᚻ•ᚹᚩᛇᚪᛈᚷ•ᛇᛗᛚᛄᛋᛏ•ᛚᚳᛈ•ᚾᛋᛝ•ᚳᚪᚳ•ᚾᛉ•ᚾᚢᛉᚫᛗᛏᛞᛏᚫ•ᛟᛗᛋᛉ•ᛏᚣᛉ•ᛇᛠᚷ•ᚻᛒᚾᚷᛇᚢᛟ•ᛄᚦᛉᚩ•ᚾᚪ•ᛞ•ᚩᛈ•ᛠᛚᛋᛏ•ᛒᚷᛁᚢᛟᛖᛁ•ᛄᚦᛖᚻᚹ•ᛄᚫᛄᚾᚻᛉᚹ•ᛒᚪᛋ•ᚠᚱᚱᛁᛉᚢᚦᚻ•ᚢᛗᚪ•ᛞᛝᛠᚪ•ᚫᛉᛖᚾᚹ•ᛟ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛝᛞᚾ•ᛈᚫᚳᛡ•ᛈᚠᛉᚩ•ᛒᚷᛗᚫ•ᛚᚻᛞᚣᛖᛉᛒ•ᛄᚹᛇ•ᛈᚩᛁᚦᚠ•ᚷᚾᛈᛞᛝᛏᛖᚪ•ᛄᛋᛠ•ᛈᛝᚢ•ᛒᚷᚳᛉ•ᚪᚢᛈᛚ•ᛄᚱᚷᚣᚪ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚪᚠ•ᛗᛝᚣᚳᛟ•ᚹᚣᚷᛈ•ᛗᛖᚩᚹᚢ•ᛟᛞᛋᚱ•ᚣᛞᛋᚳᛡᛉ•ᚻᚦᚹᛚᛞᛠᚩᛞᛠᚢᛟᛖ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛠᚹ•ᛉᚻᛡᚹᛞ•ᚪᛗ•ᚠᚦᛈ•ᛝᛏᚳᚪ•ᛠᚣᚷ•ᚳᚦᛖᚾᚢᛁᚫᛁᚢᛡ•ᚹᛚᚳ•ᚻᛈ•ᛞᛄᚳ•ᛗᛒ•ᛗᚪᛄ•ᚩᚪᛞᛁ•ᚩᚱᛟᚠᛖᚣᛟᛁ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛇᛟ•ᛁᛈᚣᛚᚪᛡ•ᚳᛏᛠᛋᛖᛒᛝ•ᚫᛟᚫᛞᛖᛞᚣᛡ•ᛠᚪᛖᚦᛚᚫ•ᚳᛋᚪᚩᚷᚹᛚ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛈᛖ'ᛏ•ᛄᛉᛝᛚ•ᛏᛉᚩᚣᛝᚠᚩᚣ•ᛁᚻ•ᛟᚫᚷᛄᛝᛡᚾᛗᚣᛟᛡ•ᛝᚷᛖᛉ•ᛟᛉᛈᛚᛋᛉᛠ•ᛚᛡ•ᚱᚪᛞ•ᛠᚷ•ᚱ•ᚳᛇᚻ•ᛗᚪᛟᚷ•ᛞᚪᛋᛡᚻ•ᛈᚷᛖᚳᛟᚱᛟᚢ•ᛁᚫᛟᚦ•ᛄᚱᛡ•ᚱᛖᚦᚣᛏᛝᛡᚩᛒ•ᛏᚦᚳ•ᛉᚳ•ᛋᚪᚫ•ᛗᚠᛄᚱᛖ•ᛡᛇᛁᛇᛟᛉᚳᚹᚪᛖ•ᛋᚢᛉ•ᛋᛟᛚ•ᛄᚾ•ᛈᛇᛒ•ᚦᚦ•ᛁᚫᛚᛋᛝᛄᛄᛡ•ᛟᚻᛇᚢᛚ•ᛁᚱ•ᛡᚻᛚᛏᚹᛉᛇ•ᚱᛏᛠ•ᛁᚫᛚᛗ•ᛁᚱᚷᛏᛠ•ᛇᛟᚻᛟᚳᛋᛏᚾᚩ•ᛁᚱᚷ•ᚹ•ᛞᚢᚣᛚᛁᛗᛒᚢ•ᛚᚱ•ᛏᛁᚢ•ᚷᚳᚠᛇ•ᛚᛇᚣᛏ•ᛏᚫᚢ•ᚫᛠᛇᚣᚾ•ᚢᚹᛝᚻ•ᚷᚣᚱ•ᚩᛁ•ᛚᚾᛉ•ᚾᚩᛈ•ᚠᛠᚫᚫᚩ•ᛉᚾᛋᛟᚫᛚ•ᚾᚫ•ᚦᚢᛠᚣᚫ•ᛈᛁᛇᚢᚱᛄ•ᛈᛟᛄᚪᛝᛈᚦᛈᚪᛝ•ᚣᛗᛟ•ᛉᛒᚢᛏᛇᛗᛈᚫᚣ•ᛉᚫᚣᚱᚫᚣᚠᚠᛗᛡ•ᛉᛖ•ᚱᚢᛏᚷᚢᚣᚱ•ᛡᚢᚩᛇᛁ•ᛄᚠᛈᛄᛞ•ᛁᚦᚩᚻᛡᚷᚻ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="1ᛚᚦᛇᛟ•ᚪᚫᛠ•ᛗᛉᚻᚳᛉᚪᛏᚦ•ᚫᛉ•ᚩᛋᚳᛞᛏ•ᚣᚹᚾ•ᛟᛏᛉ•ᚹᛁᛟᛄᚠᛁᚩ•ᛁᚱᛋ•ᛉᚾᛗᚪᛡ•ᚱᛈᛋᛞ•ᛁᛟ•ᚻᛖᛏᚢᚹ•ᛠᛟᛞᛟᛄᛁᛝᛡ•ᛄᚱᛞᛗᛒ•ᚩᚳᚩ•ᚦᛟᚱᚢᛚ•ᚢᚦᛋᚢᛞᛚ•ᚷᛁᚣᛝᚩᛟ•ᛁᛖᚣ•ᛖᚠ•ᛇᛝᛒᛚᛁᚢᚣᚠᛟᚾᛟ•ᛒᛟᚷᛄᚪᚾᛗᚫ•ᚣᚦᚠ•ᛁᛒᛝᛈᚾᛁᚱᚷ•ᛄᛇᚫ•ᚻᚪ•ᚱᛉᛉ•ᚩᛚᚾᚫ•ᛞᚣᛒᚾᚪ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="2•ᚾᚣᛖᛉ•ᚾᚢᛉᛁ•ᛝᛏᛈᚹᛋᚣ•ᛏᛠᛈᛉ•ᚪᛁᛄᛋᚱᚪᛏᛋᛝᛏ•ᚳᚷᚳᚻ•ᛖᛟᚱᚪᛡᚻᚳ•ᛝᛒᛖᚱᛠᚪ•ᛚᛟᛖᛚᚪ•ᚦᛋ•ᚳᚹᚱᚹ•ᚩᚻᚣ•ᚢᛝᚩ•ᛈᛚᛁᛏᚪ•ᚠᛋᛝᛞ•ᚳᚪᚱᛒ•ᚹᛈ•ᚾᚩᚦᚳᚦᚾᛗᚩᛖ•ᚣᛇᚾ•ᚠᛒ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="3•ᛞᚢᛈ•ᚹᚾᛖᚪ•ᚱᛚᛁᚹ•ᚫᛉ•ᛝᚠᛞᚪᚠ•ᛒᛄᛉ•ᛞᛄᛝᚣᛇᚪ•ᚫᛄ•ᛝᛈᚪ•ᚢᛠ•ᛇᛏᚱ•ᛖ•ᚫᛗ•ᚫᛠᚻ•ᛁᚫᛟ•ᛠᚹᚳᛄᚦᚻ•ᛡᚩᚢ•ᚩᚦᚷᛡ•ᚻᛋᚷᚪᛁᛟᛞᚪᛄ•ᛁᚹᛡᛒ•ᛗᛝᛡᛞᚠᛒᛋᛏ•ᛒᚷᚠ•ᚷᛟᚢᚳᚫᛏᛁᛖ•ᚱᚷᛗᚣ•ᚪᚷᚹ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="4•ᛝᛄᛋᛄᛗᚱᛗ•ᚾᛒᛋᛗᛉᛞᚻᛉᛁ•ᚣᛡᚻᚣᛠᛉᚻ•ᛞᛖ•ᚹᛖᚦ•ᚢᚳ•ᛉᛗᚪᚣᛠ•ᚹᚫᚪᚳ•ᚢᚫᚳᛇᚳᚣ•ᛡᚫᛏᛖᚳᚠ•ᛋᚻ•ᛋᚱᚢᚦ•ᛁᛋᛝᛗᛞᚫᚢᛠᚢᚪ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚾᛝᚳ•ᛖᛈᚹᛉ•ᚢᛉᚫ•ᚾᛈᚳᚻᚱᚣᚹᛚᛉᚱᛒ•ᛗᚫᛟᚣᚩ•ᚳᛇᛗ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="5ᚻᚫᛉᚦᛒᛟ•ᛏᛟᚹᛄ•ᚫᛠᛗᚠᚫᚳᚷ•ᛇ•ᚻᚹᛗᚻᛝᚣ•ᛁᚩᛁ•ᛏᛁᛖᛡᛄ•ᛗᚣᛚ•ᚻᚱᚩᛞᛒᛡᛈᛠᛗ•ᚳᛠ•ᛖᛒᚢ•ᚷᛁᚦ•ᛟᚫ•ᛡᚻᛝᛖᚾ•ᚱᛠᛡᛋ•ᚻᛏᛝᚻᚪᚷᚩᛝᚫ•ᚹᛚᛏᚱ•ᚷᛁᚾ•ᛖᛠᛄᛡᛞᛋᚻ•ᛝᚾᚳᛋᚾᛞᛇᚾᛋᛁᚳᛡ•ᚱᛝᛚᚫᚣᛇᛚᚩ•ᚳᛞᚾ•ᛝᚷᛡ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛝᛄ•ᚻᛄᛚᛠᛟ•ᛄᛏᚷ•ᛚᛒᛝᚢᛏ•ᚻᚳ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚫᛞᛟᚫᛟᛗ•ᛟᚫᚪᚻᚱᛗᚢ•ᚣᚢᚣ•ᛈᛗ•ᚪᛄᚫᛟᛠᛚᚠᛖᛡᚢ•ᛉᚻ•ᚪᚩᛡᛒᛠᚢᚷ•ᚻᛏᛠᚪᛞ•ᛋᚹ•ᚦ•ᚾᛋᛁᚻᛒ•ᛉᛠᛝ•ᛒᚢᛚᛟᚢᚾ•ᚢᚦᚩᛗᚪ•ᚾᛞᚫᛇ•ᚫᚣᚪᛋ•ᚣᛝᛡᛗᚷᛇᚾᛈ•ᛠᚳᚻᛝᛚ•ᚠᚷᛡ•ᛁᛡᚪᚠᛒᛈ•ᚳᛋᚦᛠᚦᚫᚱ•ᚷᛞᛚᛟ•ᚷᚱᛁᛇ•ᚣᚩᛟᚢᛝᚱᚷ•ᛗᛏᚷᛒᛈᚷ•ᛗᛏ•ᛗᚣᚹᛒᛏᛒ•ᚷᚣᛈᚷ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚾᚦᛇᛒᚳ•ᚷᛖᛇᛟᛚᛈ•ᚹᚾ•ᚻᚷᚱᛇᛏ•ᛈᚷᛒ•ᚹᛗᛋᚹᛟᚻ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛡᚳᛋ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛈᛞᛋᛡ•ᚪᚹᛏᚳᚹᛟ•ᛗᚹᛁᛒᛞ•ᚷᛇᚢᛚ•ᛉᛋᚫ•ᛟᚻᛚᚦᛒ•ᚣᚪᛚᛞᚦᚠ•ᚻ•ᛞᛝᚩᚢᛋᚪᚫ•ᛖᚦᛁ•ᛏᛄᛏ•ᛝᚦᚾᚳᛉᛏᛝ•ᚳᛈᛁ•ᚾᛏ•ᛒᚾᛡᚱᛒ•ᚢᛈᛋᚦᛁᚳᛈᛋᛁᚹ•ᚹᛚᚣᚾᚢ•ᛒᛁᚪᛠ•ᚹᛟᚳ•ᛠᚢᚪ•ᛚᚦᚹ•ᚠᚾᛏᚳᛡᛁ•ᛚᚩ•ᚾᛗᛄᛠ•ᚦᛟᛄ•ᚪᚦᚹ•ᛡᚾᛖᛠᛈ•ᛒᛋᛄ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚠᚾᛗ•ᚣᚷᛞᚫᚻ•ᚪᛈᛉᚣᚻ•ᛇᛠᚩᛖ•ᛏᛝᛠ•ᛚᛁᛏᚦᚠ•ᛗᚪᚳᛖ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛞᚳ•ᛏᚱᛟᚷᛠᚾᚫᛒᚢᛖᛒᚢ•ᚦᚠᛟ•ᚷᛋᛟ•ᛁᛈ•ᛟᛉᛋᛒ•ᚹᛄᛒᚣᛗᚢᛠ•ᚱᛁᚢᛟᛄᛁ•ᛗᛖᚫ•ᚱᛋᛉᛝ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛠᛈᛚ•ᛞᚩᛚᛁᛉᛠᛝᛖᚱ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚾᛈᛖᚹᛡ•ᚾᛄᛏᚣ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛋᚩᛋᛏᛝ•ᚢᚾᛇᚪ•ᛖᛏᚪᛄᚳᚣ•ᛟᛒ•ᛚᛋ•ᛒᛞᛄ•ᛁᛝᚣᛖᚳ•ᛄᚻᛚᚣ•ᚷᚫᛚᛞ•ᛚᚫᛚᚦᛉ•ᛚ•ᛖᛉᚩᛉᛁᚳᚢᛗᚾᚢ•ᚩᚾᛇ•ᚻᛡᛚᛇᚩᚫᚪ•ᚩᛟᚩ•ᚣᚱ•ᛖᚠᚢ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛁᚻ•ᛟᛚᚾᛏ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚠᛞᚱᛠᚷ•ᛈᚩᛇᚩᛗᛠᛒ•ᛄᛡ•ᛋᛗᚠ•ᛏᚠᚫᚩ•ᛟᚳᛚᛞᛡᛚ•ᚩᚳᛝᚢ•ᛈᚹᛏ•ᚷᚳᛋ•ᚢᛟᚷᚦ•ᚠᛉᚠᛏ•ᚳᛋᛉᛟ•ᚷᚠᛉᚾᛞ•ᛒᛏᛠᛡ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛈᛡᛠᛁᚪ•ᛋᚣᛗᛞᚣᛋ•ᛒᛞᛄᛞ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚩᚾᛏᛚ•ᚳᚪᛝ•ᚱᚷᚻᚷ•ᛄᚹᚠ•ᚪᚢᛇ•ᛞᛏᛗᛄᛁ•ᛝᚫ•ᛉᛈᚳᛈᛠ•ᛟᚪᛒᛁᛁᛋ•ᛇᚷᚻᛋ•ᛇᛡᛒ•ᚠᚹᛝ•ᚫᚪᚠᚩᚣᛡᚪᚾᚻ•ᛒᚦᛟᛇᚣᛟᛁᛒ•ᛟ•ᚩᛋᚹ•ᛞᚳᚠᚪᛁ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛉᛏᛟᚢᚩᛟᚦᛈᛋᚩ•ᚻᛇᚦᛝ•ᛏᛠᚠᛝᛠ•ᚩᛗ•ᛏᚠᚣᛚᚣ•ᚹᛚᛞ•ᚪᛉᛠ•ᚪᛄ•ᚩᛋᛒᛚ•ᚳᛖᚾᚪᚩᚱᛏᚦ•ᚱᛒᚳᚣ•ᛠᛗᚹᛚ•ᚻᛈ•ᛇᛈᛖ•ᛚᛄᚩᛡᚪ•ᛖᛋᚫᚩ•ᛠᛉᛝᚣ•ᛖᚫᛒᛗ•ᛖᚻᚱ•ᛈᚾᛗ•ᚹᛏᛟᚣᚢ•ᚠᛉᛈᛗᚩᚷᚾ•ᛡᛇᚳᚠᛒᛈᛗ•ᛋᛇᛁ•ᛖᛈᚢᚱᛏᚳᚣ•ᛄᛚᚠ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚱᛚᚱᚫᛖᚻᛟ•ᛇᚣᛡ•ᚩᛉ•ᚪᛋᚣᛁᛝ•ᛉᛚᛄ'ᚳ•ᛖᚣᚢᛝᚦᛇᚱ•ᛠᛁᚫ•ᚦᚠᛟᚷᛠᛁ•ᛈᛋᛒ•ᛗᛒᛄᚠᚾᚳᛖ•ᚻᚫᚩᛄ•ᛉᛄᛚᛈᚪᛁ•ᛟᚹᚱᛁᚱᚦᛖᛉ•ᚪᚾ•ᛞᛄᚷ•ᛟᛟᚳᛏᛄᛞ•ᛉᚾᛗᚦ•ᛁᛄᚱ•ᛈᛉᚢᚫᚦᛒᚠᛄᚦ•ᚠᚪᛝᛖ•ᚹᚹᚣᛚᛇ•ᚢᚣ•ᚾᚱᚪ•ᛈᚾᚹ•ᛚᚾᛏᛚᚢᛒᚱᛝᚪᛋ•ᚫᛈ•ᛄᛚᚢᚳᚷ•ᛚᛏᛄᚹᛈ•ᚫᛗᛚ•ᛉᛚᛗᛏᛞᚠᛈᛁ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚠᚳᚦᛗᛄᚹᚱᚪᛚ•ᚩᛝᚱᚢᛈᚱᛟᛡ•ᚳᛉᚱ•ᛇᛏᚦᚾ•ᚱᛇᚫᛞᛟᚻ•ᛒᚾᚣ•ᚠᛡᚪᛡᛖᚫᛞᛄᚢᛖ•ᚦᚱ•ᚩᛇᚱᛡ•ᚣᛁᛉᛇᚻᚩᛠ•ᚫᚻᛡᛝᛠᚦ•ᚾᚣ•ᚾᚠᛁᛝ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛏᚻᚹᚫ•ᛒᛇ•ᛡᚻᛉᛒ•ᛞᛝᚱᛄᚦᚻ•ᚪᚷᚣᛁᚠᚷ•ᛁᛏᛞᛠᛒᚠᚩᛈ•ᛇᛡᛟᚹᚱᚾᚩᛏ•ᛋᚹᚢ⊹ᛖᛡᛖᛡᚦ•ᛉᚪᚷᛈᚾ•ᛋᚱᚠᛞᛝᚻᛖᛄᛞ•ᛄᛡ•ᚱᚹ•ᚷᛝᚪᛒ•ᛄᛈᛄ•ᛏᚠᛉ•ᚪᛄ•ᛁᚠᛉᚢᚩᚣᚻᚦ•ᚻᚾᛁᛒ•ᛡᛟᛡᛋᛈᚣᛉ•ᛠᚢᛠᛚ•ᚠᛝᛗᚻ•ᚦᛒᚩ•ᛗᛚ•ᚩᛠᛋᚦᛠ•ᛇᛋᛉ•ᚠᛗᛒ•ᚫᛋᛇᚾᛡᚾ•ᚢᚫᚹ•ᛞᛠᚢᚾᛝᚠᚾᛖᚫᚻᛄ•ᛁᛖᛏᛡ•ᚷᛁᚩᚾ•ᚳᚢᚫᛗᛈᛋᚪᛡ•ᚷᛚᚣᚹᛟ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚠᚢ•ᛉᚠᚫᛞᚠᛡᛄᚾ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚻᛋᚦᚠ•ᛏᚠᛄᚱᚹᚠᛋᚾᚹᛄᛖᛒᚢᚦ•ᚩᛇᚫᛈ•ᛡᛟ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚢᛁᚩᛄᚩᛇᛟᛄᛞᚩ•ᛈᚹᛞᚷᚱ•ᚠᛟ•ᛇᚷ•ᛄᛟᛇᚫᛋᚫᚣ•ᛒᛏᛞᛟ•ᛠᚻᛡᚱᛠᛠᛉᛋ•ᚠᚾᚣᚱᚠ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚪᚾᛡᚪᛖᚫ•ᚳᛇᛁᛝ•ᛒᛡᛞᛠᚫᛒᛠᚳᛉᚠ•ᚫᛏᛁᚱᚪᛗᚩ•ᛚᛉᛋᚪ•ᛒᚩᛈᚫᚩᛝᚻᛇᛖᛇᚫ•ᚻᛖᛇᛠ•ᚱᛗᛞ•ᚫᛇᛗ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚾᚾᚣᛡ•ᚱᚾᛗᛠ•ᛄᛉᛋᛄ•ᛟᛖᛒ•ᛏᚻᚾ•ᚠᚪᚠ•ᛒᚾ•ᚩᚾ•ᛖᛋᛏᛒᚹᛡ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚻᛏ•ᚩᛟᚩ•ᛒᚾᛖᚳᛁᚹᚣᛟ•ᛟᚩᛒ•ᛋᛖᚩ•ᚫᚻᛟᚠᚫᚷᚩᛄ•ᛟᛒᚻ•ᚳᛖᛁᛚᚫᚣᛚ•ᚢᛚᛁ•ᚾᛟᛏ•ᚫᛈᛟᛈᛝᛗ•ᚳᚢᛁ•ᚣᛋᚳᚢᛡᛇᚩ•ᚠᛖ•ᚷᛟ•ᚻᚫ•ᛝᚠ•ᛗᚠᛝᛉᛞᛁ•ᛗᛝᚣᚪᛝᚠᛉᛁᛟᚷᛚ•ᛇᚩ•ᚫᛡᛏ•ᛄᛏᛠᚢ•ᚷᚦᚣ•ᚦᚾᛟᚣᚩᛖᚻ•ᛁᛋᛖᚣᚦᚪᛡᛝᛟᛇᛚ•ᛡᛏᛝ•ᛁᛚ•ᚠᛉᛡᛠᛏ•ᚠᚾᛄᚠᚻᚳ•ᚻᛞᛠᚣᛟᛝ•ᛉᛇᚻᚩᛋᚻ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛇᛏᚠ•ᛚᚱᛇᚦᚪᛁᛁ•ᛒᚠᛁᛚ•ᛄᛡᛒᚣᛗᚫᚫ•ᛞᚻᛟ•ᚪᚹᛉᛚᛏᛁᚪ•ᛟᛞᛖᚾᛈᚻᚣ•ᚦᛚᛖᛋᛖᛟᚫᛖ•ᛏᚱᚪ•ᛁᚫᚹᚫ•ᛋᛈᚱ•ᛄᛡᚪᛏ•ᚫᚦ•ᚠᛠᚢᛈᚣᚫᛝ•ᚣᚾᚻᛡ•ᚳᛗᚠᚾ•ᛞᛄ•ᛖᚩ•ᛒᚷᚻᚪ•ᛖᛞᛟᚠᛇᛞᛟ•ᛈᚳᛁᚪᛒᚷᛒᛈᛟ•ᛟᛄᚠᚪᛖ•ᛄᚣᚩᛄ•ᚣ•ᚫᛋ•ᚦᛁᚫᛄᚫᛏ•ᛖᛇᚻᛟ•ᚣᚠᚹᛞᚷ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛡᚱᛒᚢ•ᛒᛚᚢ•ᚷᛈᛄᚪ•ᛏᛡ•ᚳᛄᚠᛡᛝᛚᚣᛒ•ᛗᚻ•ᚱᛚᛟᛠᛋᚦᛝ•ᛏᚳᛟᛉᛁ•ᛄᚱᚳᛖᛏᛄᚷ•ᛡᛈᛏᛉᚩᛁᛄᛟ•ᚷᚩᚪᚢ•ᚣᛖᚪᛋᛟᛇᚢᚪᛡ•ᛗᚱᛚᚳᚠ•ᛒᛗᛝ•ᚻᛉ•ᛠᛄᚫ•ᛉᚪᚷᚻᚣᛏᛖᛝ•ᛉᛉᛗᚾᚫᛋ•ᚱᛗᛞᛋᚳ•ᚦᛚᛟ•ᛝᛇᚢ•ᚻᚩ•ᛏ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚢᛁᚦᛄᚾᚠᚱᚦ•ᛋᛟᚷᛠᛗᚪ•ᛝᛚᚪᛁᛒᛠᚢᛋ•ᚩ•ᛖᛋᛝ•ᚠᛡᚢᛟᛞᛇᚪ•ᛞᛡᛒᚹᚩ•ᛄᛋ•ᛟᛝᛏᚳ•ᚻᚾᛇᛋ•ᛗᛚᚻᛞᛖᛈ•ᚫᛄᚱᚪᚢᚻᚱᚦᚱ•ᛟᛄ•ᛟᛗᚩᛟᛏ•ᚫᛇ•ᛉᛒᚳ•ᛄᛁ•ᚪᚩᛉ•ᚹᚪᚾᛈᛏᚢᚣ•ᛁᛒᚢ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚦᚩᛡ•ᛗᚳᚠᛉᚱᛁ•ᚪᛗᛏᛒ•ᛗᛚᛁᚦᛏᛠᛋᚾᚷᛚ•ᛏ•ᛇᛈ•ᚩᛚᛞ•ᛚᚹᚳᛄᚹᛉ•ᚪᛡᚹᛇ•ᛖᛖᚹ•ᛏᚪ•ᚣᚠᛉᚳ•ᛗᚩᚷᛞᚷ•ᛚᚳ•ᛒᚣᛋᚣᚠᛞᚣᛝ•ᛠᛇᛏᚩᚢᚫ•ᛟᛁᛒ•ᛏᚾᚫᚠ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛄᛟᛗᚾᛈ•ᛠᛡᚩᛏᛡᚪᚱᛞ•ᚪᛝᛈᚹᛗᛄᛟᛠᚩ•ᛚᚹᛉ•ᚱᛗ•ᚩᛏᚹᛄᚹᚾ•ᚷᚳᛠ•ᛄᚳᚢᚱ•ᛟᛇᛟᚾᚻᚫᛉ•ᚣᛚᚩ•ᚩᛡᚳᚻᛄ•ᛋᚣᚹᛁ•ᚣᚠᛋᚾᚪ•ᚷᛖᚾᛄᚪᚹᛠ•ᛞᚠᛟ•ᚢᛁ•ᛖᛇᚦ•ᚫᛞ•ᚳᛄ•ᚷᚢᚻᚣᚻᛁᛒᛉᚾ•ᚹᛝᚻᛏᛉᚫᛁᛄᚢ•ᛞᚠᛡᚫ•ᛋᛁᚹᛝᛈ•ᛗᛉᛄᛈ•ᛞᛗᛝ•ᛇᛚᛞᚣ•ᚠᚩᛞ•ᛝᚷᚾᛇ•ᚷᛖ•ᛚᛉᚣ•ᚫᛚᛖᛉ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛡᛝᛋ•ᚳᛁᚦ•ᚷᛏᚣ•ᚹᚩ•ᛝᛖ•ᛒᚪᛗᛏᚪᚷᛒ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛈᛡᛟ•ᚪᛉᛝᛒᛞᛉᛄᚦᚢ•ᛏᛇᛖ•ᚣᚪᚳ•ᛠᚦᚹ•ᛏᛉᚩᚳᛞᛒ•ᛟᚩᛠᚾᚠᚪ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛚᛗᛖᛁᚦᚫᚪᛡᛄᛁᚪᚱ•ᚦᚱᛖᛖᚣᛋᚾ•ᛖᛏᚢᚻᛈᚳᚦᛋ•ᚳᛇᛉᛖᛇᚠ•ᛞᛠᛏᛈ•ᚣᛇᛠᚢᛏ•ᛉᚦᚷᚻ•ᚫᚾᛠᚱ•ᛡᛒᛏᛁᛉ•ᚩᚢᛝ•ᛚᛒᛇᚩ•ᛟᛉ•ᚦᛞᚷᚠ•ᚩᚱᛈᚪᛏ•ᚫᛋᚪᚦ•ᛖᛟᚪᛝᚫ•ᚣᛒᛚ•ᛡᚦᚾᚠᛈᛟᛡᚾ•ᛖᚹ•ᛖᛗᚩ•ᛉᚹᚦᛠ•ᛁᚦᛒᛖᚱ•ᛟᚳᛉ•ᛈᛖ•ᛁᚢᚦ•ᛈᚠᛞᛈᛄ•ᛁᛟᚻ•ᛒᚦᛏᚩᚳᚢᛚ•ᛞᛄᛝ•ᚦᛄᛁᚪ•ᚹᚣ•ᚢᛝᚾ•ᛋᚾᛈᚠᚫᛒᛄᚫ•ᛡᛗᚹ•ᛇᚪᚩᚾᛄᚳᛚᛒᛉ•ᚣᛠᚦᚹ•ᛝᛚᛗᚳᛡᛇᚠᚫᛠᛁᚦ•ᛒᛠᛚᚦᚳᛞᛁᛇ•ᚠᚢᛉᛋᛉᛁᚦᚫᛋᛗ•ᚦᚹ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛈ•ᛒᛋᛏᚫᚾᚱᛁ•ᚦᛇᛡᚱᛚᛡᚹ•ᚢᚩᛋᚱ•ᚹᚫ•ᛒᚹᛡᛖᛟᛄ•ᛡᚣᛖᚩᛖᛡᚷᚫᚠᚾᚹ•ᛟᛏᚫᚠᛄᚹᛠ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚦᛞ•ᛁᚫᚩᚾ•ᛋᚷᛈᚪᛖᚩ•ᚣᚦᚹ•ᚾᚷ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛠᛋᚩᛇᛏ•ᛝᛚᚷᛞ•ᛒᛈᛈ•ᛗᛁᚪᛖ•ᛚᛏᛁ•ᚫᛄᛖ•ᛒᚾᚠᚪᛋᚷᛒᚠ•ᚫᚹᚣᚷᚢᛡᚠᛠ•ᛖᛋᛞ•ᛚᚳᛒᛞᛏᛈ•ᛖᚾᛈᚣ•ᚱᚠᚻ•ᚫᛝ•ᛟᚪᛗ•ᛒ•ᛡᛚ•ᛝᛋᚱᚢᚹᚱᚣᚻᚹ•ᚹᛡᛈ•ᛁᚻᚾᚻᚱ•ᚳᛖᛏᚫᚩᛋ•ᚣᛋ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛝᚫᛡᛝᚫ•ᚻᚦ•ᛇᚪᛞᛋ•ᛒᛁᚳᛈ•ᛇᛒᛟᚫ•ᛠᛝᛖ•ᛝᛠᚣ•ᛒᚣᛉᚻᚢᚠᚦᛞᚹ•ᛗᚢᛁᛡᛄᚩ•ᛋᛇᚫᛇᛝᚱ•ᛚᛇᛠ•ᛏᚩᛄ•ᚩᛝᛈ•ᚱᚻᛠᚢᛉᚦ•ᚣᚢᛋ•ᛡᛚᛖᚷᛗᛝᚹᚻᚱᛋ•ᚢᛟᚣᛠᚷᚩᚷ•ᛇᛁᛖ•ᛠᛄᛇᛁᚾᛄᚩᛗᚱᛡᛉ•ᚠᚻᚳ•ᚪᚩᚪᚫᚻᚳᛁᚦ•ᛄᚷ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛝᛖᚢ•ᛡᛏᛁ•ᛚᚩᚱᛈ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚠᚪ•ᛈᛞᚱᛒ•ᛝᛁᛋ•ᚷ•ᚠᚾᛈᚠᛒ•ᛟᚦᛁᛠᚪ•ᛡᛏᚾᚳ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚦᛟᚻᛈᛖᛚᚫ•ᛟᚠᛗ•ᛡᛝ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛒᛝᚦᛝᛠᚠ•ᛇᛗᛟ•ᚩᛠᛈ•ᛁᛡᚱ•ᚹᚹᛟᚩᛒᚩ•ᚾᚩᛄᛟᚾ•ᚦᛡᚠ•ᚩᛄᛞᚦᛏᛁ•ᛈᚾᚪᚱᛄ•ᛉᚱᚣ•ᛝᛡ•ᛏᛗ•ᛈᛞᚣᚻ•ᛗᛝᚫᚳᛇ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛡᚣᛄᛟ•ᛝᚩᚢᛇᛁᚱ•ᛏᚪ•ᚩᚻᚪᛚᚫᛚᚪ•ᛋᛈ•ᛏᚪᛄᚳᚦᚢᛏᚹᚦ•ᛗᚷᛖᛗᚣᛡᛁᛞ•ᚢᛋᚠᛒ•ᛟᛚᛟ•ᚪᛒ•ᚦᛚᚣ•ᚳᛠᚣ•ᛞᛇᛁ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚹᛉ•ᛟᛝᛒᚢᛋᛞᚻᛞ•ᚢ•ᛠᚱ•ᚫᚩᚻᛝᛒᚪᚹ•ᛈᛡᚾᛚᛇ•ᛖᛟᛝ•ᛡᚠᛇᛡ•ᚳᚦᚹ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛚᚦᚪᛁᛈ•ᛞᛟᛄ•ᚢᛉᚢᚾᛠᚠ•ᚩᚾᚪ•ᚱᛠᚷ•ᛗᚢ•ᛗᛁᛄᛒᛗᚱᚾᛗ•ᚩᚾᚠᚣ•ᛗᚠᛇᚠᛄ•ᛒᛡᛈᛄᛖᛡᛏ•ᛈᛟᚫᛏᛟ•ᚻᛖᚾ•ᚳᛇᚩ•ᛋᚻᚫᛇ•ᛝᛁᛟ•ᛇᚠᚢᛞᚣᚪᛚᚠᛡ•ᛖᛄ•ᚠᛚᛟ•ᛁᚳ•ᛁᛝᚷᚦ•ᛗᛋᚫᚷᚪᛠ•ᛗᛁ•ᛒᛡᛏᚾ•ᛝᛗᚦ•ᛏᚣᚫᛄ•ᛖᚻᚠᚪᛡᚷ•ᚪᛗᛁ•ᛞᛉᛏ•ᚢᛖᚦᚾ•ᛖᚪᛈᚹᛠᛚ•ᛒᚢᚱᛡᛟ•ᚪᚣ•ᛟᛇᚹᛄᛈᛞ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚹᚹᛈ•ᚠᛡᛚᛉᛒᚾ•ᚳᛗᚾᚱᛗ•ᚻᚦᚫᛞᛄ•ᛒᛡᚫ•ᛇᚹᛗᚢ•ᚪᛈᛡ•ᛈᛁᛄ•ᚪᚢᚾᛠᛖᛞᛗᚪ•ᛏᛟᛗ•ᛋᛞᛝᚷᛚᛋᛞᛝ•ᛟ•ᛋᛄᛞ•ᛚᛟᚠᛄᚫᚠᚪ•ᛝᛟᚣᛈ•ᚣᚩᛒᚷᚳᛖᛏᚹ•ᚪᛋᛒ•ᛗᛠᚣᛇᛗᚫᛚᚱ•ᚹᛇᛄᛒ•ᛈᛚᚠᛈ•ᚠᛗ•ᛝᚪᛇᚾᛟᚹᛇᛉ•ᚣᚫᛉᛞᛟᚱᛒ•ᛡᚱᛟ•ᚹᛏᚷᚱᛄᛖ•ᛠ•ᛈᛚᛞ•ᚻᚦᚱ•ᚦᚣᛚᛉ•ᛠᛈᚫᚠᚪ•ᚫᚪᛒ•ᛈᛋ•ᛗ•ᛏᚫᚳᛈᛝᚹᚦ•ᚻᛠ•ᛞᚩᛄᚷ•ᛋᚩᛠᚳᛖᛋ•ᚣᛖᚫ•ᛈᚦ•ᛁᛇᛈᚳᛝ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛈᚳᛇᚢᛏᚳᛡᛇᛝᚾᚢᚻᚦ•ᚣᚠᛗᚾ•ᛝᚠᛄᛉᛟᚱᛗ•ᛝᛠᛄᛏᚳ•ᚢᚷᚦ•ᚠᚦᛋ•ᚪᛈᚩᚪᚫᛞᛋᛝ•ᛒᛗᚩᚷ•ᚹᚠᛗᛖ•ᛠᛇᚻᚠᚻᚳᚱᚫ•ᛝᛗᛉᚳ•ᛋᚪᚹᛋᛠ•ᚩᚣᛚᛉᛝ•ᛠᛟᛉᛟᛠᛡᛝᛒ•ᛝᚳᚫᛁᚱ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛒᚠ•ᛏᚣᚣ•ᛠᛒ•ᚣᛚᚩ•ᛇᛉ•ᚩᚷᛗᚩ•ᚠᛚᛟᛝᚦᛠ•ᚦᚣᛖᚣ•ᚾᚷᚾ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛡᛏ•ᛄᛟᚾᛁ•ᛋᛟ•ᛠᚦᚣ•ᛋᛒ•ᚫᛚᚪᛄᛡᛖᚷᛉᛡᚾᛉᛏ•ᛡᛒᚻᛚᚷ•ᚢᚦᛠ•ᚢᚾᛁᚩᛗᛠᛁᚷ•ᛟᚦᚱᚣ•ᛒᛖᛠᚩᛈ•ᛗᛏᚱᚫᚢᚻᛁᛝ•ᛇᚳᚠ•ᛄᚾᚱᚷ•ᛟᚷᚻᚣᚻᛇᚫᛠᚫᚣ•ᚢᛗᛈ•ᛉᛁᚢᚾᚩᛟᚾ•ᚷᛞᚦ•ᛡᚫᚹ•ᛞᛟᛖᚱ•ᛗᚾᛖᚻᚷᛒᚢᛄ•ᚢᚦᛗᛖᛞᛝ•ᛒᚷᚣᚱ•ᛖᛁᚢᛄ•ᚣᛡᛚᚢ•ᛄᛟ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛠᛉᚣᛇᚱ•ᚩᛈᛋᚳᚫᛗᛇ•ᚾᛄ•ᛖᚠᛋ•ᛖᚠᚪᛝ•ᚢᛝᛄᛇᚷᚠᛝᚱᛁᚦ•ᛄᚢᚫ•ᚣᛋᚠᛖᚢᛋᚫᚣᛠ•ᛁᛏᛟᚱᛏᛟᚩ•ᚷᚾᚻ•ᛞᛗᚩᚳᛞᛖᛏ•ᚹᛉᛞᛚ•ᚩᚫᛄ•ᛇᚢᛒ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛗᛏ•ᛞᛗᛖ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛏᛈᚹᛇᛋ•ᚹᛒᛇᚦ•ᚾᚻᚷᛄ•ᚱᛡᛞᛡᚦᚪᛁᛇᚫᛉᛚ•ᛇᛠ•ᛡᚪᛄ•ᚻᚱ•ᚦᛈᛞᛄᛝᚩ•ᚷᚠᛇᛗᚳ•ᚻᛞᚩᛏᚳ•ᚢᚱ•ᛈᚾ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᚪ•ᛗᛝᛞᛡᚦᛉᛁᛗ" >> gemput.txt
./quoteomatic -patternOrGemSum="gemsum" -text="ᛡᛞᛈᛝᚢᚹᚪᛗ•ᛏᚪᛝ•ᛝᚦᛡᚹᛋᚻ•ᛁᚳ•ᚫᛈᚫᚷᚩ•ᛗᛁᚪ•ᛖᚩ•ᛏᚹᚩ•ᚠᚣᚢᛏᛄ•ᚦᛄᛠᛖᚳᚾᛠ•ᚳᛠᛖ•ᚱᚩᚢᛉ•ᛞᚹᚻᛒᛝᚠᚪᚳᛄᚢ•ᚩᛄᛡᛠᛁᛚᚷᚻ•ᛒᚢᛄ•ᛉᚪᚳᚹᛡ•ᛗᚩᛈᚣᛞᛡᛚᛈ•ᛇᛁᚦᚱ•ᚣᚷᛗ•ᛉᛟᚷᛋ•ᛗᛈᛄᛟᛞ•ᛟᛏᛡᛟ•ᛏᛝᛁ•ᛗᛝᚣᚪᚫ•ᛝ•ᚱᚣᛄ•ᚾᛚᚢᛉᛒ•ᚻᛈᛄᚩᛠ•ᚷᚫᚹ•ᛉᛋᛞᚳ•ᚢᛏ•ᛟᚻᛇᚾᛈᛏ•ᛠᚣᛒᚢᚷ•ᚷᚪᛇ•ᚾᚷᚩᛖᛚᛗᛒᚦ•ᚣᛡᛟᛇᚣ•ᛗᚳᛟᚦ•ᛖᛚᚱᛇᛈᚱᛞᚣ•ᛉᛞ•ᛝᚣᛈ•ᛋᛖᛉᚹ•ᚳᚷᚠᛞᚱᛖ•ᛞᛖᚹᚩᛇᛟ•ᚻᚩᛟ•ᛒᛋ•ᚻᛠᚪᚳᛁᛗᛉᛄᛗᛖ•ᛗᛚ•ᚷᚩᛏᚦᛉᛖᛠᚱᚷᚣᛝ•ᚫᛗᛁᚹ•ᛋᛒ•ᛉᛗ•ᛋᛇᚷᛞᚦᚫ•ᚠᛡᚪᛒᚳᚢ•ᚹᚱ•ᛒᛠᚠᛉᛁᛗᚢᚳᛈᚻᛝᛚᛇ•ᛗᛋᛞᛡᛈᚠ•ᛒᚻᛇᚳ•ᛇᛖ•ᛠᛖᛁᚷᛉᚷᛋ•ᛖᛋᛇᚦᚦᛖᛋ•ᚦᛟ•ᚳᛠᛁᛗᚳᛉ•ᛞᛄᚢ•ᛒᛖᛁ" >> gemput.txt